### ISSUE TITLE
bson error: ImportError: No module named objectid

### ISSUE THREAD

**Issue by twiecki** [hyperopt/hyperopt#132]
Running unittests:

```
  File "hyperopt/hyperopt/__init__.py", line 7, in <module>
    from .base import STATUS_STRINGS
  File "hyperopt/hyperopt/base.py", line 42, in <module>
    from bson.objectid import ObjectId
ImportError: No module named objectid
```

This is with bson 0.3.3 installed via pip. Is a different version required?

**Comment by anuragreddygv323** [comment]
Is there a solution to this ? I am getting the same error with installing hyperopt

**Comment by robertmuil** [comment]
@anuragreddygv323 I had same issue, try this:
`pip uninstall bson && pip install pymongo`

**Comment by neuronalX** [comment]
> pip uninstall bson && pip install pymongo

Thanks @robertmuil, it worked for me!
