### ISSUE TITLE
true_loss vs loss semantics

### ISSUE THREAD

**Issue by xrgcfsqtj** [hyperopt/hyperopt#137]
Does hyperopt not use the true_loss of a function to determine which hyperparameters configurations are used? The tutorial seems to indicate loss is to be used for the training error, and true_loss for the generalization error, so if we want to to minimize generalization should we just store it as loss?

**Comment by KOLANICH** [comment]
Could anyone write the docs about the difference between `loss` and `true_loss`? I mean, why we need it and why just loss is not enough and what is the difference between supplying crossvalidation error as `loss` vs `true_loss`.

**Comment by mjmikulski** [comment]
Yeah, the [tutorial](https://github.com/hyperopt/hyperopt/wiki/FMin) talks only about `spiffier` plots, whatever that means...
