### ISSUE TITLE
Example code for STATUS_FAIL

### ISSUE THREAD

**Issue by xrgcfsqtj** [hyperopt/hyperopt#143]
Is there no example code for using STATUS_FAIL in hyperopt. The tutorial says you don't need to provide a loss when the status is STATUS_FAIL, but when I try to use it in my own code I get the exception ValueError: ('dictionary must have "loss" key', ['status']. Maybe I'm just doing it wrong, but if this is a bug it's simple to replicate.

fmin(fn=lambda x : {'status':STATUS_FAIL} , trials = Trials() , max_evals = 10 , algo = rand.suggest , space = hp.uniform('s',0,1) )

ValueError                                Traceback (most recent call last)
<ipython-input-13-eaa6885ff762> in <module>()
----> 1 fmin(fn=lambda x : {'status':STATUS_FAIL} , trials = Trials() , max_evals = 10 , algo = rand.suggest , space = hp.uniform('s',0,1) )

/home/malcolm/env/lib/python2.7/site-packages/hyperopt/fmin.pyc in fmin(fn, space, algo, max_evals, trials, rseed)
    326 
    327     rval = FMinIter(algo, domain, trials, max_evals=max_evals)
--> 328     rval.exhaust()
    329     return trials.argmin
    330 

/home/malcolm/env/lib/python2.7/site-packages/hyperopt/fmin.pyc in exhaust(self)
    289     def exhaust(self):
    290         n_done = len(self.trials)
--> 291         self.run(self.max_evals - n_done, block_until_done=self.async)
    292         self.trials.refresh()
    293         return self

/home/malcolm/env/lib/python2.7/site-packages/hyperopt/fmin.pyc in run(self, N, block_until_done)
    263             else:
    264                 # -- loop over trials and do the jobs directly
--> 265                 self.serial_evaluate()
    266 
    267             if stopped:

/home/malcolm/env/lib/python2.7/site-packages/hyperopt/fmin.pyc in serial_evaluate(self, N)
    182                 ctrl = base.Ctrl(self.trials, current_trial=trial)
    183                 try:
--> 184                     result = self.domain.evaluate(spec, ctrl)
    185                 except Exception, e:
    186                     logger.info('job exception: %s' % str(e))

/home/malcolm/env/lib/python2.7/site-packages/hyperopt/fmin.pyc in evaluate(self, config, ctrl, attach_attachments)
    117             if 'loss' not in dict_rval:
    118                 raise ValueError('dictionary must have "loss" key',
--> 119                         dict_rval.keys())
    120         else:
    121             raise TypeError('invalid return type (neither number nor dict)', rval)

ValueError: ('dictionary must have "loss" key', ['status'])

As far as I can tell it looks like the check for 'loss' being in the dictionary is done independently of checking the 'status'.

**Comment by michaelmior** [comment]
Looks like this has been resolved. Feel free to reopen if you're still having an issue.
