### ISSUE TITLE
exhaustive search unavailable 

### ISSUE THREAD

**Issue by hmitiche** [hyperopt/hyperopt#181]
I need to do an exhaustive search over one parameter with a range of size 15. The "hp.choice" with "rand.suggest" algo is not really adequate to simulate a full search, because if we set max_evals (of fmin) at 15 only, some param config may be missed (due to the random pickup of the param value). Otherwise, if we set max_evals at a higher value like 100, it's more likely to end up covering all the range values, but with extra unnecessary computation time.

**Comment by ashay88** [comment]
Hi,
I am stuck on 
_**create a memo that hashes your fmin function arguments to the fmin
function return value**_

Could you please help me out to do this. The documentation was not very clear on how to add things to the memo. I have tried going through the source code, but my attempts to modify the memo across multiple runs through MongoTrials has not succeeded. I also had a look at the some of the other github projects using this library as a dependency, but it was not too clear there too.

I am using the following code 
```
from hyperopt import pyll
@hyperopt.fmin_pass_expr_memo_ctrl
def realtime_objective(expr, memo, ctrl):
    config = pyll.rec_eval(expr, memo=memo)
    # .. config is a configuration point
    # .. ctrl can be used to interact with database
    return {’loss’: f(config),
               ’status’: STATUS_OK, ...}
```
from [http://iopscience.iop.org/article/10.1088/1749-4699/8/1/014008/ampdf](http://iopscience.iop.org/article/10.1088/1749-4699/8/1/014008/ampdf)
