### ISSUE TITLE
Parameters conditional on continuous parameters?

### ISSUE THREAD

**Issue by mfeurer** [hyperopt/hyperopt#190]
For a neural network I want to express the depth as a continuous integer value. Is this the right way to go?

```
@scope.define
def _space(depth, num_units_1, num_units_2):
    space = {'depth': depth}
    if depth >= 1:
        space.update({'num_units_1': num_units_1})
    if depth >= 2:
        space.update({'num_units_2': num_units_2})
    return space

space = scope._space(hp.quniform('depth', 0, 3, 1), hp.quniform('num_units_1', 16, 1024, 15), hp.quniform('num_units_2', 16, 1024, 15))
```

I am not sure about what happens if depth is set to zero or one (no or one hidden layer). Will num_units_2 (number of neurons in the second hidden layer) be evaluated (which I don't want)?

**Comment by Nithanaroy** [comment]
Is there an op for continuous hp, like `scope.switch` or `hp.choice` are for discrete? I want to conditionally set hp2 based on the value of hp1. Both hp1 and hp2 are of `hp.uniform` type.
