### ISSUE TITLE
Error that I can't understand :(

### ISSUE THREAD

**Issue by JaspreetO4t1qbit** [hyperopt/hyperopt#198]
File "/Users/Jas/Downloads/hyperopt/hyperopt/fmin.py", line 319, in fmin
    rval.exhaust()
  File "/Users/Jas/Downloads/hyperopt/hyperopt/fmin.py", line 198, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/Users/Jas/Downloads/hyperopt/hyperopt/fmin.py", line 172, in run
    self.serial_evaluate()
  File "/Users/Jas/Downloads/hyperopt/hyperopt/fmin.py", line 89, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/Users/Jas/Downloads/hyperopt/hyperopt/base.py", line 832, in evaluate
    dict_rval = dict(rval)
TypeError: 'NoneType' object is not iterable

**Comment by JessitaMS** [comment]
I have the same issue, but before visualize the best params. My code:

`from hyperopt import hp
from hyperopt.pyll.base import scope

space = {'batch_size': scope.int(hp.quniform('batch_size',1024,2048))}

def fnn (params):
    # Variables
    tmp_x = pad(preproc_english_sentences, preproc_french_sentences.shape[1])
    tmp_x = tmp_x.reshape((-1, preproc_french_sentences.shape[-2]))
    english_vocab_size = len(english_tokenizer.word_index)+1
    french_vocab_size = len(french_tokenizer.word_index)+1

    # Hyperparameters
    learning_rate = 0.005
    
    # TODO: Build the layers (Objetive function)
    model = Sequential()
    model.add(Embedding(english_vocab_size, 256, input_length=tmp_x.shape[1], input_shape=tmp_x.shape[1:]))
    model.add(GRU(256, return_sequences=True))    
    model.add(TimeDistributed(Dense(1024, activation='relu')))
    model.add(Dropout(0.5))
    model.add(TimeDistributed(Dense(french_vocab_size, activation='softmax'))) 

    # Compile model (Loss function)
    model.compile(loss=sparse_categorical_crossentropy,
                  optimizer=Adam(learning_rate),
                  metrics=['accuracy'])
    
    

    # TODO: Train the neural network
    embed_rnn_model2 = model

    embed_rnn_model2.summary()

    embed_rnn_model2.fit(tmp_x, preproc_french_sentences, batch_size=params['batch_size'], epochs=10, validation_split=0.2)

    print(logits_to_text(embed_rnn_model2.predict(tmp_x[:1])[0], french_tokenizer))

from hyperopt import fmin, tpe, Trials
trials = Trials()
best = fmin(fnn, 
            space, 
            algo=tpe.suggest,
            max_evals=50,
            trials=trials)`

The error:
[/usr/local/lib/python3.10/dist-packages/hyperopt/base.py](https://localhost:8080/#) in evaluate(self, config, ctrl, attach_attachments)
    895             dict_rval = {"loss": float(rval), "status": STATUS_OK}
    896         else:
--> 897             dict_rval = dict(rval)
    898             status = dict_rval["status"]
    899             if status not in STATUS_STRINGS:

TypeError: 'NoneType' object is not iterable
