### ISSUE TITLE
hyperopt-mongo-worker on windows

### ISSUE THREAD

**Issue by tfriedel** [hyperopt/hyperopt#207]
Currently hyperopt-mongo-worker is only working on unix, not on windows. It would be great if this could be fixed in the future.

**Comment by thijsgelton** [comment]
Has this ever been fixed? I can not start hyperopt-mongo-worker via the command line. I pip installed it (v 3.6) in my virtual environment and my global site-packages. I am getting a 'hyperopt-mongo-worker is not recognized as an internal or external command operable program or batch file' error.

**Comment by ivan-marroquin** [comment]
I am having the same issue. the script hyperopt-mongo-worker is for linux OS but not for windows. Is there any plan to create a script for windows?

many thanks!
