### ISSUE TITLE
Prior_sigma is negative.

### ISSUE THREAD

**Issue by harri-edwards** [hyperopt/hyperopt#221]
The following code:

    from hyperopt import hp, fmin, tpe, Trials

    space = (
    hp.qloguniform( 'hidden_dim', np.log( 50 ), np.log( 500 ), 1 ),
    hp.loguniform("L1",np.log(10**(-2)), np.log(10**(-7))),
    hp.loguniform("L2",np.log(10**(-2)), np.log(10**(-7))),
    hp.quniform("pool_width1", 1,20,1),
    hp.quniform("pool_width2", 1,20,1),
    hp.quniform("filter_width1", 2,20,1),
    hp.quniform("filter_width2", 2,20,1),
    hp.quniform("n_filters1", 1,5,1),
    hp.quniform("n_filters2", 1,5,1),
    hp.choice("dropout_p", [0,0.5]),
    hp.quniform("n_iter", 5,100,1),
    hp.quniform("mini_batch_size", 10,150,1)
    )

   objective_foo = obj.objective

   trials=Trials()

   best=fmin(fn=objective_foo, space=space, max_evals=100,
             algo=tpe.suggest, trials=trials)

eventually produces an assertion error  error "assert prior_sigma > 0" from the adaptive_parzen_normal function on line 464 in tpe.py.

**Comment by w1kke** [comment]
You run into problems with the following parameters:
hp.loguniform("L1",np.log(10**(-2)), np.log(10**(-7))),
hp.loguniform("L2",np.log(10**(-2)), np.log(10**(-7))),

As the prior_sigma is calculated in tpe.py like this:

prior_sigma = 1.0 * (high - low)

high is the upper limit, low the lower limit. In our example it is low = np.log(10**(-2)) = -4.605 and high = np.log(10**(-7)) = -16.11 -> therefore prior_sigma is not > 0 and you get the error.

**Comment by jaberg** [comment]
Thanks for the bug report, and explanation! The error message should have
been better.
