### ISSUE TITLE
Multiple arguments as input for fmin's fn function

### ISSUE THREAD

**Issue by KarolP87** [hyperopt/hyperopt#228]
In the parameter description in the source code of fmin we read:

fn: This function will be called with a value generated from `space` as the first and possibly only argument.

In my case I defined fn as a score of a cross validation procedure. I want to apply fmin to minimise this score. For the cross-validation procedure, aside from the hyper parameters, I also need the data matrix as input.  From the exerpt above I assume that there is a possiblity to define fn with more than 1 parameter, but how to?

**Comment by dwf** [comment]
One simple way is to use functools.partial.

**Comment by KarolP87** [comment]
Oh I forgot to add that fmin() is called within a function. Somehow I thought it's not feasible to define a function within another function. Thanks for your solution, it works! Another possible way to fix the additional parameters is to use lambda:

def general_optimisation_function(data_matrix, space,...):
      fn = lambda args: objective_function(data_matrix, args) 
      best = fmin(fn, space,...)

**Comment by dwf** [comment]
lambda has the possible disadvantage of not being picklable, but yes,
that's an option.
