### ISSUE TITLE
AttributeError: 'module' object has no attribute 'random'

### ISSUE THREAD

**Issue by mahdiman** [hyperopt/hyperopt#247]
I am trying to run this code sample:

```
from hyperopt import fmin, tpe, hp
import hyperopt
algo=hyperopt.random.suggest
space = hp.uniform('x', -10, 10)
```

but there is a problem arises:

```
AttributeError: 'module' object has no attribute 'random'
```

can anyone help?

**Comment by MantasMiksys** [comment]
You should use `hyperopt.rand.suggest ` instead of `hyperopt.random.suggest`.

**Comment by nd26** [comment]
Why not change the documentation?
https://github.com/hyperopt/hyperopt/wiki/FMin

**Comment by DarkKnight1991** [comment]
Just a reminder guys.. documentation still shows "random" instead of "rand"

**Comment by mmcdermott** [comment]
Still shows random.
