### ISSUE TITLE
Initial space/search position

### ISSUE THREAD

**Issue by vmirnv** [hyperopt/hyperopt#249]
Many thanks for an awesome lib!

Is it possible to add a starting position for a search?

Like this: `hp.quniform('eta', 0.001, 0.3, 0.001, start_from=0.1)`

It could save a ton of time at some cases.

**Comment by jaberg** [comment]
You can do this. The Trials object stores experiment progress. If you just
"sample" that initial point first, then it will inform the search
algorithms. One way to do this would be to search for a while with really
tight intervals, then search a broader area by changing the distribution
bounds but keeping the same variable names and the same Trials object.

**Comment by VladMironov** [comment]
@jaberg I solved this problem with tight intervals, yeah: `hp.uniform('eta', 0.1, 0.1)`
Will check Trials, thanks!

**Comment by michaelmior** [comment]
Closing since it seems like this is resolved. Feel free to reopen if you're still having an issue.
