### ISSUE TITLE
hp.quniform giving float values for integer range.

### ISSUE THREAD

**Issue by muditbac** [hyperopt/hyperopt#253]
When using hyperopt for optimizing XGBoost it throws error.
`XGBoostError: b"Invalid Parameter format for max_depth expect int but value='4.0'"`

I have set range as `{'max_depth': hp.quniform('max_depth', 1, 13, 1),}`

**Comment by erlendd** [comment]
I had the same issue recently, but it's easily resolved by replacing hp.quniform by hp.choice('max_depth', np.arange(1, 13+1, dtyle=int).

**Comment by yassineAlouini** [comment]
I had the same problem as @muditbac. As suggested by @erlendd, the `hp.choice('max_depth', np.arange(1, 14, dtype=int))` seems to solve the issue. Thanks for the help!

**Comment by shahlaebrahimi** [comment]
I had the same problem so I used the suggested approach by @yassineAlouini and @erlendd. It solves the issue just in some iteration so again that error is reported.
I would greatly appreciate if you could let me know how to deal with it?
regards,

**Comment by shahlaebrahimi** [comment]
Some part of the error is:
```
.637468	eval-mlogloss:0.67373
Multiple eval metrics have been passed: 'eval-mlogloss' will be used for early stopping.

Will train until eval-mlogloss hasn't improved in 10 rounds.
[1]	train-mlogloss:0.434509	eval-mlogloss:0.487707
[2]	train-mlogloss:0.395639	eval-mlogloss:0.462347
[3]	train-mlogloss:0.390629	eval-mlogloss:0.468641
[4]	train-mlogloss:0.355771	eval-mlogloss:0.420497
[5]	train-mlogloss:0.355757	eval-mlogloss:0.419786
[6]	train-mlogloss:0.355836	eval-mlogloss:0.418852
[7]	train-mlogloss:0.351659	eval-mlogloss:0.415997
[8]	train-mlogloss:0.351758	eval-mlogloss:0.415255
[9]	train-mlogloss:0.351417	eval-mlogloss:0.417624
[10]	train-mlogloss:0.351384	eval-mlogloss:0.418595
[11]	train-mlogloss:0.346445	eval-mlogloss:0.418504
[12]	train-mlogloss:0.346458	eval-mlogloss:0.425383
[13]	train-mlogloss:0.342745	eval-mlogloss:0.421794
[14]	train-mlogloss:0.343302	eval-mlogloss:0.417118
[15]	train-mlogloss:0.34298	eval-mlogloss:0.426841
[16]	train-mlogloss:0.34323	eval-mlogloss:0.428758
[17]	train-mlogloss:0.342802	eval-mlogloss:0.424159
[18]	train-mlogloss:0.342729	eval-mlogloss:0.421804
Stopping. Best iteration:
[8]	train-mlogloss:0.351758	eval-mlogloss:0.415255

	Average of best iteration 11.25

	Score 0.3786545

best parameters {'min_child_weight': 1.0, 'eta': 0.4, 'colsample_bytree': 0.9, 'max_depth': 6, 'gamma': 0.0, 'subsample': 0.8}
Training with params : 
{'min_child_weight': 1.0, 'eta': 0.6000000000000001, 'num_class': 3, 'gamma': 0.0, 'colsample_bytree': 0.9500000000000001, 'max_depth': 3.0, 'eval_metric': 'mlogloss', 'objective': 'multi:softprob', 'subsample': 0.9500000000000001}
Traceback (most recent call last):
  File "D:/mifs-master_2/MU/learning-from-imbalanced-classes-master/learning-from-imbalanced-classes-master/continuous/hyperopt12 - Copy.py", line 87, in <module>
    score(params)
  File "D:/mifs-master_2/MU/learning-from-imbalanced-classes-master/learning-from-imbalanced-classes-master/continuous/hyperopt12 - Copy.py", line 35, in score
    model = xgb.train(params, dtrain, num_boost_round=150, evals=watchlist, early_stopping_rounds=10)
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\training.py", line 204, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 819, in update
    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle, iteration, dtrain.handle))
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 127, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b"Invalid Parameter format for max_depth expect int but value='3.0'"

Process finished with exit code 1

```

**Comment by shahlaebrahimi** [comment]
this should be add to your code in order to resolve the issue:
    `params['max_depth'] = int(params['max_depth'])`

**Comment by jaberg** [comment]
I think pyll's scope.int can also do the case you need, so you can try `
scope.int(hp.quniform(...))` to do the cast

**Comment by proximacent** [comment]
I'm not sure if this if this is exactly what @jaberg is referring to. But you can solve it by editing pyll_utils.py file in the hyperopt package dir. Edit function "hp_quniform" to return "scope.int(" instead of "scope.float(" . At the moment, this is line 78

**Comment by erlendd** [comment]
@shahlaebrahimi The fix I suggested above should fix the problem indefinitely, as it just uses a uniform random selection from a bunch of integers (via numpy). Are you sure you aren't getting a different error?

**Comment by simonm3** [comment]
I have seen many examples using hp.choice for integer variables. However this does not seem ideal as the integers are ordered whereas hp.choice is not. In a range of 0-1000 you may find a peak at 3 but hp.choice would continue to generate random choices up to 1000.

An alternative is to just generate floats and round them. However this won't work either as it may look at 1.9 and 1.1; find they generate the same score and then assume it has found the maximum.

Do any of the optimisation algorithms work for integer distributions as these are not differentiable?

p.s. if you are using quniform and want an integer between 1 and 6 then you need hp.quniform("qu",.5,6.5, 1).

**Comment by ronnyli** [comment]
To clarify @jaberg's comment, you can import `scope` from `hyperopt.pyll.base` and use `scope.int` to cast `quniform` to `int`.

Here is an example:
```
from hyperopt import hp
from hyperopt.pyll.base import scope
from hyperopt.pyll.stochastic import sample
# Returns an integer from 0 to 10, inclusive
sample(scope.int(hp.quniform('example', 0, 10, 1)))
```

**Comment by brandonschabell** [comment]
I created a PR to fix the issue: https://github.com/hyperopt/hyperopt/pull/444

**Comment by maxpumperla** [comment]
thanks @brandonschabell

**Comment by bratitch** [comment]
Another fix would be to include a code like this in your objective function before calling xgboost
if 'max_depth' in params.keys():
        params['max_depth'] = int(params['max_depth'])

**Comment by Lean-Y** [comment]
> I had the same issue recently, but it's easily resolved by replacing hp.quniform by hp.choice('max_depth', np.arange(1, 13+1, dtyle=int).

typo:
hp.choice('max_depth', np.arange(1, 13+1, dtype=int)

and big thanks for your suggestion!

**Comment by relue** [comment]
Switching to choice is not feasible for me as it would lose the order of an integer space, which may helps optimizing when it is somehow related to a monotonic order.  

Also scope.int() did not help, still float result.

**Comment by josedallavia** [comment]
> I'm not sure if this if this is exactly what @jaberg is referring to. But you can solve it by editing pyll_utils.py file in the hyperopt package dir. Edit function "hp_quniform" to return "scope.int(" instead of "scope.float(" . At the moment, this is line 78

# Worked for me!, however it was not line 78 but I did modify the return value of the function hp_quniform in the  pyll_utils.py file in the hyperopt package dir.

**Comment by arainboldt** [comment]
@here, @maxpumperla isn't this solution rather hacky? it doesn't make sense to have to change source-code when using a library. Imagine the headaches when running in multiple virtual envs. Nightmare. What about a dtype argument to integrate explicit type casting in the distribution function itself?

**Comment by maxpumperla** [comment]
@arainboldt completely agree with your assessment. I wasn't even aware of this issue anymore, to be honest.

@marload @marctorsoc is this something you could have a look at?

**Comment by marctorsoc** [comment]
after my PR here https://github.com/hyperopt/hyperopt/pull/595/, one should be able to get integers in a given interval using randint. Could you try this @arainboldt ? Also, could you post a minimal example showing what you want to do, and the error message?

**Comment by sdhaus** [comment]
My approach to this problem in the short term is to force change the values to `int` if it doesn't change the actual value:

```
for key in models['model_best_param'].keys():
    if int(models['model_best_param'][key]) == models['model_best_param'][key]:
        models['model_best_param'][key] = int(models['model_best_param'][key])
```

I don't want to manually set the values

**Comment by wincenzo** [comment]
> 
> 
> this should be add to your code in order to resolve the issue:
> `params['max_depth'] = int(params['max_depth'])`

i solved with this

**Comment by jwels** [comment]
As this was still the first result on Google for me on this problem, I just wanted to highlight that there also is `uniformint` which returns an integer as mentioned [here](https://github.com/hyperopt/hyperopt/issues/508#issuecomment-508189840).

**Comment by CameronAHSA** [comment]
> As this was still the first result on Google for me on this problem, I just wanted to highlight that there also is `uniformint` which returns an integer as mentioned [here](https://github.com/hyperopt/hyperopt/issues/508#issuecomment-508189840).

This worked for me only where the `q` param is explicitly added to the function, ie:

```python
  search_space = {"n_estimators": hp.uniformint("n_estimators", 50, 500, q=10.0)}
```

**Comment by MenaWANG** [comment]
For anyone who stumbled on this, the more updated discussions are available here: https://github.com/hyperopt/hyperopt/issues/508

Following the linked discussions, this worked for me:

`from hyperopt import hp
from hyperopt.pyll.base import scope
import hyperopt

search_space = {"n_estimators": scope.int(hp.uniformint("n_estimators", 50, 500, q=10.0))}
print(hyperopt.pyll.stochastic.sample(search_space))`
