### ISSUE TITLE
both py2 and 3 install having error 

### ISSUE THREAD

**Issue by Heipiao** [hyperopt/hyperopt#254]
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bc/rstz2cgd2k5gkx1mplrpbjn80000gn/T/pip-build-b51drzkf/hyperopt/

**Comment by volker48** [comment]
Did you try `pip install git+https://github.com/hyperopt/hyperopt.git`

**Comment by michaelmior** [comment]
Closing since there was no follow up. Feel free to reopen with more information if you're still experiencing this.
