### ISSUE TITLE
Incompatible with Python3 ....

### ISSUE THREAD

**Issue by jiapei100** [hyperopt/hyperopt#255]

**Comment by paulperry** [comment]
On python 3.5 on install I get:

```
pip install hyperopt
Collecting hyperopt
  Downloading hyperopt-0.0.2.tar.gz (85kB)
    100% |████████████████████████████████| 92kB 1.8MB/s 
    Complete output from command python setup.py egg_info:
    DEBUG:root:distribute_setup.py not found, defaulting to system setuptools
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/m7/bjp2kv013213101q4vmqbyr00000gn/T/pip-build-nvsyn0zw/hyperopt/setup.py", line 119, in <module>
        if package_data is None: package_data = find_package_data(packages)
      File "/private/var/folders/m7/bjp2kv013213101q4vmqbyr00000gn/T/pip-build-nvsyn0zw/hyperopt/setup.py", line 102, in find_package_data
        for subdir in find_subdirectories(package):
      File "/private/var/folders/m7/bjp2kv013213101q4vmqbyr00000gn/T/pip-build-nvsyn0zw/hyperopt/setup.py", line 73, in find_subdirectories
        subdirectories = os.walk(package_to_path(package)).next()[1]
    AttributeError: 'generator' object has no attribute 'next'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/m7/bjp2kv013213101q4vmqbyr00000gn/T/pip-build-nvsyn0zw/hyperopt/

```

**Comment by gayanadarajan** [comment]
I also got those errors, but upon finding this command in another online forum:

pip install git+https://github.com/hyperopt/hyperopt.git

it worked fine on subsequent installations.

**Comment by paulperry** [comment]
Yes, that works.  Thanks!

**Comment by hadim** [comment]
Since `pip install git+https://github.com/hyperopt/hyperopt.git` seems to work fine with Python 3. Could you please release a version to pypi so people can install it with `pip install hyperopt` ?

Thank you

**Comment by leriomaggio** [comment]
Up! 
Any update on this? The pypi package seems only compatibile with Python 2, still.

Who's in charge of updating the PyPi package?

Thanks a lot!
Cheers

**Comment by jgosmann** [comment]
Ran into the same problem today. :/

**Comment by jaberg** [comment]
I've done this in the past but as is plain to see I've not been on top of things for the last 2 years! Would anyone like to take on package ownership & maintenance? cc @bjkomer @dwf ?

**Comment by maxpumperla** [comment]
@jaberg As I have a project that depends on hyperopt (thanks for this amazing lib, by the way) and people keep bugging me about python3 support, I'd offer to help port hyperopt to python3. Can't take full ownership and maintain it all, but at least help out. 

What do you think?

**Comment by peter-ch** [comment]
I also have a project that depends on hyperopt and I need Python 3 support. After 2to3 I get this error: 

"  File "/usr/local/lib/python3.4/dist-packages/hyperopt-0.0.3.dev0-py3.4.egg/hyperopt/base.py", line 625, in fmin
AttributeError: 'function' object has no attribute 'fmin'"

I think it might be related to this commit: https://github.com/hyperopt/hyperopt/commit/ddb32ecf384312ae0fd9f9e17d2d9e17e90e6096

**Comment by maxpumperla** [comment]
it's fixed on master now, will proceed to release a new version now!

**Comment by maxpumperla** [comment]
`pip3 install git+https://github.com/hyperopt/hyperopt` should work to install version `0.1` now. 👍

**Comment by shahlaebrahimi** [comment]
@maxpumperla 
Hello.
I would appreciate if you could let me know how to install hyperopt on windows. I described this issue [here](https://github.com/hyperopt/hyperopt/issues/280). 
Thanks.
Best regards,

**Comment by prafullsm** [comment]
(tensorflow) C:\Users\pmankar\AppData\Local\Continuum\Anaconda3\Scripts>conda in
stall -c jaikumarm hyperopt=0.1
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - hyperopt 0.1* -> python >=2.7,<2.8.0a0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.



I am getting following error  when trying to install hyperopt on window 7 in conda environment which has tensorflow as well.. Kindly help to resolve issue.
Regards,
