### ISSUE TITLE
Error in wiki

### ISSUE THREAD

**Issue by benbo** [hyperopt/hyperopt#256]
A line in the wiki on parallelization via mongodb (https://github.com/hyperopt/hyperopt/wiki/Parallelizing-Evaluations-During-Search-via-MongoDB) causes and error in python2.7 on my system:

```
best = fmin(math.sin, hp.uniform('x', -2, 2), trials=trials, algo=tpe.suggest)
>>> TypeError: fmin() takes at least 4 arguments (4 given)
```

It does not cause an error if I call

```
best = fmin(math.sin, hp.uniform('x', -2, 2), trials=trials, algo=tpe.suggest, max_evals=10))
```

**Comment by mixxen** [comment]
Same here. Wiki should be updated to include max_evals=10

**Comment by michaelmior** [comment]
Thanks @benbo! Fixed.
