### ISSUE TITLE
Pyll module errors

### ISSUE THREAD

**Issue by StuartFarmer** [hyperopt/hyperopt#264]
Using Python 3.5 creates errors when installing hyperopt through pip and setup.py. When using pip git+, no errors occur, but in ipython, upon using 'import hyperopt' a 'no module named pyll' error occurs.

Installing pyll fails regardless of running it with Python 2.7 or virtual environments.

**Comment by maxpumperla** [comment]
`pip3 install git+https://github.com/hyperopt/hyperopt` should now install version `0.1` from master (soon to be released). @StuartFarmer
