### ISSUE TITLE
NameError: name 'pickle' is not defined when using MongoTrials

### ISSUE THREAD

**Issue by yassineAlouini** [hyperopt/hyperopt#265]
I am trying to use the `MongoTrials`. I get a `NameError` for the `pickle` module for `fmin.py` and `mongoexp.py`. 

I think the error comes from the following import statement: 

```
try:
    import dill as cPickle
except ImportError:
    import pickle
```

I have changed the code to the following: 

```
try:
    import dill as pickle
except ImportError:
    import pickle
```

This problem was solved (for now) with this trick.

Here are some complementary information (using the watermark package): 

```
last updated: 2016-09-07 10:57:41 2016-09-07T10:57:41+01:00

CPython 3.5.1
IPython 5.1.0

hyperopt 0.0.3.dev

compiler   : GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
system     : Linux
release    : 4.4.0-36-generic
machine    : x86_64
processor  : x86_64
CPU cores  : 4
interpreter: 64bit
watermark 1.3.3
```

Does anyone else had similar issues? Is there a better way to fix it? Thanks in advance.

**Comment by jaberg** [comment]
Good catch! That looks like the right fix.

Evidently that code isn't being unit-tested.

**Comment by yassineAlouini** [comment]
Awesome!
@jaberg: Is there any next step? Should I make a PR? Thanks.

**Comment by maxpumperla** [comment]
it's fixed on master now
