### ISSUE TITLE
nosetests fail on 'from pyll.stochastic import recursive_set_rng_kwarg'

### ISSUE THREAD

**Issue by dtsmith2001** [hyperopt/hyperopt#266]
pyll doesn't have a directory `stochastic,`and none of the Pyll version 0.4.3 files have method `recursive_set_rng_kwarg`. As far as I can tell, this is only referenced in `hyperopt/base.py`, class Domain to instantiate `self.s_idxs_vals`. Using

> Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06)
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on Linux

**Comment by maxpumperla** [comment]
of course, `from hyperopt.pyll.stochastic import recursive_set_rng_kwarg` works fine. `stochastic.py` is a file in `pyll`, not a folder. Do you work on master?
