### ISSUE TITLE
Usage of lib2to3 causes problems with pickle/dill

### ISSUE THREAD

**Issue by maexlich** [hyperopt/hyperopt#268]
As the current version of hyperopt uses lib2to3 during installation, some files are changed at installation time.
This for example makes it impossible to use dill on a python 3 installation, as the import statement is not rewritten correctly:

Original fmin.py:

```
try:
    import dill as cPickle
except ImportError:
    import cPickle
```

after lib2to3:

```
try:
    import dill as cPickle
except ImportError:
    import pickle
```

This could of course be circumvented by the not very elegant statement

```
try:
    import dill as pickle
except ImportError:
    import cPickle as pickle
```

which would result in the strange but valid statement `import pickle as pickle` on python3 installations without dill.

**Comment by jaberg** [comment]
Looks like a good fix to me. Plus a comment asking for forgiveness by
readers of the py3 code.

**Comment by maxpumperla** [comment]
this is now closed, we use `import six.moves.cPickle as pickle` for now, as it allows more elegant imports throughout the project. Should `dill` prove to be much better we could still think about adding it later on.
