### ISSUE TITLE
ImportError: No module named builtins (Python 2.7)

### ISSUE THREAD

**Issue by abiteboul** [hyperopt/hyperopt#273]
Running `pip install future` fixed this error for me.
For compatibility with Python2.7, I think the package `future` should be added to the `install_requires` in `setup.py` (hopefully this is also compatible with Python3?).

Note that `nosetests` also fails without matplotlib, but I'm not sure adding matplotlib as a dependency makes much sense.

**Comment by maxpumperla** [comment]
You're right, I addressed this in the patch above. Thanks for spotting this.

**Comment by santaraproject** [comment]
thank you

**Comment by bruce25796** [comment]
YES, we should "pip install future". Besides, the Nvidia GPU-Accelerated Caffe2 did not correct this flaw. So, this is a must for python 2.7 environments.

**Comment by Chukwuebuka86** [comment]
Thanks

**Comment by iyuge2** [comment]
thanks

**Comment by yesyu** [comment]
thanks

**Comment by carpii** [comment]
I also had to `pip install argparse`  (python 2.6.x)

**Comment by zilverback** [comment]
I did it and it works. thank you.
