### ISSUE TITLE
road map for bayesian and gp optimization?

### ISSUE THREAD

**Issue by kirk86** [hyperopt/hyperopt#283]
Hi, may I ask what is the roadmap for Bayesian and GPs optimization algorithms into hyperopt? The main drawback of this software package in relations the other ones available is the lack of true bayesian and gp optimization. The main advantage of this software package IMO in comparison the other ones, is it's easy of use. It would be nice to see those new optimization algorithms added since that would definitely made the overall project even more popular.

**Comment by jaberg** [comment]
You can try using https://github.com/hyperopt/hyperopt-gpsmbo

**Comment by kirk86** [comment]
@jaberg thanks! Some usage examples would be nice. Does it follow the same philosophy as hyperopt? I mean in terms or usage.

**Comment by jaberg** [comment]
There's an optimizer in there you should be able to pass to fmin. I haven't
used it in a while, I hope it still works. At one point it worked like a
champ for low-D continuous spaces.  I recall the 6D branin (?) space was a
challenge to really find the best point it 100% of the time. I presented
some results at a NIPS BayesOpt workshop maybe 3 years ago, it was as good
or better than Spearmint (I was considering that a reference impl) on some
small sample problems iirc. It was not very effective for med-large
conditional spaces, and I didn't have a large hyperparameter space with no
conditional vars to look at that case conveniently.

**Comment by kirk86** [comment]
@jaberg Thanks for the prompt and clear reply. My intention was to use it for NN optimization and after your comment got me thinking that probably won't work as well as expected since there's quite a big number of hyperparams and also their search space can vary from sth medium to large.

**Comment by neuronalX** [comment]
@kirk86 @jaberg Wasn't Hyperopt made to optimize NN at the beginning? (or did I miss something?)

**Comment by kirk86** [comment]
@neuronalX In my case I have huge models. They require a lot of hyperparam tuning and tpe the main algorithm for the search space in hyperopt is slower that bayesian or gps. At least that's what I've come across empirically.

**Comment by neuronalX** [comment]
@kirk86 Interesting that you find this empirically, it may be useful to others!
So how "huge" are your models? How much parameters, and how much "parameter points" to you need to evaluate?

**Comment by neuronalX** [comment]
@kirk86 BTW what kind of networks are you optimizing?

**Comment by kirk86** [comment]
@neuronalX its a combination of different stuff. Number of params can vary between 5*1e7-1e8...

**Comment by neuronalX** [comment]
@kirk86 ok! I understand why it is slow! Are you trying to optimize (nearly) whole networks?

**Comment by kirk86** [comment]
Well if you consider number or filters, number of layers, number of activations, number of optimizers.. etc. it can easily explode quickly
