### ISSUE TITLE
Typo in the wiki

### ISSUE THREAD

**Issue by ghost** [hyperopt/hyperopt#292]
Hello.
Page https://github.com/hyperopt/hyperopt/wiki/FMin,
_space2 = scope.foo(hp.uniform('a', 0, 10), hp.normal('b', 0, 1) -> space2 = scope.foo(hp.uniform('a', 0, 10), hp.normal('b', 0, 1)**)**_  .

**Comment by michaelmior** [comment]
Thanks @ghost! Fixed.
