### ISSUE TITLE
fmin(): inconsistency with max_eval() and parameter space.

### ISSUE THREAD

**Issue by ben0it8** [hyperopt/hyperopt#299]
I have defined a model with the following parameters space (eg., without any optimization to be done):
space = {'max_words': 20000,
         'seq_len': 200,
         'batch_size': 64,
         'nb_epochs':  10,
         'optimizer': 'nadam',
         'activation': 'relu'
        }

now, for example running best = fmin(f_nn, space, algo=tpe.suggest, max_evals=2, trials = trials) will evaluate the model two times with the same parameter settings. I assume it should only run it once.
is it meant to work this way or not?

best,
Oliver

**Comment by gjmulder** [comment]
max_evals = 2, so at a guess it picks your same constants twice. You've defined what is likely a local minimum and since all your parameters are constants the second eval is unlikely to escape it...
