### ISSUE TITLE
Conditional Search Space in Logistic Regression Problem

### ISSUE THREAD

**Issue by switch527** [hyperopt/hyperopt#304]
I'll fully admit that I may be setting up the conditional space wrong here but for some reason, I just can't get this to function at all. I am attempting to use hyperopt to tune a logistic regression model and depending on the solver there are some other parameters that need to be explored. If you choose the liblinear solver you can choose penalties, and depending on the penalty you can also choose dual. When I try and run hyperopt on this search space though, it keeps giving me an error because its passing the entire dictionary as show below. Any ideas?

space4lr = {
        'C': hp.uniform('C', .0001, 100.0),
        'solver' : hp.choice('solver', [
            {'solver' : 'newton-cg',},
            {'solver' : 'lbfgs',},
            {'solver' : 'sag'},
            {'solver' : 'liblinear', 'penalty' : hp.choice('penalty', [
                 {'penalty' : 'l1'},
                 {'penalty' : 'l2', 'dual' : hp.choice('dual', [True, False])}]
                                                          )},
        ]),
        'fit_intercept': hp.choice('fit_intercept', ['True', 'False']),
        'class_weight': hp.choice('class_weight', ['balanced', None]),
        'max_iter': hp.choice('max_iter', [50000]),
        'random_state': hp.choice('random_state', [8675309]),
        'n_jobs': hp.choice('n_jobs', [8])
    }

ValueError: Logistic Regression supports only liblinear, newton-cg, lbfgs and sag solvers, got {'solver': 'newton-cg'}

**Comment by switch527** [comment]
``space4lr = {
        'C': hp.uniform('C', .0001, 100.0),
        'solver' : hp.choice('solver', [
            {'solver' : 'newton-cg',},
            {'solver' : 'lbfgs',},
            {'solver' : 'sag'},
            {'solver' : 'liblinear', 'penalty' : hp.choice('penalty', [
                 {'penalty' : 'l1'},
                 {'penalty' : 'l2', 'dual' : hp.choice('dual', [True, False])}]
                                                          )},
        ]),
        'fit_intercept': hp.choice('fit_intercept', ['True', 'False']),
        'class_weight': hp.choice('class_weight', ['balanced', None]),
        'max_iter': hp.choice('max_iter', [50000]),
        'random_state': hp.choice('random_state', [8675309]),
        'n_jobs': hp.choice('n_jobs', [8])
    }

**Comment by namratameena** [comment]
I faced the same problem , while using Logistic with Hyperopt. Please do post the solution , if are able to resolve the issue.

**Comment by shauryagoel0** [comment]
I was facing the same problem. I solved it using- 
```
space={'C': hp.loguniform('x_C',-10,1),
       'solver':  hp.choice('x_solver',[{'solver':'newton-cg', 'penalty': hp.choice('p_newton',['none','l2'])},
                                        {'solver':'lbfgs', 'penalty': hp.choice('p_lbfgs',['none','l2'])},
                                        {'solver': 'liblinear', 'penalty': hp.choice('p_lib',['l1','l2'])}, 
                                        {'solver': 'sag', 'penalty': hp.choice('p_sag',['l2','none'])}, 
                                        {'solver':'saga', 'penalty':'elasticnet'}]),
       'tol': hp.loguniform('x_tol',-13,-1),
       'l1_ratio': hp.uniform('x_l1',0,1)}

def objective(space):
    solver=space['solver']['solver']
    penalty=space['solver']['penalty']
    clf=LogisticRegression(penalty=penalty, C=space['C'], solver=solver, tol=space['tol'], l1_ratio=space['l1_ratio'], max_iter=500)
    clf.fit(X_train, y_train)
    acc=clf.score(X_test,y_test)
    return {'loss': -acc, 'status': STATUS_OK}
```

**Comment by ciberger** [comment]
Another example:

```python
# Conditional search spaces
langevin = [{'langevin': False},
            {'langevin': True,
            	'diffusion_temperature': hp.uniform('diffusion_temperature', 5000, 15000)}]

# Definition of search space
search_space = {
    # ...
    'langevin': hp.choice('langevin', langevin),
}

# Start objective function with
def objective_func(args):
    # extract nested conditional parameters
    if args['langevin']['langevin']:
        # Define conditional parameter if 'langevin' is True
        args['diffusion_temperature'] = args['langevin'].get('diffusion_temperature')

    # Re-write 'langevin' variable
    args['langevin'] = args['langevin']['langevin']
```

Hope it helps 👍
