### ISSUE TITLE
set maximum runtime or max_successful_evals

### ISSUE THREAD

**Issue by skjerns** [hyperopt/hyperopt#307]
It would be great to be able to set a maximum runtime for `fmin()`

I have a project where I evaluate a function where in some cases the function returns STATUS_FAIL or runs for quite a long time and returns a loss.

I would love to be able to either let the function run as long as it has collected `X` times a successful `return` or alternatively stop after some defined time limit.

Because right now I cannot know how long my function will run and can't risk it never finishing.

**Comment by mrgloom** [comment]
+1 for time limit.

**Comment by tayor** [comment]
+1

**Comment by tayor** [comment]
Please see this code to execute Hyperopt cost functions with timeout inspired by hyperopt-sklearnn: https://gist.github.com/hunse/247d91d14aaa8f32b24533767353e35d

**Comment by yangwang166** [comment]
+1 for time limt
