### ISSUE TITLE
Parallelizing as shown on wiki does not work with own function

### ISSUE THREAD

**Issue by jlherren** [hyperopt/hyperopt#312]
The wiki [gives a trivial example](https://github.com/hyperopt/hyperopt/wiki/Parallelizing-Evaluations-During-Search-via-MongoDB) about how to parallelize using mongodb.  The trivial math.sin example works fine, but immediately fails when replacing math.sin with an own function.

For example, this works (taken from wiki):
```
import math
from hyperopt import fmin, tpe, hp
from hyperopt.mongoexp import MongoTrials
trials = MongoTrials('mongo://localhost:27017/foo_db/jobs', exp_key='exp1')
best = fmin(math.sin, hp.uniform('x', -2, 2), trials=trials, algo=tpe.suggest, max_evals=10)
```
This fails:
```
import math
from hyperopt import fmin, tpe, hp
from hyperopt.mongoexp import MongoTrials
def my_func(x):
    return math.sin(x)
trials = MongoTrials('mongo://localhost:27017/foo_db/jobs', exp_key='exp1')
best = fmin(my_func, hp.uniform('x', -2, 2), trials=trials, algo=tpe.suggest, max_evals=10)
```
I get this error when running `hyperopt-mongo-worker`:
```
INFO:hyperopt.mongoexp:Error while unpickling. Try installing dill via "pip install dill" for enhanced pickling support.
INFO:hyperopt.mongoexp:job exception: Can't get attribute 'my_func' on <module '__main__' from '/home/<myuser>/virtualenv/bin/hyperopt-mongo-worker'>
```
It looks like it's looking for `my_func` in a completely wrong place. How to make this very trivial example work?

(PS: I do have dill installed, so that message seems bogus)

**Comment by DmitryBe** [comment]
similar issue;
tried to run worker with --workdir but didnt help

**Comment by DmitryBe** [comment]
probably the easiest solution would be to set PYTHONPATH

**Comment by svirg** [comment]
setting PYTHONPATH worked for me as well (yet it looks like a hack)

**Comment by JPellegrino** [comment]
Hi ! I have the same problem. Please can you bring more details on the solution, i.e. how do you modify your PYTHONPATH.

**Comment by svirg** [comment]
In Linux you can just execute ```export PYTHONPATH=<directory with your worker code>``` before running hyperopt-mongo-worker

**Comment by renan-ms** [comment]
@jlherren Did you manage to solve your problem? I am struggling with the same error but I haven't solve it yet.
