### ISSUE TITLE
Update on Bayesian Optimization?

### ISSUE THREAD

**Issue by imichaelnewman** [hyperopt/hyperopt#313]
In the docs, it says that at some point, HyperOpt will also include support for Bayesian optimization through either Gaussian processes or regression trees; any idea on when that could be implemented? 

Thanks

**Comment by amueller** [comment]
Check out:
- [scikit-optimize](https://scikit-optimize.github.io/)
- [spearmint](https://github.com/HIPS/Spearmint) 
- [GPyOpt](https://sheffieldml.github.io/GPyOpt/)
- [RoBo](http://automl.github.io/RoBO/index.html)
- [SMAC3](http://www.ml4aad.org/algorithm-configuration/smac/)

**Comment by jaberg** [comment]
You can also check out
https://github.com/hyperopt/hyperopt-gpsmbo

The algos in
https://github.com/hyperopt/hyperopt-gpsmbo/blob/master/hp_gpsmbo/suggest_algos.py
should be valid args to fmin, at least they were a few years ago.
