### ISSUE TITLE
ImportError: cannot import name models (Pythin 2.7)

### ISSUE THREAD

**Issue by Geckelberi** [hyperopt/hyperopt#317]
Running `from baselines import deepq` in Jupyter (Python2.7) (Ubuntu 16.4) gives me the following error:

```
ImportError                               Traceback (most recent call last)
<ipython-input-6-344b5db8bf7a> in <module>()
----> 1 from baselines.deepq.build_graph import build_act, build_train

/home/tur/anaconda2/lib/python2.7/site-packages/baselines/deepq/__init__.py in <module>()
----> 1 from baselines.deepq import models  # noqa
      2 from baselines.deepq.build_graph import build_act, build_train  # noqa
      3 
      4 from baselines.deepq.simple import learn, load  # noqa
      5 from baselines.deepq.replay_buffer import ReplayBuffer, PrioritizedReplayBuffer  # noqa

ImportError: cannot import name models 
```

**Comment by geweihgg** [comment]
Hi, Geckelberi,
     Have you solved this problem? I'm trapped by this problem too.
     Looking forward to your reply.
                                                                                                                                  Thanks, Wei

**Comment by michaelmior** [comment]
Closing as this has not had any recent activity. Feel free to reopen if you're still having an issue.
