### ISSUE TITLE
Hyperopt with xgboost early_stopping

### ISSUE THREAD

**Issue by eranop** [hyperopt/hyperopt#334]
When defining a space to search for xgboost params, one might define:
'n_estimators': hp.quniform('n_estimators', 10, 1000, 10)

This is wrong and can be avoided by setting n_estimators high (10,000) and set an early_stopping parameter in the xgboost model.

Whats bothering me is that I cant save that parameter I "discover" through fmin.
In fmin theres a variable fn which doesn't communicate with the current TRIAL, thus it cant save the model best iteration.. which is the n_estimators we are looking for.

build a way to change the TRIAL variable through fn, or add variables through fn.

**Comment by nd26** [comment]
Can't you retrieve that parameter through the objective function and save it from there?

**Comment by eranop** [comment]
Of course I can. 
If I return a dictionary and manually handles the parameters 
return {'loss': 1 - score, 'status': STATUS_OK, 'params': params}

and then I go look for them in trials.trials.
But its long, complicated and un-intuitive. 

When you write:
best = fmin(score, space, algo=tpe.suggest, trials=trials, max_evals=2500),
you expect  to have all the variables that matter in "best".

Why not adding a "layer" that will let you manually control what other variables will be in "best"

**Comment by srowen** [comment]
I just add `'booster': booster.attributes()` to the return values. It will have three attributes related to the best iteration. You can retrieve it later with `.best_trial['result']['booster']['best_iteration']`
