### ISSUE TITLE
Repeating tested hyperparameters

### ISSUE THREAD

**Issue by nd26** [hyperopt/hyperopt#335]
Hey,

I was wondering whether I have some error in my implementation or if this is a natural outcome of TPE.

![image](https://user-images.githubusercontent.com/7026980/32212978-39dd4946-be11-11e7-8ea0-fa45d938bff2.png)

As you can see, a specific subset of hyperparameters is being tested again and again (for KNN). Why is that? If this was expected, would a "pchoice" with a smaller probability on classifiers with fewer hyperparameters be a better solution?

**Comment by vh77** [comment]
Hi, I have a similar behavior on my side. When using hyperopt.choice (I guess this is what you're using), I notice the same set of hyperparameter values are used several times. I can't figure out why. Does the TPE algorithm assumes the function to minimize is non-deterministic and that it makes sense to try the same config from time to time?
Could you figure out something on you side?

**Comment by nd26** [comment]
Indeed, I had used hp.choice for allowing TPE determine which classifier to choose next. Nevertheless, following this error, my current methodology simply runs TPE on the different classifiers independently (hence the choice of the classifier is not a hyperparameter).

**Comment by vh77** [comment]
Ah, I'm afraid I don't have that option. I use hp.choice to pass ranges of integers. Then it's unfortunate that it tries out several times - and pretty often - the same combinations. I opened a new issue (https://github.com/hyperopt/hyperopt/issues/370). Let's see. Tx.

**Comment by ashay88** [comment]
This issue #181  might be relevant

**Comment by cdavi014** [comment]
Any update on this? Having the same issue.

**Comment by oldrichsmejkal** [comment]
any update?

**Comment by ivan-marroquin** [comment]
Hi @oldrichsmejkal ,

go to incident 370: https://github.com/hyperopt/hyperopt/issues/370 and scroll down until you see the code shared by Rubyr0id 

It will give you an idea on how to deal with repeated configurations. 

To answer the question posted in this incident. It is likely that if you have  a large number of trials compared to the parameter space size, then repeated hyperparameter setting can show up.

Hope this helps,

Ivan
