### ISSUE TITLE
Check pointing

### ISSUE THREAD

**Issue by mtanti** [hyperopt/hyperopt#344]
Is there a way to save check points of the optimization process so that I can resume the optimization from where it left off if it gets terminated?

**Comment by michaelmior** [comment]
Check out the wiki on [using MongoDB](https://github.com/hyperopt/hyperopt/wiki/Parallelizing-Evaluations-During-Search-via-MongoDB). In addition to enabling parallelization, any trials which complete will be recorded and not repeated when the optimization is run again.

**Comment by mtanti** [comment]
It would be nice to have a less demanding feature such as saving pickled files or something.

**Comment by az0** [comment]
@mtanti  See https://github.com/hyperopt/hyperopt/issues/267 . Does this help? It seems like the same issue
