### ISSUE TITLE
Latest version of networkx causes error

### ISSUE THREAD

**Issue by mtanti** [hyperopt/hyperopt#349]
There is a line of code that uses a value returned by a networkx function which assumes that the value is a list but now it has been changed to a generator so it causes an error as you try to subscript it. Here is the line of code in question:
https://github.com/jaberg/hyperopt/blob/master/hyperopt/pyll/base.py#L673

**Comment by michaelmior** [comment]
I believe this was fixed in #319. This issue is a duplicate of #318.
