### ISSUE TITLE
hyperopt on GPU with keras

### ISSUE THREAD

**Issue by buckleytoby** [hyperopt/hyperopt#351]
Hey All,

I'm running hyperopt on a keras (tensorflow backend) script to optimize hyperparameters. Normally tf will identify GPU's and run on them if they're available, and my script does so when ran separately. But with hyperopt only the CPU is used, not the GPU. Any idea what might be happening?

Regards,
Toby

**Comment by buckleytoby** [comment]
Ok, so I figured it out.

I had both tensorflow & tensorflow-gpu installed through pip, so I 
`pip uninstall tensorflow` and then had to 
`pip install tensorflow-gpu --ignore-installed` so that it reinstalled and let me use `import tensorflow` to call it
then I had to install cudnn6.0 for my cuda 8.0 since tensorflow-gpu 1.4 requires it
then I had to add /usr/local/cuda/lib64 to my LD_LIBRARY_PATH in my .bashrc file
then it worked!

**Comment by michaelmior** [comment]
Glad you solved this!

**Comment by mtlive** [comment]
I have this problem but the proposed workaround didn't work.
The code runs on GPU without problem, but when it's called from fmin it progresses really slow.
