### ISSUE TITLE
Switch to MIT license?

### ISSUE THREAD

**Issue by jaberg** [hyperopt/hyperopt#352]
@aldanor wrote in #350 :

I've noticed that some of the files claim they are MIT-licensed, e.g. hyperopt/ipy.py, while the whole project is 3-clause BSD.

Would the authors consider switching the project to a somewhat friendlier MIT license? (unless there's reasons we're not aware about that prohibit doing so)

**Comment by jaberg** [comment]
Is valid to just change an MIT-licensed file to BSD-3, but not the other way around?

**Comment by analog-cbarber** [comment]
Not sure why MIT is considered to be that much "friendlier". I doubt it matters either way.

 I always use Apache 2 for my projects.

**Comment by michaelmior** [comment]
Here's a [relevant discussion](https://softwareengineering.stackexchange.com/questions/82321/why-do-people-pick-the-mit-license-over-bsd-if-bsds-non-endorsement-clause-i) on the software engineering Stack Exchange.
