### ISSUE TITLE
Separate mongodb dependency

### ISSUE THREAD

**Issue by jaberg** [hyperopt/hyperopt#353]
@aldenor wrote (#350): 

I understand that Mongo backend is an essential part of hyperopt, however quite often it won't be needed (people just import fmin and hp and go on optimizing). It would be nice if, at the very least, the core code didn't try to import pymongo unless you tried to create a MongoTrials.

It might be nice to provide a clean separation, so that mongo-related code is not intertwined with the core codebase; also, pymongo could be made a separate dependency, enabled via [mongo] setuptools feature (which would also install the mongo backend), like so:

```
$ pip install hyperopt[mongo]
```

**Comment by ClimbsRocks** [comment]
Whoa, I didn't realize you could specify dependencies that way. Do you have any favorite examples of this? 

I'm also a big fan of packages that just work out of the box (don't require db installs or db service starts or anything else), that allow the user to opt into more advanced features when they want, and choose to take on that incremental setup work (ie, the mongo features). 

Really glad to see this project coming back to life!

**Comment by palicand** [comment]
Hello. I have created a PR that should fix this. If there anything else related to the issue is needed, I'll be happy to add it there.
