### ISSUE TITLE
Set up CI & make a new release

### ISSUE THREAD

**Issue by jaberg** [hyperopt/hyperopt#355]
@aldanor (#350) suggests a number of things, but burning issues would be:

* [ ] set up CI for key platforms
* [ ] address any failing tests

If we do this, make a release, then we can start on a lot of the other possible next steps.

**Comment by jaberg** [comment]
Made this a milestone, rather than an issue.

**Comment by jaberg** [comment]
#361 gets tests passing (skipping mongo).

**Comment by michaelmior** [comment]
I'm still seeing a failing test. I configured Travis CI on a branch in my fork. The [test output](https://travis-ci.org/michaelmior/hyperopt/builds/337560527) is available on Travis.

**Comment by michaelmior** [comment]
Also, the tests seem flaky since different tests fail each time things run. As one other observation, I tried to get the IPython tests running but I see that the latest IPython has moved the parallel stuff to a separate package. Probably worth updating to use that.

**Comment by jaberg** [comment]
Let's stomp these out - if you see a test fail keep track of it (gh issue?)
so we can fix it even if it passes most of the time.  Some tests may not
have the random seeds locked down, and yet still pass e.g. 99% of the time.
How to properly test such code is an interesting question, but in the
interest of not confusing travisCI I think pinning a good seed is
reasonable now.

**Comment by jaberg** [comment]
Oh - reading the fmin() docs reminded me of HYPEROPT_FMIN_SEED. The fmin
calls in the tests were deliberately written without seeds so that this env
variable could re-run the tests with different seeds. I'll put up a PR that
sets this in travis config.

**Comment by michaelmior** [comment]
@jaberg Do you want me to go ahead and merge as-is then and file issues for failing tests?

**Comment by jaberg** [comment]
@michaelmior sorry, but merge what? I've got a PR #363  to pin down the seed in Travis so that CI isn't flaky.

**Comment by maxpumperla** [comment]
@jaberg closing this as travis has been around for a while now and we've had a release.
