### ISSUE TITLE
hyperopt-mongo-worker is not recognized as an internal or external command operable program or batch file

### ISSUE THREAD

**Issue by thijsgelton** [hyperopt/hyperopt#365]
I can not start hyperopt-mongo-worker via the command line. I pip installed it (v 3.6) in my virtual environment and my global site-packages. I am getting a 'hyperopt-mongo-worker is not recognized as an internal or external command operable program or batch file' error when I try to run it in my CMD (with and without admin rights).

**Comment by ivan-marroquin** [comment]
I anaconda and hyperopt installed on a windows machine. the script hyperopt-mongo-worker can be found under the path <anaconda home folder>\Scripts. 

The file is written to run on a Linux like OS. Is there a version for Windows?

many thanks!

**Comment by jve2kor** [comment]
I think you can execute it as python file 
ex: python hyperopt-mongo-worker

**Comment by steve7an** [comment]
Traceback (most recent call last):
  File "hyperopt-mongo-worker", line 6, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "\lib\site-packages\hyperopt\mongoexp.py", line 1313, in main_worker
    return main_worker_helper(options, args)
  File "\lib\site-packages\hyperopt\mongoexp.py", line 1193, in main_worker_helper
    signal.signal(signal.SIGHUP, sighandler_shutdown)
AttributeError: module 'signal' has no attribute 'SIGHUP'

**Comment by ivan-marroquin** [comment]
It seems that the script was written to work under a Linux OS system. I created another issue asking if there is a plan to have a mongo worker for windows.
