### ISSUE TITLE
How to search optimizers and their params at the same time?

### ISSUE THREAD

**Issue by tonywangcn** [hyperopt/hyperopt#374]
Some code like [this](https://github.com/keras-team/keras/issues/1591#issuecomment-193763247
), but search optimizers and their params like below

'optimizer' : 
'SGD: lr=[0.01-0.08], decay=1e-7, momentum=[0.01-0.15], nesterov=True)'
,'RMSprop': ....
'Adadelta': .....
'Adam'] ....

**Comment by michaelmior** [comment]
You should be able to do this using something similar to the example below in the docs.

``
space = hp.choice('a',
    [
        ('case 1', 1 + hp.lognormal('c1', 0, 1)),
        ('case 2', hp.uniform('c2', -10, 10))
    ])
```

In your case, it might look like this

```
space = hp.choice('optimizer',
    [
        ('SGD', hp.lognormal('lr', 0.01, 0.08), …),
        ('RMSprop', …)
    ])
```

If this doesn't resolve your issue, feel free to reopen.
