### ISSUE TITLE
Understanding pyll

### ISSUE THREAD

**Issue by thiagotei** [hyperopt/hyperopt#378]
I've read about [using non-stochastic options here]( https://github.com/hyperopt/hyperopt/wiki/FMin#23-adding-non-stochastic-expressions-with-pyll) and seen the use of pyll on [sklearn here](https://github.com/hyperopt/hyperopt-sklearn/blob/b880877e7dd7f24a739c7ae6f6db52f9730d68cb/hpsklearn/estimator.py#L523).
I've just started exploring hyperopt on and I'd like more info on that.

Thanks!

**Comment by taylor-schneider** [comment]
I am interested in this as well. Digging through the documentation/codebase/issues at this point. My first question was "What does pyll stand for". I found the answer in a [post on an issue](https://github.com/hyperopt/hyperopt/issues/188#issuecomment-67743207). According to the author of hyperopt (@jaberg ): "Pyll originally stood for a python lispy language."
