### ISSUE TITLE
Strange behavior with hyperopt-mongo-workers

### ISSUE THREAD

**Issue by reidswanson** [hyperopt/hyperopt#379]
I am observing some strange behavior running hyperopt-mongo-workers (although it could easily be due to a misunderstanding of how it works). I have an objective function that has a sharp boundary. What I mean is that some combination of parameters lead to a catastrophic failure and are highly penalized (receive a high loss), however a very similar set of parameters that just avoid this failure are likely to be near optimal and receive a very small loss. My best guess for my problem and defined parameter space these catastrophic parameters are somewhere between 1/3 to 1/2 of the trials.

Using MongoTrials and the hyperopt-mongo-worker script I am running multiple instances of the script on 3 different computers. In my script I have some logging to record some finer grained details about the progress (including the loss before it is returned by the objective function).

The first strange behavior I am noticing is the distribution of failures (i.e., parameters that lead to very high loss) across the machines. I have set the number of startup jobs to 500. Within the first 500 runs on the first machine that I launched the hyperopt-mongo-scripts, I am seeing about a 35% failure rate. However, on the second machine I am only seeing about a 15-20% failure rate and on the third machine I am seeing a 0% failure rate.

The second strange thing is that the losses do not seem to be distributed randomly either. The losses on the first machine seem to be the worst on average. The losses on the second machine seem to be a bit better and the losses on the third machine are clearly the best. 

I would think that during the initial startup phase that the distribution of losses should be similar across the machines since the parameters should still be randomly initialized.

Finally, when I look at the losses logged by my code there are discrepancies between what I have logged and what hyperopt reports. Mainly, there are entries that my code has logged as complete but do not show up as being completed by hyperopt (one of which is the current best result). Looking a bit more closely, it looks like when the objective was complete it tried to report the result to the database but a ConnectionResetError (Connection reset by peer) was raised and the result is now lost in the ether. Any thoughts on how to avoid this?

**Comment by dsanalytics** [comment]
@reidswanson as far as distribution of losses/failures is concerned, have you tried using algo=rand.suggest in fmin call instead of algo=tpe.suggest? If not, give it try and do let us know.

P.S. Perhaps try one thing at the time - e.g. only single machine with algo=rand.suggest and if that works try all three?

**Comment by reidswanson** [comment]
Thanks for the suggestions. I'll try that a post back once this batch is completed (in a few days).

**Comment by dsanalytics** [comment]
Looking forward to it. By the way, did you manage to use hyperopt with newer versions of mongo (e.g. 3.4) or the old one? If with newer, I'd like to learn how you connect to it. Thanks in advance.

**Comment by dsanalytics** [comment]
@reidswanson Looking forward to it. By the way, did you manage to use hyperopt with newer versions of mongo (e.g. 3.4) or the old one? If with newer, I'd like to learn how you connect to it. Thanks in advance.

**Comment by reidswanson** [comment]
@dsanalytics I wrote a simple program that uses a test function similar to [this blog post](https://gab41.lab41.org/effectively-running-thousands-of-experiments-hyperopt-with-sacred-dfa53b50f1ec), but I generalized the Rosenbrock function to arbitrary dimensions to make the problem more difficult. It's really not much but it's [available from my bitbucket repository](https://bitbucket.org/reidswanson/distributed-hyperopt-test).

The short of it is everything seems to work as expected. TPE does seem to generate random parameters for `n_startup_jobs` whether it's run directly (using a regular `Trials`), with a `hyperopt-mongo-worker` on one machine, or with `hyperopt-mongo-workers` on multiple machines. I have no idea why I was seeing the strange behavior on my other problem, but I'll have to assume it was some bug on my end (maybe out of sync code or accidentally using different databases).

One thing I did notice however is that using the combination of `MongoTrials` and a `hyperopt-mongo-worker` is much slower than running the optimization directly with a `Trials` object. Not really a bug or related to my previous post but it was so much slower that I thought I'd mention it.

As far as MongoDB is concerned, I'm using version 3.4.10. It mostly seemed to just work, but I did have to follow the suggestion in the top rated answer in [this StackOverflow question](https://stackoverflow.com/questions/41373885/hyperopt-mongotrials-issue-with-pickle-attributeerror-module-object-has-no-a). That is I had to put the objective function in a module other than the one with `__main__` and I have to append the directory/package where the module is to the `PYTHON_PATH`.

**Comment by dsanalytics** [comment]
@reidswanson very interesting. Could be just my area or work, but I've found that random works much better - i.e. better coverage of the search space. Tpe seems to sweep around the last-best-found too much for my taste. Also, tpe seems to be quadratic time vs linear for random, and that'd be the biggest downside imho.
