### ISSUE TITLE
Waiting for jobs to finish.

### ISSUE THREAD

**Issue by ghost** [hyperopt/hyperopt#381]
Having some trouble with FMin, it just sits there after completing all of the work with "Waiting for 4 jobs to finish"

Not sure what's up!!!

**Comment by MoonGem** [comment]
Eventually my workers lock up, no clue why!!!!! 

INFO:hyperopt.mongoexp:PASS None
INFO:hyperopt.mongoexp:job finished: 5ab4a1956e95520f8c9ca0ff
.INFO:hyperopt.mongoexp:PROTOCOL mongo
INFO:hyperopt.mongoexp:USERNAME None
INFO:hyperopt.mongoexp:HOSTNAME localhost
INFO:hyperopt.mongoexp:PORT 1234
INFO:hyperopt.mongoexp:PATH /freqtrade_hyperopt/jobs
INFO:hyperopt.mongoexp:AUTH DB None
INFO:hyperopt.mongoexp:DB freqtrade_hyperopt
INFO:hyperopt.mongoexp:COLLECTION jobs
INFO:hyperopt.mongoexp:PASS None
INFO:hyperopt.mongoexp:no job found, sleeping for 0.6s
INFO:hyperopt.mongoexp:PROTOCOL mongo
INFO:hyperopt.mongoexp:USERNAME None
INFO:hyperopt.mongoexp:HOSTNAME 127.0.0.1
INFO:hyperopt.mongoexp:PORT 1234
INFO:hyperopt.mongoexp:PATH /freqtrade_hyperopt/jobs
INFO:hyperopt.mongoexp:AUTH DB None
INFO:hyperopt.mongoexp:DB freqtrade_hyperopt
INFO:hyperopt.mongoexp:COLLECTION jobs
INFO:hyperopt.mongoexp:PASS None

**Comment by kpatel28** [comment]
I'm having the same problem except it says "Waiting for 3 jobs to finish". Eventually mongoexp.py raises a ReserveTimeout exception and the worker times out.

**Comment by kpatel28** [comment]
I tried fmin's catch_eval_exceptions to True and max_queue_len to 20 (with number of trials set to 10). At the end of the work it still prints "Waiting for 2 jobs to finish", but fmin eventually times out with "Queue empty, exiting run". This works but the timeout takes up a lot of time.

**Comment by btyukodi** [comment]
I'm having the same problem. Any clue on why it's happening?
