### ISSUE TITLE
How does tpe.suggest traverse the search space?

### ISSUE THREAD

**Issue by mdiamore** [hyperopt/hyperopt#382]
Hello,

We're having trouble getting reliable deterministic results from fmin optimizer using tpe.suggest. We set the randomseed for fmin(rstate) in the following way. As we want to run 1000 trials with different initializations at each trial.

seeds = np.random.randint(1,10**6,size=1000)
rstate=np.random.RandomState(seeds)

As we adjust 10**6 to 10**5 or 10**3 we get much better results. Is this just a coincidence of picking a different set of random vectors or is fmin traversing the space in a different way? How can we adjust fmin to take more granular steps through the search space?

**Comment by vgoklani** [comment]
Hey there, we've had similar problems with hyperopt too. Unfortunately the results weren't robust, and we decided to pursue other libraries...
