### ISSUE TITLE
Parallelizing Evaluations on Windows

### ISSUE THREAD

**Issue by ivan-marroquin** [hyperopt/hyperopt#388]
Hi,

I downloaded MongoDB 3.6.3 and able to run the process as suggested in 
https://github.com/hyperopt/hyperopt/wiki/Parallelizing-Evaluations-During-Search-via-MongoDB

Then, I followed these steps:

1) did a minor change to the test script:
trials = MongoTrials('mongo://localhost:1234/mongo-data/jobs', exp_key='exp1')

2) Since the hyperopt-worker file in the installation was written as a script for Linux OS (or alike). For windows, I did the following:

- create a python file (mongo-worker.py) with this content:
import sys
import hyperopt.mongoexp
import logging
logging.basicConfig(stream=sys.stderr, level=logging.INFO)
sys.exit(hyperopt.mongoexp.main_worker())

3) open a conda terminal and cd to the path where the test script exists (as well the mongodb), and run the command:

python mongo-worker.py --mongo=localhost:1234/mongo-data/ --poll-interval=0.1

I got the following error message:
signal.signal(signal.SIGHUP, sighandler_shutdown)
AttributeError: module 'signal' has no attribute 'SIGHUP'

Based on this information, I checked pymongoexp.py file and noticed (lines 1181 to 1184):
signal.signal(signal.SIGINT, sighandler_shutdown)
signal.signal(signal.SIGHUP, sighandler_shutdown)
signal.signal(signal.SIGTERM, sighandler_shutdown)
signal.signal(signal.SIGUSR1, sighandler_wait_quit)

the SIGHUP and SIGUSR1 are not supported on Windows. In the hope of moivng ahead, decided to do the following edit:
if os.name == 'nt'
   signal.signal(signal.SIGINT, sighandler_shutdown, shutdown)
   signal.signal(signal.SIGINT, sighandler_shutdown, wait_quit)
else
   signal.signal(signal.SIGINT, sighandler_shutdown)
   signal.signal(signal.SIGHUP, sighandler_shutdown)
   signal.signal(signal.SIGTERM, sighandler_shutdown)
   signal.signal(signal.SIGUSR1, sighandler_wait_quit)

Re-run the command: python mongo-worker.py --mongo=localhost:1234/mongo-data/ --poll-interval=0.1

and this time, I get the following error message:
Traceback (most recent call last):
  File "mongo-worker.py", line 6, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "C:\Temp\Anaconda3\lib\site-packages\hyperopt-0.1-py3.6.egg\hyperopt\mong
oexp.py", line 1312, in main_worker
    return main_worker_helper(options, args)
  File "C:\Temp\Anaconda3\lib\site-packages\hyperopt-0.1-py3.6.egg\hyperopt\mong
oexp.py", line 1220, in main_worker_helper
    proc = subprocess.Popen(sub_argv)
  File "C:\Temp\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Temp\Anaconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

Now, there is another issue on how the subprocess is called on a Windows environment.

Any suggestions?

Many thanks,
Ivan

**Comment by JonnoFTW** [comment]
Please check my pull request for all details, the code changes are quite simple and should not require any changes for users. You can check out my fork if you want to use it.

**Comment by ivan-marroquin** [comment]
Hi @JonnoFTW 

Thanks for the suggestion. I followed the instructions outlined in your fork (https://github.com/JonnoFTW/hyperopt/blob/master/hyperopt/mongoexp.py) to make the necessary changes in my local installation.

Then, I followed these steps:
- download and intall mongodb version 4.05 for windows 64 bits

- Set dbpath to this folder "C:\Users\IMarroquin|Documents\MyMongo" 

- cd to that path and run command to start mongodb: "C:\Program Files\MongoDB\Server\4.0\bin\mongod.exe" --dbpath . --port 1234

- Generate a test file for mongotrials as follows:
import math
from hyperopt import fmin, tpe, hp
from hyperopt.mongoexp import MongoTrials

trials = MongoTrials('mongo://localhost:1234/ivan_db/jobs', exp_key='exp1')
best = fmin(math.sin, hp.uniform('x', -2, 2), trials=trials, algo=tpe.suggest, max_evals=10)

- create hyperopt-mongo-worker as follows:
import hyperopt.mongoexp

hyperopt.mongoexp.main()

- Save both python scripts in this folder "C:\Users\IMarroquin\test"

- open a DOS terminal and run command: python hyperopt-mongo-worker.py  --mongo=localhost:1234/foo_db --poll-interval=0.1

Unfortunately, I got this error: 

Traceback (most recent call last):
  File "hyperopt-mongo-worker.py", line 11, in <module>
    hyperopt.mongoexp.main()
  File "C:\Temp\Python\Python36\lib\site-packages\hyperopt\mongoexp.py", line 1266, in main
    sys.exit(main_worker())
  File "C:\Temp\Python\Python36\lib\site-packages\hyperopt\mongoexp.py", line 1317, in main_worker
    return main_worker_helper(options, args)
  File "C:\Temp\Python\Python36\lib\site-packages\hyperopt\mongoexp.py", line 1217, in main_worker_helper
    proc = subprocess.Popen(sub_argv)
  File "C:\Temp\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Temp\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application


Could you let me know if I missed some steps (or were incorrectly done)?

Many thanks,
Ivan

**Comment by JonnoFTW** [comment]
I made a pull request that should fix this. Please use the latest code from this repo and try again, it should generate a `hyperopt-mongo-worker` windows executable (so you only need to put `python` in front when you run it).

**Comment by mrdrebin** [comment]
Has this issue been solved in fact? I am experiencing very similar difficulties as @ivan-marroquin when trying to run the simple example from https://github.com/hyperopt/hyperopt/wiki/Parallelizing-Evaluations-During-Search-via-MongoDB on Windows 10 and mongodb 4.0.3. The hyperopt installation is version 0.1.2 which I updated recently via `conda update hyperopt`.

With a mongo database started at port 1234, I execute the script containing the call to fmin and it returns `No handlers could be found for logger "hyperopt.mongoexp"` while waiting for workers to get started. Then I open another Anaconda prompt, cd to the directory that contains the hyperopt-mongo-worker script and call the hyperopt worker script:

`python hyperopt-mongo-worker --mongo=localhost:1234/ --poll-interval=0.1`

This gives this error:
```
Traceback (most recent call last):
  File "hyperopt-mongo-worker", line 11, in <module>
    load_entry_point('hyperopt==0.1.2', 'console_scripts', 'hyperopt-mongo-worker')()
  File "C:\ProgramData\Miniconda2\lib\site-packages\hyperopt\mongoexp.py", line 1267, in main
    sys.exit(main_worker())
  File "C:\ProgramData\Miniconda2\lib\site-packages\hyperopt\mongoexp.py", line 1317, in main_worker
    return main_worker_helper(options, args)
  File "C:\ProgramData\Miniconda2\lib\site-packages\hyperopt\mongoexp.py", line 1222, in main_worker_helper
    proc = subprocess.Popen(sub_argv)
  File "C:\ProgramData\Miniconda2\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\ProgramData\Miniconda2\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

Since it has been mentioned that hyperopt-mongo-worker does not work under Windows I created a worker script mongo-worker.py with the same contents as in @ivan-marroquin's post.

Calling this worker script 

`python mongo-worker.py --mongo=localhost:1234\ --poll-interval=0.1`

produces almost the same error as previously reported by @ivan-marroquin:

```
Traceback (most recent call last):
  File "mongo-worker.py", line 5, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "C:\ProgramData\Miniconda2\lib\site-packages\hyperopt\mongoexp.py", line 1317, in main_worker
    return main_worker_helper(options, args)
  File "C:\ProgramData\Miniconda2\lib\site-packages\hyperopt\mongoexp.py", line 1222, in main_worker_helper
    proc = subprocess.Popen(sub_argv)
  File "C:\ProgramData\Miniconda2\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\ProgramData\Miniconda2\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

Am I missing something here? Any ideas how to get this running on Windows?
Kind regards

**Comment by JonnoFTW** [comment]
You don't need to run it with python in front. You should have a file called `hyperopt-mongo-worker.exe` on your machine. Please verify that it exists. Use that without `python` in front of it.

**Comment by mrdrebin** [comment]
Hi @JonnoFTW, I searched the entire harddisk but there is no `hyperopt-mongo-worker.exe` file. Should this file be created automatically during hyperopt installation via `conda install hyperopt` or is an additional step necessary?

**Comment by JonnoFTW** [comment]
I suggest you install it from GitHub source then, instead of using conda. It should be created during install. 

Do a `pip install git+https://github.com/hyperopt/hyperopt.git`

**Comment by mrdrebin** [comment]
Thank you very much @JonnoFTW ,
using pip instead of conda indeed creates the `hyperopt-mongo-worker.exe`.
