### ISSUE TITLE
Reference for citing hyperopt.

### ISSUE THREAD

**Issue by terry07** [hyperopt/hyperopt#389]
I would like a suitable rederence for citing hjyperopt (paper-journal) apart from github's link.

**Comment by bjkomer** [comment]
There is the conference paper [here](https://scholar.google.ca/scholar?cluster=4090146850565226752&hl=en&as_sdt=0,5) and the more recent journal paper [here](https://scholar.google.ca/scholar?cluster=13332741087884022951&hl=en&as_sdt=0,5)
