### ISSUE TITLE
Supported Algorithms

### ISSUE THREAD

**Issue by christianblust** [hyperopt/hyperopt#391]
Hi, 

on your github page following search algorithms are listed: 
- Random Search
- Tree of Parzen Estimators (TPE)

However, hyperopt sk-learn lists:
- Random Search
- Tree of Parzen Estimators (TPE)
- Annealing Tree
- Gaussian Process Tree

Is this true or just an old documenation on github? Is "tree of parzen estimators (TPE) a Bayesian approach?

Best,
Christian

**Comment by maxpumperla** [comment]
Random search, annealing and tpe you find in hyperopt, gpt is in https://github.com/hyperopt/hyperopt-gpsmbo. tpe is an smbo as well. cheers!
