### ISSUE TITLE
fmin verbose progress

### ISSUE THREAD

**Issue by zalky** [hyperopt/hyperopt#392]
Hi,

I'm trying to display `fmin` progress by setting the `verbose=1` keyword argument of `fmin`. Unfortunately I don't see any output, though the trials complete successfully. I also didn't see anything in the documentation about output. Should I expect to see output when setting verbose to `1`?

At minimum I would hope to be able to see which trial is currently underway (trial <n> out of `max_evals`) to get a sense of progress.

Thanks for all the hard work putting this great library together!

**Comment by erniejunior** [comment]
Hmm you could place some output at the head of your objective function.

**Comment by zalky** [comment]
@erniejunior , thanks for the response! That's a helpful suggestion for synchronous trials. Unfortunately if your objective fn is being executed in parallel on separate workers, it won't work so well.

**Comment by erniejunior** [comment]
In that case I suggest repeatedly calling `hyperopt.plotting.main_plot_history()` on your trials object. Your can either do this from within the code that calls your fmin or from a different script. For example:
```python
fmin(objective, search_space, tpe.suggest, 2000, trials)
```
becomes
```python
for _ in range(2000):
    fmin(objective, search_space, tpe.suggest, len(trials)+1, trials)
    plotting.main_plot_history(trials)
```
By the way I just opened a pull request fro a cleaned up version of the plotting utils (see #397)

**Comment by augustoicaro** [comment]
Hi @zalky, a workaround that I found is declare a global [tqdm](https://github.com/tqdm/) progress bar:
`from tqdm import tqdm
pbar = tqdm(total=max_evals, desc="Hyperopt")`
And add the update code in the end of objective function:
`pbar.update()`
And finally put the close call after fmin call:
`fmin(objective, search_space, tpe.suggest, 2000, trials)
pbar.close()`

I'm using this with hyperas and works well.

**Comment by NicolaDonelli** [comment]
The 'verbose' attribute of fmin function seems an unused attribute.
I mean, it actually is one of the possible attributes of fmin and it actually passes it to FMinIter but then FMinIter seems not to actually use it.  Am I wrong?

**Comment by marctorrellas** [comment]
I reviewed the code and it seems like this @NicolaDonelli . I wonder whether there is any work to change this? It's so annoying not being able to control the output

**Comment by KIC** [comment]
I came to the same conclusion after digging in the code. However I would like to silence optimization :-D

**Comment by marctorrellas** [comment]
as a hacky solution, you can do:

```
import logging

loggers_to_shut_up = [
    "hyperopt.tpe",
    "hyperopt.fmin",
    "hyperopt.pyll.base",
]
for logger in loggers_to_shut_up:
    logging.getLogger(logger).setLevel(logging.ERROR)
```

it worked for me

**Comment by KIC** [comment]
yes and setting `show_progressbar=False`

**Comment by marctorrellas** [comment]
I meant apart from that :) Even if you set it to False it prints a lot of stuff

**Comment by itamar-precog** [comment]
> Hi @zalky, a workaround that I found is declare a global [tqdm](https://github.com/tqdm/) progress bar:
> 
> ```
> from tqdm import tqdm
> pbar = tqdm(total=max_evals, desc="Hyperopt")
> ```
> 
> And add the update code in the end of objective function:
> 
> ```
> pbar.update()
> ```
> 
> And finally put the close call after fmin call:
> 
> ```
> fmin(objective, search_space, tpe.suggest, 2000, trials)
> pbar.close()
> ```
> 
> I'm using this with hyperas and works well.



> Hi @zalky, a workaround that I found is declare a global [tqdm](https://github.com/tqdm/) progress bar:
> 
> ```
> from tqdm import tqdm
> pbar = tqdm(total=max_evals, desc="Hyperopt")
> ```
> 
> And add the update code in the end of objective function:
> 
> ```
> pbar.update()
> ```
> 
> And finally put the close call after fmin call:
> 
> ```
> fmin(objective, search_space, tpe.suggest, 2000, trials)
> pbar.close()
> ```
> 
> I'm using this with hyperas and works well.

I think that with a notebook you should replace "import tqdm" with "from tqdm.auto import tqdm", which worked for me. Also, thanks for the workaround!

**Comment by marctorrellas** [comment]
doesn't this https://github.com/hyperopt/hyperopt/pull/581 fix the problem?
