### ISSUE TITLE
Reusing trials from other similar hyperparameter configurations

### ISSUE THREAD

**Issue by ernestum** [hyperopt/hyperopt#395]
I would like to do hyperparameter optimization on my algorithm and store the results using the MongoDBTrials Class. Later, I might add more hyperparameters or more choices in the choice nodes to the hyperparameter space. 

Now when tuning those parameters it would make sense to reuse the old trials to give some kind of good initial guess. Will this be possible? I guess changing the ranges of distributions is fine but will this work if I add more choices or entirely new parameters?

**Comment by erniejunior** [comment]
I would prefer the second option because the first one might be confined to the specific trials implementation?

**Comment by maxpumperla** [comment]
@erniejunior the solution @ptempczyk-nethone talks about has been merged in #403 already
