### ISSUE TITLE
space_eval(space, trials.trials[n]['misc']['vals']) 

### ISSUE THREAD

**Issue by luded** [hyperopt/hyperopt#405]
the above code does not work because trials.trials[n]['misc']['vals'] returns a dict of lists instead a dict of values.

how can I get the n-th trial in the same format as the 'best' trial (dict of values that can be fed to space_eval)

thanks

**Comment by ivotron** [comment]
this might work:

```
def space_eval_trial(space, trial):
    for_eval = {}
    for k, v in trial["misc"]["vals"].items():
        if len(v) == 0:
            for_eval[k] = None
        else:
            for_eval[k] = v[0]
    return space_eval(space, for_eval)
```

taken from https://github.com/hyperopt/hyperopt/issues/383

**Comment by benskov** [comment]
Had the same problem and came up with this solution. It ain't pretty but not too bad either, I suppose:

    all_settings = [space_eval(space, {x[0]: x[1][0] for x in trial['misc']['vals'].items()}) for trial in trials.trials]
&nbsp;
Also added to https://github.com/hyperopt/hyperopt/issues/383
