### ISSUE TITLE
Question on how to find the best 10 results

### ISSUE THREAD

**Issue by ivan-marroquin** [hyperopt/hyperopt#408]
Hi!

I use these commands to set up a TPE run to optimize a function:
trials= Trials()
tpe= partial(tpe.suggest,
                 n_EI_candidates= 10,
                 gamma=0.2,
                 n_startup_jobs= 10)
fmin(Training,
         trials= trials,
         space= parameter_space,
         algo= tpe,
         max_evals= 100,
         rstate= np.random.RandomState(1969))

To get the best result after 100 trials, I use this command: 
best_error= trials.best_trial['result']['loss']

My question is: how do I do to get the best 10 results out of 100 trials?

Many thanks,
Ivan

**Comment by manosfer** [comment]
best_trials = sorted(trials.results, key=lambda x: x['loss'], reverse=False)

**Comment by ivan-marroquin** [comment]
Thanks for the suggestion!
