### ISSUE TITLE
MongoTrials and parallel search

### ISSUE THREAD

**Issue by ninnghazad** [hyperopt/hyperopt#410]
Trying to get parallel search to work, i did like the wiki said, and have a few workers, a mongod and a job-creator. However there will only ever be one worker running at the same time. Starting multiple job-creators kind of gets the workers busy for one job, after they seem to get confused and it's back to one job at a time. 
what am i missing here? should i have a pool of fmins within one process? is there a parameter somewhere that i have to set to actually spawn enough jobs to satisfy all workers? or is this a bug and it should just work but doesn't?

**Comment by ninnghazad** [comment]
tried some more setups, threads, processes, but it seems multiple fmin on the same exp_key wait on each others jobs. this might however just be the fault of keras/tensorflow and my own stuff. 
has anybody had a single process to serve a bunch of workers without waiting for all of them to finish before issuing new jobs?

**Comment by richardliaw** [comment]
Maybe instead of the default HyperOpt parallelism mechanism, try using HyperOpt with [Tune](http://ray.readthedocs.io/en/latest/tune.html)? Tune uses HyperOpt to search but manages the asynchronous parallel execution for you and works with any deep learning framework.

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import ray
from ray.tune import run_experiments
from ray.tune.suggest import HyperOptSearch


def train_model(config, reporter):
    model = Model(config)  # create model with Hyperparameters
    for i in range(100):
        accuracy = model.train()
        reporter(mean_accuracy=accuracy)


if __name__ == '__main__':
    import argparse
    from hyperopt import hp

    ray.init()

    space = {
        'width': hp.uniform('width', 0, 20),
        'height': hp.uniform('height', -100, 100),
        'activation': hp.choice("activation", ["relu", "tanh"])
    }

    config = {
        "my_exp": {
            "run": "exp",
            "num_samples": 10,
            "stop": {
                "training_iteration": 100
            },
        }
    }
    # this wraps hyperopt TPE
    algo = HyperOptSearch(space, max_concurrent=32, reward_attr="neg_mean_loss")
    run_experiments(config, search_alg=algo)
```

**Comment by ninnghazad** [comment]
@richardliaw thanks for the idea. i do however use multiple heterogeneous systems for hyperopting - which makes hyperopt's mongo-worker thing awesome for me. i think i will look into tune anyway - i could manually split the searchspace and distribute that - although that's kind of uncool.

anyway - i played around with max_queue_len, but could not get it to make a difference. but maybe i messed up my hyperopt-installs. could someone double check that new version for the max_queue_len and it's influence on the matter? i still have all workers waiting for a batch of trials to finish before starting new ones.

**Comment by richardliaw** [comment]
Thanks for the feedback! Can you clarify what you mean by "multiple heterogeneous systems"? Like different Python versions?

**Comment by ninnghazad** [comment]
Well that too, i could switch all systems to python 3 though. What i meant was multiple systems with different hardware. A few gpu-based and a few cpu-based, multiple workers running on each. Each with it's own conda-based environment and native compiled tensorflow/keras/hyperopt - those use identical versions, but the hardware may differ in supported instructions and the like.
One plays the job-server and the others crunch trials. Which works well, except for that little flaw mentioned above. It is not much of a problem, as the whole thing works, it's just not as efficient as i would like it to be. Depending on what i do, trials may take a while, and nearing completion of a batch of trials, most of the workers will be idle until the batch is finished.

**Comment by richardliaw** [comment]
I see - from what I understand about your setup, Tune supports that situation seamlessly while maintaining full worker utilization (no idle workers). 

You can have a cluster of machines where each machine has different amounts resources, and Tune will place trials that need GPUs on machines with GPUs and trials that need CPUs on machines that have available cores. There will also be a job server (driver) that runs the hyperopt and does task placement. Each machine can also have different versions of TF, as the TF specifics/compilation manner doesn't affect how Tune operates. 

You can find the command for [starting a cluster here](https://ray.readthedocs.io/en/latest/using-ray-on-a-cluster.html); it's just a single command line instruction for each machine. Let me know if you decide to try it out/have any questions!

**Comment by ninnghazad** [comment]
Just to wrap this up, by now i am using ray's tune with hyperopt instead of hyperopt's own mongotrials. Once set up, it works well aside from some minor stuff. So i am going to close this, as the issue is resolved, even if not purely based on hyperopt.
