### ISSUE TITLE
 the best hyper-parameter of random forest returns out "n_estimator"= 0, what does it mean?

### ISSUE THREAD

**Issue by exampen** [hyperopt/hyperopt#423]
Hello, 
   When I use hyperopt to  tun the hyper-parameters of random forest algorithm, it turned out that the best parameters are like this:
{'max_depth': [18], 'max_features': [0.7384644259246458], 'min_samples_leaf': [0.0026607801250987037], 'min_samples_split': [0.2077313599175486], 'n_estimators': [0]}
  What does it mean by 'n_estimators': [0]? If some one can help me, I will appreciate, thanks!!!

**Comment by bjkomer** [comment]
I'm guessing your `n_estimators` parameter was a list of possible options (e.g. specified by `hp.choice`) and the 0 means the first element of that list was chosen as the best hyperparameter.
Looking through the [sklearn code](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/ensemble/base.py#L108), it should be throwing an error if a 0 is given.

The only other explanation I can think of is if you are using a different implementation than sklearn, your algorithm could be doing something special when a 0 is given (e.g. adaptively changing based on performance).

**Comment by ejlb** [comment]
Sorry to raise this from the dead. But is there any easy way to map hp.choice indices to the hyper-parameter value? 

At the moment I'm doing it myself but it seems strange that the value is returned some spaces (hp.uniform) but not for others (hp.choice)

thanks
