### ISSUE TITLE
Is there any function that reverts space_eval()?

### ISSUE THREAD

**Issue by barbaradarques** [hyperopt/hyperopt#428]
I'm manually injecting results in my project but when it comes to categorical variables I have to map them back to the indexing used by hyperopt. I could just save the mapping when creating the space, but this would become more tricky once I'm dealing with conditional variables who may have the same name as variables in another conditional branch. Is there any function already implemented that does this reverse mapping using the space nodes?

**Comment by Demyxter** [comment]
Sorry for not actually providing an answer, but from my understanding, you're manually adding known evaluated points? How are you doing that? Its exactly what i'm looking for right now.

**Comment by tangoed2whiskey** [comment]
@barbaradarques @Demyxter I'm also interested in manually injecting known points, have you got any hints on how to do this?
