### ISSUE TITLE
MongoTrials not working : name 'variable' is not defined 

### ISSUE THREAD

**Issue by emghufran** [hyperopt/hyperopt#429]
I have tried several examples, issues on git and am still not able to make MongoTrials work. This is something that makes the usability of hyperopt quite low. 

I have the following example of code, adapted and simplified version of [this kaggle post](https://www.kaggle.com/yassinealouini/hyperopt-the-xgboost-model/code).

I am able to run this with the Trials but not with MongoTrials. I get the following exception: 

INFO:hyperopt.mongoexp:job exception: name 'train_features' is not defined
Traceback (most recent call last):
  File "/home/mghufran/anaconda3/envs/py36/bin/hyperopt-mongo-worker", line 6, in <module>
    sys.exit(hyperopt.mongoexp.main_worker())
  File "/home/mghufran/anaconda3/envs/py36/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1313, in main_worker
    return main_worker_helper(options, args)
  File "/home/mghufran/anaconda3/envs/py36/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1260, in main_worker_helper
    mworker.run_one(reserve_timeout=float(options.reserve_timeout))
  File "/home/mghufran/anaconda3/envs/py36/lib/python3.6/site-packages/hyperopt/mongoexp.py", line 1085, in run_one
    result = worker_fn(spec, ctrl)
  File "/home/mghufran/anaconda3/envs/py36/lib/python3.6/site-packages/hyperopt/base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)
  File "hp_svm.py", line 42, in score
NameError: name 'train_features' is not defined
INFO:hyperopt.mongoexp:exiting with N=9223372036854775803 after 4 consecutive exceptions

I don't understand why the variables won't be visible in this scope (I've tried moving them around). 
I also tried making them global, but didn't help. 

The code i use is below:

```python
import pandas as pd
import numpy as np
from sklearn.cross_validation import train_test_split
from sklearn.metrics import f1_score
from sklearn import datasets
from sklearn.preprocessing import normalize, scale
from sklearn.svm import SVC

from hyperopt import STATUS_OK, Trials, fmin, hp, tpe
from hyperopt.mongoexp import MongoTrials

SEED = 1314343
VALID_SIZE = 0.25
TARGET = 'target'

iris = datasets.load_iris()
X = iris.data
y = iris.target 

df = pd.DataFrame(X, columns=['a', 'b', 'c', 'd'])
FEATURES = df.columns
df['target'] = y

train, valid = train_test_split(df, test_size=VALID_SIZE,
                                random_state=SEED)
train_features = train[FEATURES]
valid_features = valid[FEATURES]
y_train = train[TARGET]
y_valid = valid[TARGET]

print('The training set is of length: ', len(train.index))
print('The validation set is of length: ', len(valid.index))

def score(params):
    print("Training with params: ")
    print(params)
    train_features_ = train_features[:]
    valid_features_ = valid_features[:]

    if 'normalize' in params:
        if params['normalize'] == 1:
            train_features_ = normalize(train_features_)
            valid_features_ = normalize(valid_features_)
        del params['normalize']

    if 'scale' in params:
        if params['scale'] == 1:
            train_features_ = scale(train_features_)
            valid_features_ = scale(valid_features_)
        del params['scale']

    clf = SVC(**params)
    clf.fit(train_features_, y_train)
    predictions = clf.predict(valid_features_)
    score = f1_score(y_valid, predictions, average='weighted')

    print("\tScore {0}\n\n".format(score))
    loss = 1 - score
    return {'loss': loss, 'status': STATUS_OK}

def optimize(
             trials, 
             random_state=SEED):
    space = {
        'C': hp.uniform('C', 0, 20),
        'kernel': hp.choice('kernel', ['linear', 'sigmoid', 'poly', 'rbf']),
        'gamma': hp.uniform('gamma', 0, 20),
        'scale': hp.choice('scale', [0, 1]),
        'normalize': hp.choice('normalize', [0, 1])
    }
    best = fmin(score, space, algo=tpe.suggest, 
                trials=trials, 
                max_evals=250)
    return best

trials = MongoTrials('mongo://localhost:1234/iris_test2/jobs')
best_hyperparams = optimize(trials)
print("The best hyperparameters are: ", "\n")
print(best_hyperparams)

````

**Comment by ninnghazad** [comment]
the problem is not a bug within mongotrials. it's a matter of visibility - you load your train_features outside of score(). hyperopt-mongo-worker does not know that and does not have that data - only the score() function. try loading your data inside the function you want to optimize.
remember - the worker might even run on a different machine and only has a depickled version of the target function. any globals will fail.

**Comment by michaelmior** [comment]
It seems like a solution to this issue has been presented. If you're still having a problem, please feel free to reopen.
