### ISSUE TITLE
Help  I use hyperopt and lgb  there were some problems

### ISSUE THREAD

**Issue by xuanzebi** [hyperopt/hyperopt#432]
def objective(params, n_folds=N_folds):
    cv_results = lgb.cv(params, train_set, nfold=n_folds, num_boost_round=10000, early_stopping_rounds=100,
                        verbose_eval=True, seed=2018, metrics='auc')
    best_score = max(cv_results['auc-mean'])

    loss = 1 - best_score

    return {'loss': loss, 'params': params, 'status': STATUS_OK}

space = { # 'class_weight': hp.choice('class_weight', [None, 'balanced']),
         #  'boosting_type': hp.choice('boosting_type', ['gbdt', 'dart', 'goss']),
         # [{'boosting_type': 'gbdt', 'subsample': hp.uniform('gbdt_subsample', 0.5, 1)},
         #  {'boosting_type': 'dart', 'subsample': hp.uniform('dart_subsample', 0.5, 1)},
         #  {'boosting_type': 'goss'}]

         'max_depth': hp.choice('max_depth', range(1, 20)),
         'num_leaves': hp.choice('num_leaves', range(30, 150)),
         # 'num_leaves': int(hp.quniform('num_leaves', 30, 150, 1)),
         'learning_rate': hp.quniform('learning_rate', 0.01, 0.1, 0.01),
         # 'learning_rate': hp.lognormal('learning_rate', np.log(0.01), np.log(0.2)),
         'subsample_for_bin': hp.quniform('subsample_for_bin', 20000, 30000, 20000),
         'min_child_samples': hp.quniform('min_child_samples', 20, 500, 5),
         'reg_alpha': hp.uniform('reg_alpha', 0.0, 1.0),
         'colsample_bytree': hp.uniform('colsample_bytree', 0.6, 1.0),

         }

best = fmin(fn=objective, space=space, algo=tpe.suggest, max_evals=MAX_EVALS, trials=bayes_trials)

lightgbm.basic.LightGBMError: Parameter min_data_in_leaf should be of type int, got "195.0"

**Comment by bjkomer** [comment]
Sounds like you just need to cast that parameter into an int rather than use a float

**Comment by xuanzebi** [comment]
But i did not use this parameter (min_data_in_leaf) in my space. and if this parameter solved , it will appears other parameter should be of type int
