### ISSUE TITLE
Printing trial number

### ISSUE THREAD

**Issue by hakansakarya** [hyperopt/hyperopt#433]
Is there any way to print which trial number is currently running? For example before the trial begins it would print something like Trial: 1

**Comment by cynseok** [comment]
len(trial) returns the number of trials stored in the trial object

**Comment by bjkomer** [comment]
There are a couple ways to do this. One would be to add a print at the beginning of your objective function (could use a global variable for that), or wrap it in another function that does the print. Another way is to do your evaluations in a loop and print there. For example:
```
trials = Trials()
for i in range(1, max_evals + 1):
    print("Trial: {0}".format(i))
    best = fmin(objective, space, algo, trials=trials, max_evals=i)
print(best)
```

**Comment by hakansakarya** [comment]
Thanks for the answers, I defined a print function using a global variable and put that in the beginning of the objective function and it worked!
