### ISSUE TITLE
scope.int does not effect fmin() return types

### ISSUE THREAD

**Issue by rgmyr** [hyperopt/hyperopt#438]
As per #253, I'm using `scope.int` to sample from ordered integer ranges:

```python
SEARCH_SPACE = {
    'max_depth' : scope.int(hp.quniform('max_depth', 3, 10, 1)),
    'learning_rate' : hp.uniform('learning_rate', 0.01, 0.2),
    'n_estimators' : scope.int(hp.quniform('n_estimators', 10, 1000, 1)),
    'gamma' : hp.uniform('gamma', 0, 0.5),
    'subsample' : hp.uniform('subsample', 0.3, 1),
    'colsample_bytree' : hp.uniform('colsample_bytree', 0.3, 1.0),
    'reg_lambda' : hp.uniform('reg_lambda', 0.1, 10)
}
```

This works for building and training models in optimization, e.g.:

```python
best_params = hyperopt.fmin(..., space=SEARCH_SPACE, ...)
```

But now if I try to use these parameters to instantiate a new model, the `int`-scoped variables have been returned as `float`, and must be explicitly casted to `int`:

```python
>>> best_params
{'colsample_bytree': 0.4933562654213974,
 'gamma': 0.4152873392462757,
 'learning_rate': 0.026329714594146604,
 'max_depth': 5.0,
 'n_estimators': 209.0,
 'reg_lambda': 7.684806554444843,
 'subsample': 0.5908104152037739}
```

This is workable, but less than ideal when I have a large variety of models and search spaces and would rather not have to manually do something like the following for every possible model type:

```python
params = {
    **default_params, 
    **best_params,
    **{'max_depth': int(best_params['max_depth']), 
       'n_estimators': int(best_params['n_estimators'])}
}
```

**Comment by brandonschabell** [comment]
I created a PR to address the issue upstream.
https://github.com/hyperopt/hyperopt/pull/444

**Comment by rgmyr** [comment]
Thanks @brandonschabell!
