### ISSUE TITLE
Could be possible to generate several sets of hyperparameter configurations in a trial?

### ISSUE THREAD

**Issue by ivan-marroquin** [hyperopt/hyperopt#439]
Hi,

Let's assume that the TPE algorithm is used for selecting the next configuration of hyperparameters. The algorithm will select a configuration at each trial, which is fine.

What I would like to achieve is the following:
- TPE provides 5 sets of hyperparameter configurations 
- on each trial, 5 (or any number of) classifiers are tested with its respective hyperparameter configuration
- store all produced errors 
- TPE provided a new batch of 5 sets of hyperparameter configurations. Repeat the above steps until a maximum number of trial is reached

Can this be possible?

Many thanks,
Ivan

**Comment by ninnghazad** [comment]
i may be wrong, but i think this is basically how it already works. check the trials object - or mongotrials db - and you find all trials with results. you can add additional info about failed trials should you need to.

**Comment by ivan-marroquin** [comment]
Hi @ninnghazad ,

Thanks for the suggestion. I work on windows and because some issues on how mongotrials were configured to run on *nix boxes, I haven't been able to test mongotrials.

What I would like in the long run is to do the following: work in a distributed environment in which the parameter server is running hyperopt. With hyperopt, 5 (or any number) of hyperparameter configurations are simultaneously generated. Each of these configurations are sent to a specific worker. The workers send back their results to parameter server which stores all errors and then, hyperopt generates a new batch of hyperparameter configurations. The loop continues for a fixed  number of iterations. At the end, the best hyperparameter configuration is selected.

Ivan

**Comment by ninnghazad** [comment]
well, i use linux exclusively, so i don't know about problems on windows. but if you could provide concrete errors you encounter with mongotrials i would try to be of assistance. another way would be to use ray/tune/hyperopt combo. which is very nice, but not exactly easy to set up. theres a hyperopt example on the tune site.
i would however advice to try give mongotrials another go first. maybe it's a small problem we can solve.
both would provide what you asked for.

**Comment by ivan-marroquin** [comment]
Hi @ninnghazad 

Many thanks for the offer ! I just got notified by Jonathan (on ticket 
Parallelizing Evaluations on Windows #388 ) that he was able to find a way to run mongotrials on a windows installation. Let me try Jonathan's solution, and I will let you know.

Once again, many thanks!

Ivan

**Comment by ivan-marroquin** [comment]
Hi @ninnghazad 

I just tried the solution proposed by @JonnoFTW  and hit the wall. I am hoping that @JonnoFTW  will reply as soon as possible. Once I pass the issue of running mongodb in windows with hypertop, I will contact you to test your suggestions.

Kind regards,
Ivan
