### ISSUE TITLE
sha256 mismatch reported when installing hyperopt via conda

### ISSUE THREAD

**Issue by bsesar** [hyperopt/hyperopt#442]
Dear all,

While installing hyperopt 0.1.1 using conda

conda install -c jaikumarm hyperopt

I got the following error message:

SafetyError: The package for hyperopt located at C:\Users\Default\Anaconda3\pkgs\hyperopt-0.1.1-py36h256ac0b_0
appears to be corrupted. The path 'Scripts/hyperopt-mongo-worker-script.py'
has a sha256 mismatch.
reported sha256: 79631a2b331d0768d7947fa169c7a3dcdc279d2865ffae3b69b8607a4183ac20
actual sha256: 93f70ab48de588c3747234da273b68b15371ea8f1e989aa67134f399c920114e

SafetyError: The package for hyperopt located at C:\Users\Default\Anaconda3\pkgs\hyperopt-0.1.1-py36h256ac0b_0
appears to be corrupted. The path 'Scripts/nosetests-3-script.py'
has a sha256 mismatch.
reported sha256: 93374516f78cd135e3b2e2db9d3ad545fe1f3c182f63b49582e8ed78fe886276
actual sha256: e8fd65905cf9fb53107c3d78dec21c3dad0acb85d63f67e780e5d8eb0733001f

Is this error message harmless? Perhaps @jaikumarm could comment?

Cheers,

Brani

**Comment by jaikumarm** [comment]
Brani, I use this package as part of my build on a daily basis, am fairly sure there is no packaging issues with that binary. On a quick search in github turns up https://github.com/conda/conda/issues/6689 or https://github.com/conda/conda/issues/6859 which seem more likely.

**Comment by bsesar** [comment]
Thanks, @jaikumarm :-) I read the issues you posted before posting my message, but I just wanted to be on the safe side.

**Comment by PhilipMay** [comment]
Hi @bsesar , maybe you should use the https://conda-forge.org/ Hyperopt package.
I am the maintainer of that package and it is not broken for sure... :-)
