### ISSUE TITLE
MongoDB query to find best loss for a specific exp_key

### ISSUE THREAD

**Issue by gjmulder** [hyperopt/hyperopt#453]
I needed to kill my fmin job using the MongoDB distributed config, so I no longer know what was the best set of hyperparams hyperopt found. 

Does someone have a sample MongoDB query to pull out the best loss and hyperparams for a specific exp_key?

**Comment by gjmulder** [comment]
I think I have it, but I still need to look in the index for the specific hyperparm values:

db.jobs.find({"exp_key" : "XXXXXXX", "result.status" : "ok"}).sort( { "result.loss": 1} ).pretty()

**Comment by ninnghazad** [comment]
you can add custom ids to your trials. when you return from your function-to-be-fmin-ed.
`return {"loss":loss,"id":id}`

**Comment by JonnoFTW** [comment]
In your best result, you can find the selected hyperparameters for a trial under the `misc` key.
