### ISSUE TITLE
Add a Progressbar with tqdm?

### ISSUE THREAD

**Issue by PhilipMay** [hyperopt/hyperopt#454]
Hi,
what do you think about adding a progressbar to hyperopt?
It would show the progress to max_evals if it is given.
Maybe it is turned off by default and can be turned on by a parameter.
I would contribute it.

I think it could be added here:
https://github.com/hyperopt/hyperopt/blob/master/hyperopt/fmin.py#L238

I would use this implementation:
https://github.com/tqdm/tqdm

What do you think?

**Comment by Ingvar-Y** [comment]
I'm not a contributor - just a user - but I would love tqdm progress bar. Hyperopt optimization takes a lot of time for my models so progress bar + finish time estimate would be a nice QoL addition.

**Comment by PhilipMay** [comment]
So do you want to have an on/off switch for the progress bar?
And do you want to have it on or off by default?

**Comment by PhilipMay** [comment]
> I'm not a contributor - just a user - but I would love tqdm progress bar. Hyperopt optimization takes a lot of time for my models so progress bar + finish time estimate would be a nice QoL addition.

I added the progressbar. See #454
It can not be turned off and is on by default. But I can add this if wanted.
The progressbar also shows the best (lowest loss).
Would be happy for feedback.

Philip

**Comment by ninnghazad** [comment]
this would be great. but not sure about having it on by default - might mess up some stuff downstream.

**Comment by maxpumperla** [comment]
@ninnghazad PR is merged, prog bar is off by default now.

**Comment by PhilipMay** [comment]
@maxpumperla I do not see that the progbar is off by default now. Did you change anything or am I just blind?

See here: https://github.com/hyperopt/hyperopt/blob/master/hyperopt/fmin.py#L274

**Comment by maxpumperla** [comment]
@PhilipMay sorry, lost track of our discussion. it's on by default, but can be turned off at any point. the way you implemented it, that should be fine.

**Comment by PhilipMay** [comment]
Closing this since it is done IMO.
