### ISSUE TITLE
Adding persistence for trials object?

### ISSUE THREAD

**Issue by PhilipMay** [hyperopt/hyperopt#457]
Hi,
what do you think about adding persistence for the trials object to hyperopt?

I have the following in mind:
You can pass a `persist_trials_name` to fmin that is used to pickle the trials object when fmin is done.
Mabe by joblib:
https://joblib.readthedocs.io/en/latest/generated/joblib.dump.html

Then when you want to restart hyperopt you can pass the `persist_trials_name` again and an `additional_max_evals` that will load the already evaluated trials and do this many additional evaluations.

What do you think? Is that useful or let the user implement it outside of hyperopt and fmin?

I would contribute a PR if wanted...

**Comment by ninnghazad** [comment]
hm, i generally pickle my trials, be it as a file or in some db. 
however loading and saving trials from/to a file is just 3 lines extra, or 0 lines extra when using MongoTrials.
so in my case, i use it, but might actually prefer doing manually - as to have full control when the data is written in case of a file. might loop fmin, but not save trials every iteration for example.
however, it might make it easier for other users to persist trials.

**Comment by maxpumperla** [comment]
@PhilipMay I think this is a very good idea. experienced users might know how to do this, but it's always better to make functionality explicit.

**Comment by maxpumperla** [comment]
@PhilipMay I meant yours. @ninnghazad might know how to do this, but a first-time user doesn't.

**Comment by ninnghazad** [comment]
i agree and did not mean to discourage. this wouldn't stop anybody from implementing something different, but would give new users easy access to an important feature.

**Comment by jeammimi** [comment]
I think it could be really helpful to put an example code on how to restart for the case without using mongodb.
The mongodb case is describe in the example, but not the other case.
For me it would be really helpful to know how to do it.

**Comment by PhilipMay** [comment]
@jeammimi Good point - thanks for this input.

**Comment by PhilipMay** [comment]
Here is a nice tool for Trials persistence and restart of hyperopt: https://github.com/PhilipMay/mltb#module-hyperopt
For me it works very good.
