### ISSUE TITLE
Following incident: Parallelizing Evaluations on Windows #388

### ISSUE THREAD

**Issue by ivan-marroquin** [hyperopt/hyperopt#460]
Hi @JonnoFTW 

Thanks for the suggestion. I followed the instructions outlined in your fork (https://github.com/JonnoFTW/hyperopt/blob/master/hyperopt/mongoexp.py) to make the necessary changes in my local installation.

Then, I followed these steps:
- download and intall mongodb version 4.05 for windows 64 bits

- Set dbpath to this folder "C:\Users\IMarroquin|Documents\MyMongo" 

- cd to that path and run command to start mongodb: "C:\Program Files\MongoDB\Server\4.0\bin\mongod.exe" --dbpath . --port 1234

- Generate a test file for mongotrials as follows:
import math
from hyperopt import fmin, tpe, hp
from hyperopt.mongoexp import MongoTrials

trials = MongoTrials('mongo://localhost:1234/ivan_db/jobs', exp_key='exp1')
best = fmin(math.sin, hp.uniform('x', -2, 2), trials=trials, algo=tpe.suggest, max_evals=10)

- create hyperopt-mongo-worker as follows:
import hyperopt.mongoexp

hyperopt.mongoexp.main()

- Save both python scripts in this folder "C:\Users\IMarroquin\test"

- open a DOS terminal and run command: python hyperopt-mongo-worker.py  --mongo=localhost:1234/foo_db --poll-interval=0.1

Unfortunately, I got this error: 

Traceback (most recent call last):
  File "hyperopt-mongo-worker.py", line 11, in <module>
    hyperopt.mongoexp.main()
  File "C:\Temp\Python\Python36\lib\site-packages\hyperopt\mongoexp.py", line 1266, in main
    sys.exit(main_worker())
  File "C:\Temp\Python\Python36\lib\site-packages\hyperopt\mongoexp.py", line 1317, in main_worker
    return main_worker_helper(options, args)
  File "C:\Temp\Python\Python36\lib\site-packages\hyperopt\mongoexp.py", line 1217, in main_worker_helper
    proc = subprocess.Popen(sub_argv)
  File "C:\Temp\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Temp\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

Could you let me know if I missed some steps (or were incorrectly done)?

Many thanks,
Ivan

**Comment by JonnoFTW** [comment]
If you examine the code carefully (line 1217 of `mongoexp.py`), it will try  start a subprocess using the first string in the argument list. In your case this is your custom `hyperopt-mongo-worker.py` file.

I highly recommend using the `hyperopt-mongo-worker` generated by the setup script and not importing your own. As long as the generated file is in your `PATH` then you should be able to run:

```
hyperopt-mongo-worker --mongo=localhost:1234/foo_db ...
```

As usual

**Comment by maxpumperla** [comment]
@JonnoFTW would your instructions mentioned by @ivan-marroquin be helpful for others here as well?

**Comment by ivan-marroquin** [comment]
Hi @JonnoFTW ,

Many thanks for your prompt answer. I would like to ask you a question regarding this command:

hyperopt-mongo-worker --mongo="mongo://localhost:27017/jobs" --exp-key="exp1"

where the "jobs" folder is created in Windows? Is there a way that I can set up the path where to store the mongo database?

Kind regards,
Ivan

**Comment by JonnoFTW** [comment]
The url:

`mongo://localhost:27017/jobs`

Refers to the instance of mongodb running on localhost that you can access via port 27017. `/jobs` refers to the `jobs` database of the currently running mongodb instance. When creating the trials object with ` MongoTrials('mongo://localhost:27017/jobs/jobs')`, it puts the jobs in the `jobs` collection of the `jobs` database (remember that each mongodb instance can have many databases, where each database has many collections containing many documents). Check out robo3t if you want a neat GUI to poke around and see what's in the collections.

When you make start a mongodb instance and pass the `--dbPath` parameter, this indicates which folder on disk will store your  database files. The name of this folder has nothing to do with the documents or collections mentioned earlier. For convenience sake, you can start mongod.exe with a config file like this:

`mongo.conf`:
```yaml
systemLog:
    destination: file
    path: F:\mongodata\log\mongod.log
storage:
    dbPath: F:\mongodata\data
```

You then start `mongod.exe --config mongo.conf`. Check here for more options:  https://docs.mongodb.com/manual/reference/configuration-options/
Refer to the mongodb docs for more information: https://docs.mongodb.com/manual/core/databases-and-collections

**Comment by ivan-marroquin** [comment]
Thanks so much @JonnoFTW

**Comment by yuluoliyuan** [comment]
how to run hyperopt-mongo-worker --mongo="mongo://localhost:27017/jobs" --exp-key="exp1"

**Comment by JonnoFTW** [comment]
@yuluoliyuan you do this from command prompt.

**Comment by yuluoliyuan** [comment]
is hyperopt-mongo-worker a hyperopt-mongo-worker.py file?  Do I need to enter the directory where this file is located?

**Comment by yuluoliyuan** [comment]
You say “I highly recommend using the hyperopt-mongo-worker generated by the setup script and not importing your own.”where is he hyperopt-mongo-worker generated by the setup script？

**Comment by JonnoFTW** [comment]
After installing the latest version of hyperopt, you should end up with a file called `hyperopt-mongo-worker.exe` in the  scripts folder of your python install. If that folder is in your `PATH` variable (google it if you don't know how to do this), then you should be able to run as described above.

On windows for recent versions of python3, this will be in `%localappdata%\programs\python\python36\scripts`. Press windows+r and paste in `%localappdata%\programs\python\python36\scripts` and it will show you the contents of the folder. The version of python in the path may change depending on what you have installed.

**Comment by yuluoliyuan** [comment]
Thank you for your help！I have  solved the problem.@JonnoFTW
