### ISSUE TITLE
ImportError: : cannot import name 'generate_trials_to_calculate'

### ISSUE THREAD

**Issue by chenzhi2223** [hyperopt/hyperopt#461]
Hi, I want to play with Hyperopt library and generate trials myself with the function 
generate_trials_to_calculate. However, I could not import it with the following 
script:

from hyperopt.fmin import generate_trials_to_calculate

as I guess this function is from the fmin file. But it doesn't work and throw me the error above as in the title of the issue.

In addition, I am also a bit confused with the command "from hyperopt import fmin", kind of it maps to the fmin function in the fmin file. However, I would assume this fmin maps to the fmin file but not the fmin function in the fmin file.

It would be greatly appreciated if someone can help resolve this issue or help me better understand the structure of this amazing project and import problems. Thanks a lot!

**Comment by bjkomer** [comment]
My guess is you have an older version of `hyperopt` that does contain that function. It was added 7 months ago so it would be in version `0.1.1` but not in `0.1.0`. You could try upgrading to the latest from PyPI, if that doesn't work then install the version on git.

For your `fmin` question, I believe [this](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/__init__.py#L21) line is what makes it get the function.

**Comment by chenzhi2223** [comment]
@bjkomer Thanks Man. I got it. Appreciate your help!
