### ISSUE TITLE
`tpe.suggest` ignores `linear_forgetting` parameter

### ISSUE THREAD

**Issue by batzner** [hyperopt/hyperopt#465]
Why is the `linear_forgetting` parameter never used in the [`tpe.suggest` function](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/tpe.py#L822)? How can I change the linear forgetting parameter used by TPE?

**Comment by 1kastner** [comment]
I guess you want to use `adaptive_parzen_normal_orig` instead of `adaptive_parzen_normal` then? Like you want to decide whether to switch it on or off?

**Comment by batzner** [comment]
@1kastner thank you for your help. I wanted to change the number. It seems like the only way to do this right now is to fork the repo and change `DEFAULT_LF` in the fork. I was curious about why the `tpe.suggest` function does not use the `linear_forgetting` parameter. It might make sense to remove it to avoid confusion.

**Comment by MiladShahidi** [comment]
Could you tell me where I can find the documentation for `tpe.suggest`? I would like to know what linear forgetting exactly does. I'm trying to do optimization in a setting where I need to give lower weight to older trials (or discard them altogether), and I think this might exactly be that. But I cannot find the documentation.

**Comment by 1kastner** [comment]
You can always check the code - and maybe they explained it in the corresponding scientific publication?

**Comment by batzner** [comment]
@MiladShahidi you can take a look at this paper: http://proceedings.mlr.press/v28/bergstra13.pdf In section "5 - Results", they explain linear forgetting:

> Relative to Bergstra et al. (2011) we made two minor modifications to the search algorithm. The first modification was to downweight trials as they age so that old results do not count for as much as more recent ones. We gave full weight to the most recent 25 trials and applied a linear ramp from 0 to 1.0 to older trials. This is a heuristic concession to TPE’s assumption of hyperparameter independence: as our search moves through space, we use temporal distance within the experiment as a surrogate for distance in the search space.
