### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by Ingvar-Y** [hyperopt/hyperopt#468]
Last release was in the end of August. Since then a few bugs were corrected, QoL changes introduced and a new dependency added - hyperopt has changed enough to consider switching from last release to building from source. However, pre-built packages are easier to use - for example, I have to maintain python environment on a server without access to the internet and each package built from source requires additional time and attention whenever I update packages on the server. Generally I think slow-updating projects like this one could use something like biannual release schedule to keep tarballs roughly up-to-date.

@maxpumperla what do you think?

**Comment by PhilipMay** [comment]
I would vote for a new release.

**Comment by maxpumperla** [comment]
@Ingvar-Y @PhilipMay guys, I'm in. no questions about it, it's time. In general, it's a good idea to remind me, hyperopt releases aren't my main prio right now, but I can usually squeeze one in. thanks!

**Comment by PhilipMay** [comment]
Ok - I will prepare the conda release after that...

**Comment by PhilipMay** [comment]
And do the documentation for my progressbar... :-)

**Comment by maxpumperla** [comment]
@Ingvar-Y @PhilipMay 0.1.2 is up. thanks for bearing with me. :+1:
