### ISSUE TITLE
Error when removing hyperopt worker directories.

### ISSUE THREAD

**Issue by ernestum** [hyperopt/hyperopt#469]
When I set `erased_created_workdir=True` in the `run_one` method of the MongoWorker, I often get failed runs with the error message:
```
INFO (hyperopt.mongoexp): job exception: [Errno 2] No such file or directory: 'home.inuse'
```
I think this is related to the [temp dir context manager](https://github.com/hyperopt/hyperopt/blob/fa4690219abee0cbd91b9db712485b1f7349c455/hyperopt/utils.py#L225). Here the sentinel file is removed after the surrounding dictionary has already been removed. This destroys a perfectly fine trial.

**Comment by skebanga** [comment]
Did you get anywhere with this?
