### ISSUE TITLE
I meet KeyError: 'loss' when I use hyperopt and Sklearn-LGBMClassifier 

### ISSUE THREAD

**Issue by SwimSweet** [hyperopt/hyperopt#470]
I get the KeyError: 'loss' message when   I use hyperopt and Sklearn-LGBMClassifier 。

```python
I get the following exception:
INFO：---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/hyperopt/base.py in evaluate(self, config, ctrl, attach_attachments)
    852                 try:
--> 853                     dict_rval['loss'] = float(dict_rval['loss'])
    854                 except (TypeError, KeyError):

KeyError: 'loss'

During handling of the above exception, another exception occurred:

InvalidLoss                               Traceback (most recent call last)
<ipython-input-28-cf4616ff7168> in <module>()
----> 1 best_class = fmin(f_class, space_dt_class, algo=tpe.suggest, max_evals=100, trials=trials_class)

/opt/conda/lib/python3.6/site-packages/hyperopt/fmin.py in fmin(fn, space, algo, max_evals, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin, points_to_evaluate, max_queue_len)
    365             verbose=verbose,
    366             catch_eval_exceptions=catch_eval_exceptions,
--> 367             return_argmin=return_argmin,
    368         )
    369 

/opt/conda/lib/python3.6/site-packages/hyperopt/base.py in fmin(self, fn, space, algo, max_evals, rstate, verbose, pass_expr_memo_ctrl, catch_eval_exceptions, return_argmin)
    633             pass_expr_memo_ctrl=pass_expr_memo_ctrl,
    634             catch_eval_exceptions=catch_eval_exceptions,
--> 635             return_argmin=return_argmin)
    636 
    637 

/opt/conda/lib/python3.6/site-packages/hyperopt/fmin.py in fmin(fn, space, algo, max_evals, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin, points_to_evaluate, max_queue_len)
    383                     max_queue_len=max_queue_len)
    384     rval.catch_eval_exceptions = catch_eval_exceptions
--> 385     rval.exhaust()
    386     if return_argmin:
    387         return trials.argmin

/opt/conda/lib/python3.6/site-packages/hyperopt/fmin.py in exhaust(self)
    242     def exhaust(self):
    243         n_done = len(self.trials)
--> 244         self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
    245         self.trials.refresh()
    246         return self

/opt/conda/lib/python3.6/site-packages/hyperopt/fmin.py in run(self, N, block_until_done)
    216             else:
    217                 # -- loop over trials and do the jobs directly
--> 218                 self.serial_evaluate()
    219 
    220             if stopped:

/opt/conda/lib/python3.6/site-packages/hyperopt/fmin.py in serial_evaluate(self, N)
    135                 ctrl = base.Ctrl(self.trials, current_trial=trial)
    136                 try:
--> 137                     result = self.domain.evaluate(spec, ctrl)
    138                 except Exception as e:
    139                     logger.info('job exception: %s' % str(e))

/opt/conda/lib/python3.6/site-packages/hyperopt/base.py in evaluate(self, config, ctrl, attach_attachments)
    853                     dict_rval['loss'] = float(dict_rval['loss'])
    854                 except (TypeError, KeyError):
--> 855                     raise InvalidLoss(dict_rval)
    856 
    857         if attach_attachments:

InvalidLoss: 

```
I don't understand why I get the ` 'KeyError: 'loss''`

the code i use is below:
```python
train_X_class=train_df[features]
train_Y_class=train_df.outliers


def hyperopt_lgb_class(params):
    clf =lgb.LGBMClassifier(**params)
    return cross_val_score(clf, train_X_class, train_Y_class,scoring='neg_log_loss',cv=10).mean()

def f_class(parms):
    log_loss = hyperopt_lgb_class(parms)
    return {'log_loss': log_loss, 'status': STATUS_OK}

space_dt_class = {
    'task':'train',
    'boosting_type':'goss',
    'max_depth': hp.choice('max_depth', range(8,40)),
    'num_leaves': hp.choice('num_leaves', range(31,70)),
    'objective': 'binary',
    'metric': 'binary_logloss',
    'min_child_weight': hp.uniform('min_child_weight', 20,50),
    'subsample': hp.uniform('subsample', 0.8,1),
    'reg_lambda':hp.uniform('reg_lambda',5,15),
    'min_split_gain':hp.uniform('min_split_gain',8,15),
    'colsample_bytree':hp.uniform('colsample_bytree',0.5,1),
    'min_data_in_leaf':hp.choice('min_data_in_leaf',range(20,30)),
    'top_rate':hp.uniform('top_rate',0.7,0.9),
    'reg_alpha':hp.uniform('reg_alpha',1,10),
    'learning_rate':hp.uniform('learning_rate',0.01,0.05),
    'other_rate':hp.uniform('other_rate',0.01,0.09),
}

trials_class = Trials()

best_class = fmin(f_class, space_dt_class, algo=tpe.suggest, max_evals=100, trials=trials_class)
```

**Comment by SwimSweet** [comment]
I get it .The problem have been solved.

**Comment by doubianimehdi** [comment]
How ? Please explain , i'm having the same problem ! Thanks !

**Comment by mwijaya3** [comment]
How did you fix it @SwimSweet ?

**Comment by ncuxomun** [comment]
> How did you fix it @SwimSweet ?
> 
> Edit: See below..
> 
> > How ? Please explain , i'm having the same problem ! Thanks !
> 
> In case you are wondering, change your return in OP case from `'log_loss': log_loss` to `'loss': loss`

I am facing similar problem. However, I can't seem to fix the issue even after your suggested 'fix'.

Here is my initial code snippet:

    optimizer = tf.keras.optimizers.Adam(lr)

    model.compile(loss='mse', metrics=['mse'], optimizer=optimizer)

    early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=25)

    result = model.fit(X_train, y_train, batch_size={{choice([50, 100])}}, epochs=EPOCHS, verbose=1, validation_data=(X_valid, y_valid))

    #get the highest validation accuracy of the training epochs
    validation_loss = result.history['val_loss']

    print('Best validation loss of epoch:', validation_loss)

    return {'loss': validation_loss, 'status': STATUS_OK, 'model': model}

Can you please have a look see what could be the issue here? (changing to 'val_loss' did not help).

**Comment by bjkomer** [comment]
@ncuxomun can you post a minimum example showing your issue? Your snippet looks fine to me (assuming that run on its own it doesn't throw any errors). This is also assuming that it is from the objective function, which is being passed as the first parameter to `fmin`, and that `validation_loss` is a scalar.

**Comment by ncuxomun** [comment]
I am sorry, can you please elaborate what you meant by "example"? I have just run the script and received the error depicted below. 
![image](https://user-images.githubusercontent.com/54369128/78596937-79ae7c00-7801-11ea-9a60-fc4442ea4b4d.png)

**Comment by bjkomer** [comment]
It looks to me like your `validation_loss` variable is actually a list rather than a single value. The `'loss'` in the return value must be a single value and not a list. I'm assuming you meant to put a `max` on that before returning it.

**Comment by ncuxomun** [comment]
@bjkomer , I have taken np.amin(history['val_loss'] as shown here
![image](https://user-images.githubusercontent.com/54369128/78598941-0e66a900-7805-11ea-8034-b65551c8316e.png)

is that what you meant?

**Comment by bjkomer** [comment]
Yes, that is what I meant. The return value must contain a key called `'loss'` (spelt exactly like that) and the value must be a scalar which gives an indication of how well the run performed, where lower is better.

**Comment by michaelmior** [comment]
Looks like this has been resolved. Feel free to reopen if not!

**Comment by tibfab** [comment]
In case you are still looking the loss is not in the last element but in second to last.
`    def stop_fn(trials, best_loss=None, iteration_no_progress=0):
        
        # check for second to last trial element
        # the last trial contains ["result"]["status"] == "new"
        trials_idx = -2
        if len(trials.trials) < 2:
            trials_idx = -1

        print(f'---- trial index {trials_idx}')

        if trials.trials[trials_idx]["result"]["status"] == "new":
          return (False, [None, 0])
      
        new_loss = trials.trials[trials_idx]['result']["loss"]
        print(f'---- new_loss {new_loss}')
        if best_loss is None:
            return False, [new_loss, iteration_no_progress + 1]
        best_loss_threshold = best_loss - abs(best_loss * (percent_increase / 100.0))
        if new_loss is None or new_loss < best_loss_threshold:
            print(f'---- best_loss {new_loss}')
            best_loss = new_loss
            iteration_no_progress = 0
        else:
            iteration_no_progress += 1
            print(f'No progress made: {iteration_no_progress} iteration on {iteration_stop_count}. {best_loss = :.2f}, {best_loss_threshold = :.2f}, {new_loss = :.2f}')

        return (
            iteration_no_progress >= iteration_stop_count,
            [best_loss, iteration_no_progress],
        )

    return stop_fn`
