### ISSUE TITLE
New Progressbar doku to Wiki - how do I do that?

### ISSUE THREAD

**Issue by PhilipMay** [hyperopt/hyperopt#472]
Hi,
I would like to add a small chapter about the new progressbar to the wiki.
How do I do that? I think it's not possible to contribute pull requests to Wiki pages.
Should I just write some text here?
Thanks
Philip

**Comment by PhilipMay** [comment]
@maxpumperla can you help here please?
Thanks
Philip

**Comment by maxpumperla** [comment]
@PhilipMay we now have "proper" documentation here http://hyperopt.github.io/hyperopt/.

you can contribute to it by adding `md` files to `templates` in the `docs` folder (see https://github.com/hyperopt/hyperopt/tree/master/docs). Afterwards simply add the page you want in the navigation defined by `mkdocs.yml`. the readme tells you how to test this locally. After your potential PR gets merged I'll update the gh-pages branch and new docs are live.
