### ISSUE TITLE
Crash with nested parameters (because of yet unhandled case)

### ISSUE THREAD

**Issue by lebigot** [hyperopt/hyperopt#475]
(PS: the problem below looks like https://github.com/hyperopt/hyperopt/issues/175, which seems, as of 2016, to be a limitation that would require "a research project" to be conducted.)

The function `tpe:adaptive_parzen_normal()` sometimes gets a `prior_mu` argument that it cannot handle yet: the [code](https://github.com/hyperopt/hyperopt/blob/243aad99d383a644e7f6869291adf70b18e7dbe5/hyperopt/tpe.py#L432) assumes that `prior_mu` is an integer, but it can sometimes be an array (that seems to always contain a unique value, like `[15, 15, 15,…]`), in which case the code crashes.

Here is a minimal example (note that the simpler, non-nested case which is commented out works, as does the case of fewer trials):
```python
import hyperopt
from hyperopt import hp

x_distrib = hp.uniform("x", 0, 1)
hp_space = {"x": x_distrib, "y": hp.uniform("y", x_distrib, 1)}
# hp_space = x_distrib  # No problem!

trials = hyperopt.Trials()

hyperopt.fmin(lambda params: 1,
              space=hp_space,
              algo=hyperopt.tpe.suggest,
              max_evals=30,  # 20 works
              trials=trials)
```
```python
TypeError                                 Traceback (most recent call last)
<ipython-input-10-180cb9137c4f> in <module>()
     12               algo=hyperopt.tpe.suggest,
     13               max_evals=30,
---> 14               trials=trials)

…/lib/python2.7/site-packages/hyperopt/fmin.pyc in fmin(fn, space, algo, max_evals, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin, points_to_evaluate, max_queue_len, show_progressbar)
    386             catch_eval_exceptions=catch_eval_exceptions,
    387             return_argmin=return_argmin,
--> 388             show_progressbar=show_progressbar,
    389         )
    390 

…/lib/python2.7/site-packages/hyperopt/base.pyc in fmin(self, fn, space, algo, max_evals, rstate, verbose, pass_expr_memo_ctrl, catch_eval_exceptions, return_argmin, show_progressbar)
    637             catch_eval_exceptions=catch_eval_exceptions,
    638             return_argmin=return_argmin,
--> 639             show_progressbar=show_progressbar)
    640 
    641 

…/lib/python2.7/site-packages/hyperopt/fmin.pyc in fmin(fn, space, algo, max_evals, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin, points_to_evaluate, max_queue_len, show_progressbar)
    405                     show_progressbar=show_progressbar)
    406     rval.catch_eval_exceptions = catch_eval_exceptions
--> 407     rval.exhaust()
    408     if return_argmin:
    409         return trials.argmin

…/lib/python2.7/site-packages/hyperopt/fmin.pyc in exhaust(self)
    260     def exhaust(self):
    261         n_done = len(self.trials)
--> 262         self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
    263         self.trials.refresh()
    264         return self

…/lib/python2.7/site-packages/hyperopt/fmin.pyc in run(self, N, block_until_done)
    209                                                           d['result'].get('status')))
    210                         new_trials = algo(new_ids, self.domain, trials,
--> 211                                           self.rstate.randint(2 ** 31 - 1))
    212                         assert len(new_ids) >= len(new_trials)
    213                         if len(new_trials):

…/lib/python2.7/site-packages/hyperopt/tpe.pyc in suggest(new_ids, domain, trials, seed, prior_weight, n_startup_jobs, n_EI_candidates, gamma, linear_forgetting)
    906 
    907     idxs, vals = pyll.rec_eval([opt_idxs, opt_vals], memo=memo,
--> 908                                print_node_on_error=False)
    909 
    910     # -- retrieve the best of the samples and form the return tuple

…/lib/python2.7/site-packages/hyperopt/pyll/base.pyc in rec_eval(expr, deepcopy_inputs, memo, max_program_len, memo_gc, print_trace, print_node_on_error)
    911 
    912             try:
--> 913                 rval = scope._impls[node.name](*args, **kwargs)
    914 
    915             except Exception as e:

…/lib/python2.7/site-packages/hyperopt/tpe.pyc in adaptive_parzen_normal(mus, prior_weight, prior_mu, prior_sigma, LF)
    440         #time.sleep(1)
    441 
--> 442         srtd_mus[:prior_pos] = mus[order[:prior_pos]]
    443         srtd_mus[prior_pos] = prior_mu
    444         srtd_mus[prior_pos + 1:] = mus[order[prior_pos:]]

TypeError: only integer scalar arrays can be converted to a scalar index
```

**Comment by peterjhPark** [comment]
I want to set a constraint between two variables, a + b < 10 , but I also met same problem. 

<from hyperopt import hp, fmin, tpe
import numpy as np

x = np.arange(-10,10,1)
y = 3 * x **2 + 6 * x  - 1

def func (space):
    a = space['a']
    b = space['b']
    l = np.sqrt(np.sum(((a * x **2 + b * x  - 1) - y)**2) / len(x))
    return l

space_a = hp.uniform('a', 0, 10)
space_b = hp.uniform('b', 0, 10 - space_a)

space = {'a'          : space_a,
        'b'          : space_b}

best = fmin(fn = func, space = space, algo=tpe.suggest, max_evals=50, show_progressbar=True)>

**Comment by lebigot** [comment]
I don't mind lending a hand in order to solve this very inconvenient situation, but after looking at the code, I'm really not sure of what's going on and what should be done: in order to help, I would first need some advice from an expert.

**Comment by DTMilodowski** [comment]
Hello,

Just wondering whether you managed to find a solution to this? I'm getting a similar error when using nested search spaces as you describe, i.e. something along the lines of:

a = hp.quniform("a",2,200,1)
b = hp.quniform("b",1,a,1)

In my case I'm using python 3.6.7 and numpy 1.16.2

Thanks in advance!

**Comment by lebigot** [comment]
Unfortunately not: the code is not easy to read if you haven't written it yourself. So it requires a *lot* more work for someone like me to try to fix the program than for one of its authors (like maybe 20 times more time?).

It would therefore be great for the community if the original authors could at least give some hints about what could be going on and what kind of modifications would be needed.

**Comment by DTMilodowski** [comment]
Thanks for replying so quickly. Hopefully there will be a response from the authors soon.

**Comment by PhilipMay** [comment]
@lebigot 
I think your nesting ist not right.

What you write here:
```
x_distrib = hp.uniform("x", 0, 1)
hp_space = {"x": x_distrib, "y": hp.uniform("y", x_distrib, 1)}
```

Is transfered to this:
```
hp_space = {"x": hp.uniform("x", 0, 1), "y": hp.uniform("y", hp.uniform("x", 0, 1), 1)}
```

Which is not ok I think. You are nesting `hp.uniform`...
The following code would be ok:

```
import hyperopt
from hyperopt import hp

x_distrib = hp.uniform("x", 0, 1)
y_distrib = hp.uniform("y", 0, 1)
hp_space = {"x": x_distrib, "y": y_distrib}

trials = hyperopt.Trials()

hyperopt.fmin(lambda params: 1,
              space=hp_space,
              algo=hyperopt.tpe.suggest,
              max_evals=30,  
              trials=trials)
```

I hope that helps.

More about this kind of nesting is written here:
https://github.com/hyperopt/hyperopt/wiki/FMin#22-a-search-space-example-scikit-learn

**Comment by DTMilodowski** [comment]
I'm not sure if this resolves the problem. I think the idea of the suggested nested parameter space is to place conditions between the parameters e.g. to avoid combinations that are not sensible.

In the example provided by @lebigot, both "x" and "y" are uniformly distributed parameters, but the intention for the nesting (assuming I've understood correctly) is to specify that "y" must always be greater than "x".

In your example, "x" and "y" are drawn independently from a uniform distribution between 0 and 1, so the condition that "y">"x" is not always satisfied.

In my experience, nested parameter spaces seem to be ok with a randomised search, but I get the aforementioned error message when switching to tpe.

**Comment by lebigot** [comment]
@DTMilodowski: exactly! In other words, in the original example, x is between 0 and 1, and y is between x and 1. That's indeed the whole point of nesting parameters.

**Comment by lebigot** [comment]
Now I see that solving this issue would be a full "research project": see issue https://github.com/hyperopt/hyperopt/issues/175.

**Comment by lebigot** [comment]
The best answer I could find so far to this problem is https://github.com/hyperopt/hyperopt/issues/175#issuecomment-29401501.

**Comment by DTMilodowski** [comment]
Thanks for pointing me in that direction. For now I'm following the advice in that post and rejecting unacceptable parameter spaces and increasing the number of evaluations accordingly. Not the most elegant solution, but probably sufficient for my purposes.

**Comment by suleka96** [comment]
Hi, 

I appolagize if my issue sounds stupid but I'm new to machine learning and just started to experiment with hyperopt. I ended up facing the same problem and as per the suggestions I modified my code to do as shown below without nesting parameters (it is required that  mx always be larger than ms and my parameter space is dynamically generated):

```
def HyperparameterTuning(param):

    if(param['ms'] < param['mx']):

        WriteFlags(param)
        subprocess.check_call(['./microwise.sh', isFirstRun])
        WriteCsv(param)
        latency_vals = pd.read_csv("agg_test.csv")
        bottom = latency_vals.tail(1)
        print(bottom["99% Line"].values[0])
        print("in true")
        return {'loss': bottom["99% Line"].values[0], 'status': STATUS_OK}
    else:
        return {'status': STATUS_FAIL}


 trials = Trials()
    best = fmin(fn=HyperparameterTuning,
                    space=space,
                    algo=tpe.suggest,
                    max_evals=30,
                    trials=trials)
```
Will doing like this obstruct the tuning process or is this the only possible solution?
