### ISSUE TITLE
Single condition for several parameters?

### ISSUE THREAD

**Issue by vladradishevsky** [hyperopt/hyperopt#477]
How can I add my own condition for example:

a = hp.uniform('a', 0.0, 1.0)
b = hp.uniform('b', 0.0, 1.0)
c = hp.uniform('c', 0.0, 1.0)

And sum of a, b and c must be equal to one ?

**Comment by PhilipMay** [comment]
Use softmax in the function?

**Comment by 1kastner** [comment]
One solution can be seen at https://github.com/hyperopt/hyperopt/issues/337 -- adding you own penalty.
Anyhow, in the source it says that this approach was not successful.
