### ISSUE TITLE
hyperopt samples same hyperparameters in random mode

### ISSUE THREAD

**Issue by deFang** [hyperopt/hyperopt#494]
I was doing simple random parameter search with hyperopt and mongo-workers, the hyperparameter space is quite simple, but I found hyperopt samples duplicate point which had been tried before. Is that should be avoided?

**Comment by deFang** [comment]
just run another experiment, and found same for tpe mode.

**Comment by phyzhenli** [comment]
> I was doing simple random parameter search with hyperopt and mongo-workers, the hyperparameter space is quite simple, but I found hyperopt samples duplicate point which had been tried before. Is that should be avoided?

Did you find the solution?

**Comment by deFang** [comment]
not yet
