### ISSUE TITLE
Create space from json

### ISSUE THREAD

**Issue by david-waterworth** [hyperopt/hyperopt#507]
Hyperopt is a great library, I use it frequently. I have a couple of suggestions.

It would be really nice if it were possible to load/dump  a space to/from json. I know this is hard as the space syntax is quite expressive but I would really like to be able to store my space in a text format so I can report on it after training.

Also it would be good if it was possible to compare to spaces for equality (again I know this is difficult), and attach the space to a Trials object (i.e. make `space_eval` private and don't return raw parameter indices from Trial?). At the moment they're essentially coupled, as a Trial is on a space, so if you pickle a Trial you must also pickle the space (correct me if I'm wrong) or it's impossible to restore the hyper-parameters from each step and it's risky to resume with a different space since you cannot know which space to eval the parameters against?

**Comment by az0** [comment]
@david-waterworth For your first suggestion, see here https://github.com/hyperopt/hyperopt/issues/267

About your second suggestion, I don't lead the hyperopt project, but my suggestion to use is follow the principle "one issue per ticket" which makes tickets easier to manage

**Comment by david-waterworth** [comment]
@az0 I don't think that's related, it's about serialising the Trials object with pickle, I want to be able to serialise the Space object as a json file, so it's easier to specify (i.e. at the moment as far as I can see the only way to specify a Space is to construct it from code, I want to construct it from data as a config file)

**Comment by bjkomer** [comment]
Sounds like a very useful feature. For simple spaces (i.e. flat) you could do something like this:

```python
from hyperopt import hp, tpe, fmin, Trials
import json

def objective(args):
    # print just to make sure the parameters are coming through correctly
    print(args)
    return 1

# function for converting a dictionary read from a json file into a hyperopt space
def json_to_space(j):
    space = {}

    for key, value in j.items():
        if value[0] == 'quniform':
            space[key] = hp.quniform(key, *value[1:])
        elif value[0] == 'choice':
            space[key] = hp.choice(key, *value[1:])
        # etc ...

    return space

# this will come from your json file and can be loaded as a dictionary
space_json = {
    "p1": ['quniform', 10, 100, 1],
    "p2": ['quniform', 20, 200, 2],
    "p3": ['choice', ['a', 'b', 'c']],
}

# generate the hyperopt space from the dictionary
space = json_to_space(space_json)

# doublecheck that it is serializable
json.dumps(space_json)

fmin(objective, space, algo=tpe.suggest, max_evals=5)
```

For more complicated and nested spaces, something more sophisticated and robust would be needed. Possibly involving some recursive calls in the space generating function. It would also be nice to be able to convert back and forth between these representations. One way could be to have a json convert method on the `Apply` objects themselves.

**Comment by makquel** [comment]
I found an interesting class that apparently works well for more complex search spaces:
```python
class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, (np.int_, np.intc, np.intp, np.int8,
                            np.int16, np.int32, np.int64, np.uint8,
                            np.uint16, np.uint32, np.uint64)):

            return int(obj)

        elif isinstance(obj, (np.float_, np.float16, np.float32, np.float64)):
            return float(obj)

        elif isinstance(obj, (np.complex_, np.complex64, np.complex128)):
            return {'real': obj.real, 'imag': obj.imag}

        elif isinstance(obj, (np.ndarray,)):
            return obj.tolist()

        elif isinstance(obj, (np.bool_)):
            return bool(obj)

        elif isinstance(obj, (np.void)): 
            return None

        return json.JSONEncoder.default(self, obj)
```

https://github.com/hmallen/numpyencoder/blob/f8199a61ccde25f829444a9df4b21bcb2d1de8f2/numpyencoder/numpyencoder.py
