### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rickydatta** [hyperopt/hyperopt#510]
PyPI lists this package as BSD licensed. However the license file included in the source does not say BSD license. Can you clarify in your license that this is a BSD licensed project?

**Comment by krispcode** [comment]
Can you please clarify if the license file needs to be updated?

**Comment by rickydatta** [comment]
Please specify your license in the included license file without any ambiguity.

**Comment by maxpumperla** [comment]
@jaberg can you help out here?

**Comment by jaberg** [comment]
Hmm, the text in LICENSE.txt looks to be copied directly from the 3-clause BSD, with the only modifications being e.g. the name of the project, contributor(s) and date. Doesn't that make this project BSD licensed?

**Comment by jaberg** [comment]
I mean I didn't think the license file had to include the string "BSD" to be a BSD license.

**Comment by jaberg** [comment]
I'm looking at https://en.wikipedia.org/wiki/BSD_licenses for example, and it seems to me it's fine as is. No ambiguity, hyperopt has a BSD license.

**Comment by krispcode** [comment]
@jaberg for GitHub to identify the license, the repo needs to be tagged 

https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by maxpumperla** [comment]
@krispcode @rickydatta I'll modify the license early next week to reflect that. thanks for reporting this, I wasn't aware of the underlying issue.
