### ISSUE TITLE
hp.choice returning value

### ISSUE THREAD

**Issue by ghost** [hyperopt/hyperopt#511]
I was using `hp.choice('max_depth', [3, 4, 5])` but the answer I got from after using fmin was 0. It took my a while to figure it our that it returns the index, not the value. I think that's a problem since it's not written anywhere in your documentation and the only source I could find was this other issue #322 

I would like to know the reason why it returns the index, not the value. And if it's a option to change it to this form, since all the other options and algorithms use this format

**Comment by Alexsbuchanan** [comment]
You can use space_eval to evaluate the space properly and have it return the answer you want.

**Comment by michaelmior** [comment]
It seems like this issue has been resolved. If not, feel free to reopen.
