### ISSUE TITLE
Multi-GPU Search

### ISSUE THREAD

**Issue by JadBatmobile** [hyperopt/hyperopt#512]
Hello,

Say i have 3 GPUs, and i want to leverage that power to do the hyperparameter search.
I built my model with Keras.

How do i use hyperopt + MongoTrials such that:

Each GPU is being used to run one trial, so 3 trails at most can be running at once, and the CPU is being used to send each GPU instance the next hyperparameters to try.

I see the wiki on using mongo workers, but im not sure how to go from that, to what i mention above.

Thanks

**Comment by richardliaw** [comment]
Maybe try using Ray: https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/hyperopt_example.py

https://ray.readthedocs.io/en/latest/tune-distributed.html

**Comment by henrique** [comment]
I am not sure if Ray solves this use case.
I also need to pass a parameter to each worker, e.g. 'cuda:0' to the first worker, 'cuda:1' to the second, and so on. 
Same/similar when training on multiple tpu pods...
Does anyone have a solution or work-around for that?
Thanks
