### ISSUE TITLE
trials.vals prints  empty values for some of the hyperparamters

### ISSUE THREAD

**Issue by yashsharan** [hyperopt/hyperopt#513]
I dont know if this is the correct place to ask this or not. I have been trying to replicate the results of  the paper Random Search for Hyper-Parameter Optimization using the Hpnnet code(which is the code used for the research paper). However after running hyperopt.fmin and printing the trials.vals to see value of hyperparaters for each trial, a lot of values of hyper-parameters and empty and I'm not able to figure out why. If i'm not wrong then every hyper-parameter should have some value.
Here is the snippet of the output.

> {'sample_v0s_2': [], 'iseed': [1], 'W_ialgo_2': [], 'W_ialgo_0': [1], 'W_ialgo_1': [], 'preproc': [0, 0, 0, 0, 0], 'lr': [0.04776717187606179, 3.669268965097567, 0.0002581138759623187, 0.009675809159205814, 0.004790139432243304], 'lr_anneal_2': [], 'W_idist_2': [], 'W_idist_1': [], 'W_idist_0': [1], 'l2_penalty_nz': [2.8216295259137156e-07], 'n_hid_2': [], 'n_hid_0': [1616.0], 'n_hid_1': [], 'batch_size': [0, 1, 1, 1, 0], 'lr_anneal_start': [119.0, 1329.0, 1252.0, 336.0, 197.0], 'cd_lr_0': [0.01285890565447791], 'cd_lr_1': [], 'cd_lr_2': [], 'lr_anneal_0': [73.0], 'lr_anneal_1': [], 'cd_epochs_0': [79.0], 'cd_epochs_1': [], 'cd_epochs_2': [], 'W_imult_1': [], 'W_imult_0': [], 'W_imult_2': [], 'cd_seed_2': [], 'cd_seed_1': [], 'cd_seed_0': [1], 'depth': [0, 1, 0, 0, 0], 'l2_penalty': [1, 0, 0, 0, 0], 'pca_energy': [], 'sample_v0s_1': [], 'sample_v0s_0': [0]}

As you can see lot of the values are empty.This happens for both TPE and random search. If i'm not wrong there should be some values in each of the hyperparameter.

**Comment by bjkomer** [comment]
That will happen if the parameter is on a conditional branch that does not get chosen. This is correct behaviour in that case.

What does your search space look like? Do you have a link to your code?

It's also important to note that `trials.vals` doesn't show the value of the hyperparameters for each trial, it shows a compressed summary across all trials. `trials.trials` will give you a list, where every element is a dictionary corresponding to a particular trial, which will include a bunch of information including the parameter values for that individual trial.
