### ISSUE TITLE
How to put KerasClassifier, Hyperopt and  Sklearn cross-validation togethert

### ISSUE THREAD

**Issue by PANXIONG-CN** [hyperopt/hyperopt#516]
I am performing a hyperparameter tuning optimization (hyperopt) tasks with sklearn on a Keras models. I am trying to optimize KerasClassifiers using the Sklearn cross-validation, Some code follows:

    def create_model():
    model = Sequential()
    model.add(
        Dense(output_dim=params['units1'],
              input_dim=features_.shape[1],
              kernel_initializer="glorot_uniform"))
    model.add(Activation(params['activation']))
    model.add(Dropout(params['dropout1']))
    model.add(BatchNormalization())
    ...
    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])

    return model

Now what I want to do is to pass the Hyperopt params to KerasClassifier using the following way

    def objective(params, n_folds=N_FOLDS):
    """Objective function for Hyperparameter Optimization"""

    # Keep track of evals
    global ITERATION

    ITERATION += 1

    clf = KerasClassifier(build_fn=create_model,**params)

    start = timer()

    # Perform n_folds cross validation
    cv_results = cross_val_score(clf,
                                 features_,
                                 labels,
                                 cv=5
                                 ).mean()

    run_time = timer() - start

    # Loss must be minimized
    loss = -cv_results

    # Dictionary with information for evaluation
    return {
        'loss': loss,
        'params': params,
        'iteration': ITERATION,
        'train_time': run_time,
        'status': STATUS_OK
    }
I define the search space as:

    space = {
    'units1':
    hp.choice('units1', [64, 128, 256, 512]),
    'units2':
    hp.choice('units2', [64, 128, 256, 512]),
    'dropout1':
    hp.choice('dropout1', [0.25, 0.5, 0.75]),
    'dropout2':
    hp.choice('dropout2', [0.25, 0.5, 0.75]),
    'batch_size':
    hp.choice('batch_size', [10, 20, 40, 60, 80, 100]),
    'nb_epochs':
    hp.choice('nb_epochs', [10, 50, 100]),
    'optimizer':
    opt_search_space,
    'activation':
    'relu'
}

Run optimization

    best = fmin(fn = objective, space = space, algo = tpe.suggest, 
                max_evals = MAX_EVALS, trials = bayes_trials, rstate = np.random.RandomState(50))

But it fails giving this error:

    ValueError: activation is not a legal parameter

What's the right way to do it?

**Comment by bjkomer** [comment]
It looks like you are using `KerasClassifier` incorrectly. Specifically I believe your `create_model` function needs to accept some arguments. If you look at the keras code [here](https://github.com/keras-team/keras/blob/master/keras/wrappers/scikit_learn.py#L73) you can see that it is trying to find the legal arguments from your `build_fn` which has none. I'm guessing if you modify your `create_model` to have named arguments that match what is in `params` rather than using a global variable it would work.

Everything looks fine on the `hyperopt` side of things.
