### ISSUE TITLE
File "/home/saireddy/anaconda3/envs/my_env/lib/python3.6/hyperas/optim.py", line 97, in base_minimizer     from temp_model import keras_fmin_fnct, get_space    File "/home/saireddy/Desktop/temp_model.py", line 1     importers when locating support scripts as well as when importing modules.                  ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by saichandrareddy1** [hyperopt/hyperopt#519]
``File "/home/saireddy/anaconda3/envs/my_env/lib/python3.6/hyperas/optim.py", line 97, in base_minimizer
    from temp_model import keras_fmin_fnct, get_space

  File "/home/saireddy/Desktop/temp_model.py", line 1
    importers when locating support scripts as well as when importing modules.
                 ^
SyntaxError: invalid syntax

**Comment by saichandrareddy1** [comment]
i'm new to tuning deep learning cnn please help me

**Comment by PhilipMay** [comment]
Can you please show all of your code here - so we can help?

**Comment by saichandrareddy1** [comment]
__author__ = "Sai Reddy"
#https://www.cs.ubc.ca/~murphyk/videodata.html

from __future__ import print_function
from hyperopt import Trials, STATUS_OK, tpe
from hyperas import optim
from hyperas.distributions import choice, uniform
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.datasets import mnist
from keras.utils import np_utils
from keras import applications
from keras.models import Model, Sequential
from keras.layers import Dense, Input, BatchNormalization
from keras.layers.pooling import GlobalAveragePooling2D, GlobalAveragePooling1D
from keras.layers.recurrent import LSTM
from keras.layers.wrappers import TimeDistributed
from keras.optimizers import Nadam, SGD, Adam, RMSprop
#from keras.preprocessing.image import ImageDataGenerator   #2D DATA
from keras.layers.convolutional_recurrent import ConvLSTM2D
from keras.layers import Conv3D, Conv2D, MaxPool2D, Flatten, Dropout, Lambda, ZeroPadding2D
import os
import numpy as np
import keras.backend as K
from keras.preprocessing.image import img_to_array, load_img
import pandas as pd
from Generator import ImageDataGenerator ##3D DATA
from keras import regularizers
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, TensorBoard, EarlyStopping


def data():
    '''
    Data providing function:
    This function is separated from model() so that hyperopt
    won't reload data for each evaluation run.
    '''
    datagen = ImageDataGenerator(
        rescale = 1./255,
        featurewise_center=True, 
        samplewise_center=True,
        rotation_range=20, width_shift_range=0.3,
        height_shift_range=0.0,
        shear_range=0.2, zoom_range=0.2, 
        channel_shift_range=0.0, fill_mode='nearest', 
        cval=0.0, horizontal_flip=True, vertical_flip=True,
        data_format=None)

 
    train_generator = datagen.flow_from_directory("/home/saireddy/Action/Tennis/TrainImages", class_mode='binary',
                                        target_size=(320, 180), 
                                        classes = ['backhand', 'smash'],
                                        batch_size=16, frames_per_step=4)
    
    validation_generator = datagen.flow_from_directory("/home/saireddy/Action/Tennis/ValImages", class_mode='binary',
                                        target_size=(320, 180),
                                        classes = ['backhand', 'smash'],
                                        batch_size=16, frames_per_step=4)
    
    test_generator = datagen.flow_from_directory("/home/saireddy/Action/Tennis/TestImages", class_mode='binary',
                                        target_size=(320, 180),
                                        classes = ['backhand', 'smash'],
                                        batch_size=16, frames_per_step=4)
    

    
    
    
    return train_generator, test_generator, validation_generator




def model(train_generator, test_generator, validation_generator):
    
    '''
    Model providing function:
    Create Keras model with double curly brackets dropped-in as needed.
    Return value has to be a valid python dictionary with two customary keys:
        - loss: Specify a numeric evaluation metric to be minimized
        - status: Just use STATUS_OK and see hyperopt documentation if not feasible
    The last one is optional, though recommended, namely:
        - model: specify the model just created so that we can later use it again.'''
        
        
    frames = 3
    img_width = 320
    img_height = 180
    channels = 3
    print(frames, img_width, img_height, channels)


    #MODEL .........-----------**************************##
    model = Sequential()

    ###CONV LAYER
    model.add(TimeDistributed(Conv2D(3, 3, 1,activation='relu'
                                         ,border_mode='valid'), 
                  input_shape = (frames, img_width, img_height, channels)))
    print(model.output_shape)
    model.add(Dropout({{uniform(0, 0.6)}}))

    ###CONV2
    model.add(TimeDistributed(ZeroPadding2D(1)))
    model.add(TimeDistributed(Conv2D(3, 3, 1,activation='relu'
                                         ,border_mode='valid', kernel_regularizer=regularizers.l2(0.001))))
    print(model.output_shape)

    ###MAXPOOL 1
    model.add(TimeDistributed(MaxPool2D((2,2))))
    model.add(Dropout({{uniform(0, 0.6)}}))

    ###CONV 3
    print(model.output_shape)
    model.add(TimeDistributed(ZeroPadding2D(1)))
    model.add(TimeDistributed(Conv2D(5, 3, 1,activation='relu',border_mode='valid', 
                                     kernel_regularizer=regularizers.l2(0.001))))
    

    ####FLATTEN LAYER
    model.add(TimeDistributed(Flatten()))
    print(model.output_shape)

    ####LSTM LAYER
    model.add(LSTM(1, return_sequences=False, kernel_regularizer=regularizers.l2(0.001)))

    ###DENSE LAYER
    model.add(Dropout({{uniform(0, 1)}}))
    print(model.output_shape)
    model.add(Dense({{choice([50, 75, 100])}}))
    model.add(Activation({{choice(['relu', 'sigmoid'])}}))
    model.add(Dropout({{uniform(0, 1)}}))
    model.add(Dense(75, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
    model.add(Dense(2, activation = 'softmax'))
    model.summary()
            
    # Train the model for a specified number of epochs.
    #SGD = SGD(lr=0.001, decay=1e-6, momentum=0.7, nesterov=True)
    #Adam = Adam(lr = 0.001)
    #RMSprop = RMSprop(lr = 0.001)
              
    model.compile(loss='sparse_categorical_crossentropy',
                  optimizer={{choice(['rmsprop', 'adam', 'sgd'])}},
                  metrics=['accuracy'])
    
    
    checkpoint = ModelCheckpoint("output/ActionData/LRCNN3.h5", monitor='val_acc', verbose=1, 
                                 save_best_only=True, save_weights_only=False, mode='auto', period=1)
    early = EarlyStopping(monitor='val_acc', min_delta=0, patience=5, verbose=1, mode='auto')


    history = model.fit_generator(train_generator, steps_per_epoch = 50,
                        epochs = {{choice([30, 50])}} , validation_data=validation_generator,
                        validation_steps=3, verbose=1,
                        callbacks = [checkpoint, early])

        # Evaluate the model with the eval dataset.
    score  = model.evaluate_generator(test_generator, steps = 20)
    
    import matplotlib.pyplot as plt
    print(history.history.keys())
    # summarize history for accuracy
    plt.plot(history.history['acc'])
    plt.plot(history.history['val_acc'])
    plt.title('model accuracy')
    plt.ylabel('accuracy')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()
        
        
    # summarize history for loss
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epoch')
    plt.legend(['train', 'test'], loc='upper left')
    plt.show()
        
    print('Test accuracy:', score[1])
    
    return {'loss': -score[0], 'status': STATUS_OK, 'model': model}

best_run, best_model = optim.minimize(model=model,
                                      data=data,
                                      max_evals=5,
                                      algo=tpe.suggest,
                                      trials=Trials())

**Comment by saichandrareddy1** [comment]
Running in  spyderm python 3.6, GPU-nvidia 940MX, Ubuntu 19.01
