### ISSUE TITLE
AllTrialsFailed causes hard crash in hpsklearn

### ISSUE THREAD

**Issue by ptyshevs** [hyperopt/hyperopt#522]
https://github.com/hyperopt/hyperopt/blob/762e89f14af8a6bacbcf258f8b5db063e297bcca/hyperopt/base.py#L581-L584

The use-case I'm stuck with is that during the first few iterations of `HyperoptEstimator().fit()` with small timeout this exception is raised. The quickfix I've used is that instead of raising an Exception, I return `None` from `Trials.best_trial`, and then handling this case in `fmin`:

https://github.com/hyperopt/hyperopt/blob/762e89f14af8a6bacbcf258f8b5db063e297bcca/hyperopt/fmin.py#L411-L415

by replacing `len(trials) > 0` with `len([t for t in trials if t["result"]["status"] == 'ok']) > 0`.

What effectively it does is allowing for `best_case` indicator during `fit` to remain in unknown state `?` until at least one non-failing candidate is generated.

What do you think of it?

**Comment by pengcao** [comment]
the newest version is ok?

**Comment by BouweCeunen** [comment]
Does someone have a fork of this fix? Would be nice to avoid manually editing files.
