### ISSUE TITLE
loss_variance field usage

### ISSUE THREAD

**Issue by bkozyrskiy** [hyperopt/hyperopt#523]
Documentation for hyperopt says, that fmin function responds to 'loss_variance' key in the dictionary, returned by an objective function. But I didn't manage to find any information, how
this additional info affects the optimization process. Does the current implementation of TPE take into consideration sampling variance (the variance of the objective function)?

**Comment by spiritix** [comment]
+1 Would appreciate an explanation

**Comment by michaelmior** [comment]
I believe the loss variance is currently unused.
