### ISSUE TITLE
cannot import name 'BSON' on new release 0.2

### ISSUE THREAD

**Issue by grfreitas** [hyperopt/hyperopt#541]
When calling fmin:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<command-1644382932079013> in <module>()
----> 1 from bson import BSON

ImportError: cannot import name 'BSON'
```

**Comment by richardliaw** [comment]
+1

**Comment by Chriskuei** [comment]
+1

**Comment by WeiwenRen** [comment]
+1

**Comment by kiran-kate** [comment]
Looks like commit 4dae46c4724d4796c6a83f146e8f336013ad9bdf caused this change. Any plans to revert it? Otherwise, packages dependent on Hyperopt are locked in with version 0.1.2 or have to handle the bson dependency themselves.

**Comment by Spinachboul** [comment]
if pymongo has its own internal bson package, then how are we supposed to use bson in our code, and how are we supposed to import it?
