### ISSUE TITLE
Line 399: Error message: "module 'bson' has no attribute 'BSON'"

### ISSUE THREAD

**Issue by rossmpowell** [hyperopt/hyperopt#547]
Hi all, 

I am working on a machine learning project, and using the Hyperas package to tune my model. Hyperas uses two functions to setup a tuning job: a data function, and model function. So far I've had some issues with them talking to each other during the encoding stage of building the model because the bson.BSON object called in hyperopt/base.py does not exist.

I ended up checking out the bson code found here: https://github.com/py-bson/bson, and the bson.BSON object does not exist there either. Is there a different bson distribution or package that I should be using?
____________________________________________________________________________________
Notes:
- I'm using an AWS SageMaker notebook, that could also have something to do with bson being imported weirdly behind the scenes.
- A somewhat related issue: https://github.com/maxpumperla/hyperas/issues/23

Thanks!

**Comment by rossmpowell** [comment]
Update (Solution):

The sequence of imports below worked for getting bson a moment ago

pip install bson 
pip install hyperopt
pip install hyperas
sudo pip uninstall bson
pip install pymongo

(Solution is similar to what was referenced in maxpumperla/hyperas#23)

**Comment by PhilipMay** [comment]
I have the same problem (see below). Although there seems to be a workaround: can someone please fix this?

```
[...]
  File "/home/phmay/miniconda3/envs/tf2/lib/python3.6/site-packages/mltb/hyperopt.py", line 99, in fmin
    show_progressbar=show_progressbar,
  File "/home/phmay/miniconda3/envs/tf2/lib/python3.6/site-packages/hyperopt/fmin.py", line 403, in fmin
    show_progressbar=show_progressbar,
  File "/home/phmay/miniconda3/envs/tf2/lib/python3.6/site-packages/hyperopt/base.py", line 651, in fmin
    show_progressbar=show_progressbar)
  File "/home/phmay/miniconda3/envs/tf2/lib/python3.6/site-packages/hyperopt/fmin.py", line 422, in fmin
    rval.exhaust()
  File "/home/phmay/miniconda3/envs/tf2/lib/python3.6/site-packages/hyperopt/fmin.py", line 276, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/phmay/miniconda3/envs/tf2/lib/python3.6/site-packages/hyperopt/fmin.py", line 225, in run
    self.trials.insert_trial_docs(new_trials)
  File "/home/phmay/miniconda3/envs/tf2/lib/python3.6/site-packages/hyperopt/base.py", line 435, in insert_trial_docs
    for doc in docs]
  File "/home/phmay/miniconda3/envs/tf2/lib/python3.6/site-packages/hyperopt/base.py", line 435, in <listcomp>
    for doc in docs]
  File "/home/phmay/miniconda3/envs/tf2/lib/python3.6/site-packages/hyperopt/base.py", line 399, in assert_valid_trial
    bson.BSON.encode(trial)
AttributeError: module 'bson' has no attribute 'BSON'
```

**Comment by rugg2** [comment]
I am still having the issue `AttributeError: module 'bson' has no attribute 'BSON'`

when I type the code:
```
best_param = fmin(
        objective_function,
        param_hyperopt,
        algo=tpe.suggest,
        max_evals=3,
    )
```

I run on version **hyperopt 0.2.1** from pypi, last released 2 days ago, which corresponds with the merge above.

Has the fix been deployed?

**Comment by palicand** [comment]
@rugg2 As far as I can tell, it has not `0.2.1` has been released on 17. 10. 2019 based on releases here on GitHub, which is before the fix. I guess we need to ping @maxpumperla, as he seems to be the primary maintainer :-)

**Comment by maxpumperla** [comment]
@palicand thanks for pinging me. I'll do another minor release for this in a bit.

**Comment by maxpumperla** [comment]
@palicand and others, I didn't explicitly mention it here, but `0.2.2` has been up for a while and contains this fix.

**Comment by AwasthiMaddy** [comment]
In `0.2.2` also, I am facing this same error.

`AttributeError: module 'bson' has no attribute 'BSON`

**Comment by marctorrellas** [comment]
I tried both in my mac and an AWS Ubuntu instance, both using a fresh conda env with python3.6. In both places after doing the

```
python setup.py develop &&  pip install -e '.[MongoTrials, SparkTrials, ATPE, dev]'
```

I could open a python terminal and run `from bson import BSON`. When I proposed my solution here https://github.com/hyperopt/hyperopt/pull/549#issuecomment-545408519 was having problems with another AWS Linux instance, but at least in the one I tried today it seems to work. Maybe a new version of bson is fixing this? 🤷‍♂️Can you try now in a fresh env @AwasthiMaddy

**Comment by marctorrellas** [comment]
is this not a blocker anymore then @maxpumperla ?

**Comment by maxpumperla** [comment]
@marctorrellas thanks, seems good after all.

**Comment by KIC** [comment]
just installed 0.2.3 from pip having the same problem. However:

```
sudo -H pip uninstall bson
sudo -H pip install pymongo
```

solved the problem.

**Comment by marctorrellas** [comment]
> just installed 0.2.3 from pip having the same problem. However:
> 
> ```
> sudo -H pip uninstall bson
> sudo -H pip install pymongo
> ```
> 
> solved the problem.

not sure those `sudo` are needed
