### ISSUE TITLE
It seems that atpe does not support int or choice!

### ISSUE THREAD

**Issue by hfarazi** [hyperopt/hyperopt#553]
It seems that atpe does not support int or choice! Is it a bug or limitation of the method?

**Comment by FraserGrid** [comment]
I feel as though this may be related to my issue too... https://github.com/hyperopt/hyperopt/issues/552

**Comment by denizetkar** [comment]
I suffer from this problem as well. Actually I was trying to speed up evaluation of previously evaluated points. Then I came up with the following code snippet (which doesn't work because 'atpe' does not support 'choice'):

```
import hyperopt
from hyperopt import hp
from hyperopt.pyll.stochastic import sample
from hyperopt.fmin import generate_trials_to_calculate

space = {'a': hp.uniform('a', 0, 1), 'b': hp.normal('b', 0, 1), 'loss': hp.pchoice('loss_exists', [(1, None), (0, hp.normal('loss', 0, 1))])}

def objective(params):
    if params['loss'] is not None:
        return params['loss']
    return params['a'] + params['b']

trials = generate_trials_to_calculate([{'a': 0, 'b': -3, 'loss_exists': 1, 'loss': -3}])
best_params = hyperopt.fmin(objective, space, algo=hyperopt.atpe.suggest, max_evals=1, trials=trials)
print(best_params)
```

Basically, I am looking for a way to kickstart the optimization with a list of points to evaluate and I also happen to have their loss values which I want to pass to the objective function. How can I do that while using ATPE?
(NOTE: all of my other hyper parameters are compatible with ATPE, just like the `'a'` and `'b'` in the example above)

**Comment by genixpro** [comment]
ATPE should support int & choice, let me investigate

**Comment by genixpro** [comment]
Have you gotten any errors or stacktraces when you attempt to use these hyperparameters?

**Comment by jithurjacob** [comment]
Any updates on this. I'm using 0.2.3 and is facing issues with pchoice and atpe

**Comment by BJWiley233** [comment]
So atpe is working with hp.choice but unfortunately for hp.uniform you get an index error in the recursion loop at `Hyperparameter.createHyperparameterConfigForHyperoptDomain` [here]()

works for choice eventually `fmin` gets here
```
ffn_hidden = np.array([150, 200, 250, 300, 400])
search_space = {
    'ffn_hidden': hp.choice('ffn_hidden', ffn_hidden),
}
## eventually fmin gets to something like
domain=search_space['ffn_hidden']
Hyperparameter.createHyperparameterConfigForHyperoptDomain(domain.pos_args[0].pos_args[1])
>>> {'type': 'number', 'min': 0, 'max': 5, 'mode': 'randint'}
```

doesn't work for uniform
```
search_space = {
    'enc_dropout_p': hp.uniform('enc_dropout_p', low=0.1, high=0.4),
}
domain=search_space['enc_dropout_p']
## eventually fmin gets to something like
Hyperparameter.createHyperparameterConfigForHyperoptDomain(domain.pos_args[0].pos_args[1])
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/deepchem/lib/python3.9/site-packages/hyperopt/atpe.py", line 421, in createHyperparameterConfigForHyperoptDomain
    data["min"] = domain.pos_args[0]._obj
IndexError: list index out of range
```
