### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by adaxidedakaonang** [hyperopt/hyperopt#564]
I installed the hyperopt and imported it to try the demo. However, after I run
`from hyperopt import hp` ,there had an error happend, that is:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/Downloads/hyperopt/hyperopt/__init__.py", line 7, in <module>
    from .base import STATUS_STRINGS
  File "/home/ubuntu/Downloads/hyperopt/hyperopt/base.py", line 158
    except Exception, e:
                    ^
SyntaxError: invalid syntax

My develop environment is python3.6, cuda10.1.

**Comment by maxpumperla** [comment]
@adaxidedakaonang right, python3 syntax is `except Exception as e:`. mind sending a quick PR?

I wonder why this doesn't get picked up anywhere.

**Comment by adaxidedakaonang** [comment]
@maxpumperla Hi it's hard to explain, when I tried to import it and found there was no error happened. Emmmm, so my problem is solved by doing nothing. Thank you.
