### ISSUE TITLE
Is there a way for a uniform integer search space?

### ISSUE THREAD

**Issue by c-phys** [hyperopt/hyperopt#566]
Hi,

from the methods for a search space I don't see a good way for uniform integer like 

`choice(1,2,3,4,5,6,...,100)`

there is only randint but this includes 0 which is mostly bad for deep learning.

So I need like for the uniform function but for integers with a lower and upper bound and steps!

`int_uniform(1,100,step=2)`

Is it right only possible to handcraft it with choice?

**Comment by bjkomer** [comment]
you can use `hp.quniform` to accomplish this

Something like `scope.int(hp.quiniform('my_param', 1, 100, q=1))` will do the trick.

By default `quniform` returns a float, so the `scope.int` just converts it to an integer for you

**Comment by c-phys** [comment]
Thank you!

**Comment by vladGriguta** [comment]
thanks for sharing!
to define scope function: 
`from hyperopt.pyll import scope`

**Comment by anxhelahyseni** [comment]
I am trying the above solution but instead of getting for example 8 I get 8.0. Is there any way that the above solution will give an int not float

**Comment by sadi-guzel** [comment]
`from hyperas.distributions import uniformint`
