### ISSUE TITLE
Trying to compare preprocessing techniques causes an error

### ISSUE THREAD

**Issue by joshred83** [hyperopt/hyperopt#568]
When trying to compare preprocessing techniques an error is triggered. 

Error: 
`ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().`

Example search space:
`space = {'params': {'max_depth': hp.uniformint('max_depth', 1, 30),
                    'max_features': hp.uniformint('max_features', 1, 29),
                    'max_leaf_nodes': hp.uniformint('max_leaf_nodes', 1, 75),
                    'min_samples_leaf': hp.uniformint('min_samples_leaf', 1, 75),
                    'min_samples_split': hp.uniformint('min_samples_split', 1, 75),
                    'min_weight_fraction_leaf': hp.uniform('min_weight_fraction_leaf', 0, 0.5),
                    'n_estimators': 10,
                    'n_jobs': 3
                    },
        'training_set': hp.choice('training_set', [(X_train_rand, y_train_rand),
                                                   (X_train_smote, y_train_smote),
                                                   (X_train_smoteenn, y_train_smoteenn)])}`

**Comment by bjkomer** [comment]
Hyperopt doesn't use the `DataFrame` object anywhere, so my guess is this has something to do with a problem with your code rather than hyperopt itself.

If it is a problem with hyperopt, we'll need the stack trace of the error and a minimum example of code that triggers it to debug.
