### ISSUE TITLE
extra comma, breaking code.

### ISSUE THREAD

**Issue by lannasjin** [hyperopt/hyperopt#571]
https://github.com/hyperopt/hyperopt/blob/2b114d01707b6f45f512fa1c648b5262437c9d94/hyperopt/fmin.py#L309

**Comment by bjkomer** [comment]
I don't see how this comma can cause an issue, it is valid Python syntax to have trailing commas. Can you explain the error you are getting?

**Comment by maxpumperla** [comment]
sorry, that's not a thing. feel free to reopen if something else is actually up
