### ISSUE TITLE
Getting the best_parameters from a trial object ?

### ISSUE THREAD

**Issue by christophelebrun** [hyperopt/hyperopt#572]
Hello,

Is there a way to get the best parameters from a trial object ?

From the `result` of a fmin function, I would do :
```
result = fmin([…])
best_params = space_eval(space, result)
```

But what if I want to get them from a (loaded) Trial() object ?
```
hypopt_trials = pickle.load(open("hp_trials/trials.hyperopt", "rb"))
best_trial = hypopt_trials.best_trial
```
Here, I get a `dict` object, with indexes. How do I make the link between it and my `space` object ?
Right now, the only turn-around that I have found is to make an other fmin run to get the result of it…

Thank you in advance !

**Comment by bjkomer** [comment]
I don't see a built-in function for doing this, but you can convert the best_trial dictionary into a format that works with `space_eval`. This can be done with the following code:

```python
# ...

trials = pickle.load(open("my_trial_file.pkl", "rb"))

best_trial = {}
for key, val in trials.best_trial['misc']['vals']:
    best_trial[key] = val[0]

print(space_eval(space, best_trial))

```

**Comment by christophelebrun** [comment]
Thank you for your answer.

During the mean time, I had come with another turn-around solution, which was to simply record the dictionary of the parameters (with pickle) at the same time as the Trial() object:

Save them:
```
    # Optimisation accross the search space
    global best_params
    best_params = fmin(
        obj_fnc,
        space=space,
        algo=tpe.suggest,
        max_evals=max_evals,
        trials=hypopt_trials
    )

    # save the trials object
    with open("hp_trials/trials.hyperopt", mode="wb") as f:
        pickle.dump(hypopt_trials, f)
        
    # get the best_params and save them
    best_params = space_eval(space, best_params)
    with open("hp_trials/best_params.hyperopt", mode="wb") as f:
        pickle.dump(best_params, f)
```

And to reload the dictionary of parameters:
```
import pickle

# Load the best_params
best_params = pickle.load(open("hp_trials/best_params.hyperopt", "rb"))

# print current best_params
best_params
```
