### ISSUE TITLE
hp.choice samples outside of bounds

### ISSUE THREAD

**Issue by arsmirnov95** [hyperopt/hyperopt#576]
Hello! I am trying to tune LightGBM and XGBoost using Hyperopt. When I sample for `max_depth`, I use: `'max_depth': hp.choice('max_depth', np.arange(1, 30, dtype=int))`.
The problem is that when I check the trials array, I see that there were trials with `'max_depth':[0]`. However, if I generate many samples from hp.choice itself and without algorithm optimization, it samples inside bounds. What can it be attributed to?
This is my code:
```
def objective(params):
    gbm = lgb.train(params,lgb_train, valid_sets=lgb_eval,  early_stopping_rounds=50)
    return mean_squared_error(gbm.predict(input_eval), output_eval)
# Define the search space
space = {'objective':'regression',
         'num_iterations': 10000,
         'metric': {'l1','l2'},
         'boosting_type':'gbdt', 
         'max_depth': hp.choice('max_depth', np.arange(1, 30, dtype=int)),
         'learning_rate': hp.loguniform('learning_rate', np.log(0.01), np.log(0.2)),
         'reg_alpha': hp.uniform('reg_alpha', 0.0, 1.0),
         'reg_lambda': hp.uniform('reg_lambda', 0.0, 1.0),
         'min_data_in_leaf': hp.choice('min_data_in_leaf', np.arange(10, 1000, dtype=int)),
         'colsample_bytree': hp.uniform('colsample_by_tree', 0.8, 1.0)         
}

from hyperopt import tpe

tpe_algorithm = tpe.suggest

from hyperopt import Trials
# Trials object to track progress
bayes_trials = Trials()

from hyperopt import fmin
MAX_EVALS = 1000
# Optimize
best = fmin(fn = objective, space = space, algo = tpe.suggest, max_evals = MAX_EVALS, trials = bayes_trials)
```
What can cause such a bug? Also, MSE values are inconsistent with grid search...

**Comment by bjkomer** [comment]
When using `hp.choice` the output stored in the trials array is the index of the value chosen. It is done this way because in general the options in choice can be complex and can themselves be entirely different search spaces.

In your case `'max_depth':[0]` would correspond to a max_depth of 1

**Comment by arsmirnov95** [comment]
> When using `hp.choice` the output stored in the trials array is the index of the value chosen.
> ```

That is somewhat strange, because I look at `[t['misc']['vals']for t in bayes_trials.trials]` and all other values are not indices but numeric values (e.g., 
```
{'colsample_by_tree': [0.8872318195751376],
  'learning_rate': [0.029201538278802685],
  'max_depth': [7],
  'min_data_in_leaf': [652],
  'reg_alpha': [0.12409416879187152],
  'reg_lambda': [0.015656562877646274]}
```
So I guess it is really only `hp.choice` that gives indices as output, other functions like `hp.loguniform, hp.uniform, hp.quniform` don't have this issue.

Many thanks!
