### ISSUE TITLE
Progress monitoring with Callback

### ISSUE THREAD

**Issue by PhilipMay** [hyperopt/hyperopt#585]
This is an idea build on @easyas314159 suggested here: #476 

I suppose this potentially leads into a broader discussion about progress monitoring of the optimization process. For example, there is currently no easy way to cancel the optimization process without access to the `Trials` object, or a mechanism for monitoring no improvement in a while, or even monitoring losses outside the main objective. A more robust callback system in general with hooks into various steps of the optimization process would be extremely useful.

Something kind of like this comes to mind:
```python
class Callback:
	def on_optimization_start(self, trials):
		...

	def on_optimization_end(self, trials):
		...

	def on_trial_start(self, trials, trial):
		...

	def on_trial_end(self, trials, trial):
		...
```

I can think of a handful of things this could be used for:
- Early stopping when there is insufficient improvement
- Early stopping when a threshold is passed
- Monitoring other properties of the trial object that are not the loss
- Custom progress monitoring that sends status information via HTTP to another service
- Custom progress bars with options for more than just a `best loss: %f` postfix

I can technically do all of that myself but it requires calling `fmin` for a single iteration and handling all externally which is not a great option in a distributed context.

This should probably be opened as a separate issue/enhancement? I also don't mind taking the development of this on but it will have to wait until later this month.

**Comment by PhilipMay** [comment]
An additional feature would be to stop optimization after a given time.

**Comment by Anto95** [comment]
This would be useful also to test the obtained configuration on the objective function with an unseen set of data.
