### ISSUE TITLE
uniformint should be added to wiki

### ISSUE THREAD

**Issue by PhilipMay** [hyperopt/hyperopt#586]
`hp.uniformint`function description should be added to wiki at this place:
https://github.com/hyperopt/hyperopt/wiki/FMin#21-parameter-expressions

**Comment by maxpumperla** [comment]
@PhilipMay thanks for noticing. As I mentioned in the other issue, please have a look at our autogen docs in the `docs` folder. I'm not sure I properly ported this FMin section to the new docs yet.

**Comment by marctorrellas** [comment]
@PhilipMay you're more than welcome to contribute with a PR to update this. I think the file is `docs/templates/getting-started/search_spaces.md`
