### ISSUE TITLE
Python script install failed

### ISSUE THREAD

**Issue by manoredd** [hyperopt/hyperopt#587]
# python test.py install
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    from hyper import HTTP20Connection
ImportError: No module named hyper

# python --version
Python 2.7.5

unable to install # pip install future
Collecting future
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9380da4e50>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/future/

**Comment by marctorrellas** [comment]
not sure what you were trying to do. is this `test.py` yours?

**Comment by manoredd** [comment]
Yes, py is my private.
the same script in another machine its working, only in my machine not working.

**Comment by maxpumperla** [comment]
@manoredd "my own private install script doesn't work on my machine" is very difficult to see as a hyperopt issue, unless you share your `test.py`. How do you expect us to debug this? From the error message above it seems like you're trying to import `hyper`, which probably isn't a thing.

**Comment by manoredd** [comment]
> @manoredd "my own private install script doesn't work on my machine" is very difficult to see as a hyperopt issue, unless you share your `test.py`. How do you expect us to debug this? From the error message above it seems like you're trying to import `hyper`, which probably isn't a thing.

[Test.txt](https://github.com/hyperopt/hyperopt/files/3969340/Test.txt)

as py file cannot upload renamed to .txt.

**Comment by marctorrellas** [comment]
well, "ImportError: No module named hyper", doesn't seem related to hyperopt

**Comment by manoredd** [comment]
> well, "ImportError: No module named hyper", doesn't seem related to hyperopt

what could be the reason then getting hyper error.

**Comment by marctorrellas** [comment]
you need to install this package https://hyper.readthedocs.io/en/latest/, not related with hyperopt

it's quite an old package actually, but if you're in Python2 I guess it's fine

**Comment by marctorrellas** [comment]
if this solves the issue, please close it

**Comment by manoredd** [comment]
Thanks its worked
