### ISSUE TITLE
Search number definition: max_evals or confidence

### ISSUE THREAD

**Issue by weixingsun** [hyperopt/hyperopt#591]
Dear experts,

Thanks for making this tool available, I can search for some simple questions
But a simple question come to my mind, if the algorithm is Bayesian, why there is no such a parameter called confidence_ratio, instead of the current max_evals (just a rough number from guess)

I would see confidence may be useful for some strictly limited search space, because if I have only 2 parameters, and only 2 options for each, the maximum attempt number is 4, so setting max_evals>4 is meaningless. 

Just very new to this tool, please correct me if there is any other definitions or workarounds
Thanks a lot

**Comment by marctorrellas** [comment]
Hey @weixingsun 

I think I agree with you if by confidence you mean a max value for the loss. In the first version of hyperopt, the loss was minimised but the only criteria was max_evals. Recently, a timeout was added. However, assuming you have unlimited time and you have an upper bound for the loss (e.g. you know the loss can go as low as 1e-4), then it could make sense to set a threshold for fmin to stop (e.g. 1e-3), irrespectively on max_evals

Look at this PR for the contribution about timeout https://github.com/hyperopt/hyperopt/pull/533

It's not a difficult task, so I encourage you to work on it and happy to review :)

**Comment by weixingsun** [comment]
Hi @marctorrellas thanks for letting me know the context, I do working on this PR now, please help to review it. But I don't know how to deal with it when someone want to change the loss function.

**Comment by marctorrellas** [comment]
please close this issue now that is solved :)
