### ISSUE TITLE
Minimum Spark Version?

### ISSUE THREAD

**Issue by davidcereal** [hyperopt/hyperopt#594]
What is the lowest Spark version compatible with running Hyperopt in parallel on Spark? Currently there is no place in the documentation (that I could find). My EMR cluster runs Spark 2.3.2.

**Comment by maxpumperla** [comment]
@jkbradley did you test this on your end? I'd be curious to learn more about this as well.

**Comment by jkbradley** [comment]
We didn't test it on earlier version; we only tested on 2.4 and some 3.0 snapshots.  I *think* it would work on 2.3.x at least...famous last words :)

**Comment by davidcereal** [comment]
Running on 2.3.2 in pyspark shell locally, I get:
```
>>> spark_trials = SparkTrials(spark_session=spark)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dberger/.pyenv/versions/classification_gdp/lib/python3.5/site-packages/hyperopt/spark.py", line 82, in __init__
    max_num_concurrent_tasks = self._spark_context._jsc.sc().maxNumConcurrentTasks()
  File "/Applications/spark-2.3.2-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/Applications/spark-2.3.2-bin-hadoop2.7/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/Applications/spark-2.3.2-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 332, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling o35.maxNumConcurrentTasks. Trace:
py4j.Py4JException: Method maxNumConcurrentTasks([]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:274)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jkbradley** [comment]
Ah, rats, you're right; that method was added in 2.4.  It might be possible to fix that, but that method makes it a lot easier to find the correct limit for concurrent tasks.

**Comment by marctorrellas** [comment]
btw, the spark tests are not very deterministic. It'd be great if you could review them, as almost every time I open a PR I have to close/reopen PR some times until they pass...

**Comment by jkbradley** [comment]
Oh, I haven't seen that :/  I see that now in the build history.  I just made https://github.com/hyperopt/hyperopt/issues/598 to track this.

**Comment by hamta** [comment]
> @jkbradley, running on 2.3.2 in pyspark shell locally, I get the error below. Running on 2.4.4 in same manner, it runs fine.
> 
> ```
> >>> spark_trials = SparkTrials(spark_session=spark)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/dberger/.pyenv/versions/classification_gdp/lib/python3.5/site-packages/hyperopt/spark.py", line 82, in __init__
>     max_num_concurrent_tasks = self._spark_context._jsc.sc().maxNumConcurrentTasks()
>   File "/Applications/spark-2.3.2-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
>   File "/Applications/spark-2.3.2-bin-hadoop2.7/python/pyspark/sql/utils.py", line 63, in deco
>     return f(*a, **kw)
>   File "/Applications/spark-2.3.2-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 332, in get_return_value
> py4j.protocol.Py4JError: An error occurred while calling o35.maxNumConcurrentTasks. Trace:
> py4j.Py4JException: Method maxNumConcurrentTasks([]) does not exist
> 	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
> 	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
> 	at py4j.Gateway.invoke(Gateway.java:274)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:238)
> 	at java.lang.Thread.run(Thread.java:748)
> ```

Hello. 
I got the same error with running on spark-3.1.1
Do you know how can I fix it?
