### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'randint' in Hyperopt classifier

### ISSUE THREAD

**Issue by bendiste** [hyperopt/hyperopt#596]
I am trying to use Hyperopt to find the best learner for my dataset on Google Colab. The dataset contains both categorical and numerical values but all of them are encoded successfully. While searching for the optimal classifier, I also wanted to get cross-validation scores, which is built-in functionality in hyperopt. However, when I tried to run my code, I got the following error:

> AttributeError: 'NoneType' object has no attribute 'randint'

I could not solve the issue alone, it is related to an attribute defined in the randint fuction defined in stochastic.py. My code and the output are below:

`from sklearn.model_selection import KFold, cross_val_score
from hpsklearn import HyperoptEstimator, any_classifier
from sklearn.model_selection import train_test_split
from hyperopt import tpe, hp, fmin, Trials
import numpy as np
type(aust_predictors)
X_train, X_test, y_train, y_test = train_test_split(aust_predictors, df_aust.target, train_size = 0.75, test_size = 0.25)
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()
estim = HyperoptEstimator(classifier=any_classifier('clf'), algo = tpe.suggest, trial_timeout=150)
estim.fit(X_train, y_train)

print(estim.score(X_test, y_test))
print(estim.best_model())

cv_sc = cross_val_score(estim, X_test, y_test, cv = 10, n_jobs=-1).mean()
print(cv_sc)`

Output:

`100%|██████████| 1/1 [00:00<00:00,  4.48it/s, best loss: 0.375]
100%|██████████| 1/1 [00:00<00:00, 11.45it/s, best loss: 0.375]
100%|██████████| 1/1 [00:00<00:00,  2.03it/s, best loss: 0.1923076923076923]
100%|██████████| 1/1 [00:00<00:00,  8.65it/s, best loss: 0.15384615384615385]
100%|██████████| 1/1 [00:00<00:00,  3.21it/s, best loss: 0.15384615384615385]
100%|██████████| 1/1 [00:00<00:00,  9.92it/s, best loss: 0.15384615384615385]
100%|██████████| 1/1 [00:00<00:00,  5.55it/s, best loss: 0.10576923076923073]
100%|██████████| 1/1 [00:04<00:00,  4.64s/it, best loss: 0.10576923076923073]
100%|██████████| 1/1 [00:00<00:00,  2.11it/s, best loss: 0.10576923076923073]
100%|██████████| 1/1 [00:00<00:00,  8.23it/s, best loss: 0.10576923076923073]
0.8728323699421965
{'learner': GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.033985711476027795, loss='deviance',
                           max_depth=4, max_features='sqrt',
                           max_leaf_nodes=None, min_impurity_decrease=0.0,
                           min_impurity_split=None, min_samples_leaf=8,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=109, n_iter_no_change=None,
                           presort='auto', random_state=1,
                           subsample=0.7700933910547965, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False), 'preprocs': (StandardScaler(copy=True, with_mean=False, with_std=False),), 'ex_preprocs': ()}
---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
    796             try:
--> 797                 tasks = self._ready_batches.get(block=False)
    798             except queue.Empty:

16 frames
/usr/lib/python3.6/queue.py in get(self, block, timeout)
    160                 if not self._qsize():
--> 161                     raise Empty
    162             elif timeout is None:

Empty: 

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-12-90d85434dc35> in <module>()
      5 print(estim.best_model())
      6 
----> 7 cv_sc = cross_val_score(estim, X_test, y_test, cv = 10, n_jobs=-1).mean()
      8 print(cv_sc)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py in cross_val_score(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, error_score)
    389                                 fit_params=fit_params,
    390                                 pre_dispatch=pre_dispatch,
--> 391                                 error_score=error_score)
    392     return cv_results['test_score']
    393 

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    230             return_times=True, return_estimator=return_estimator,
    231             error_score=error_score)
--> 232         for train, test in cv.split(X, y, groups))
    233 
    234     zipped_scores = list(zip(*scores))

/usr/local/lib/python3.6/dist-packages/joblib/parallel.py in __call__(self, iterable)
   1002             # remaining jobs.
   1003             self._iterating = False
-> 1004             if self.dispatch_one_batch(iterator):
   1005                 self._iterating = self._original_iterator is not None
   1006 

/usr/local/lib/python3.6/dist-packages/joblib/parallel.py in dispatch_one_batch(self, iterator)
    806                 big_batch_size = batch_size * n_jobs
    807 
--> 808                 islice = list(itertools.islice(iterator, big_batch_size))
    809                 if len(islice) == 0:
    810                     return False

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py in <genexpr>(.0)
    230             return_times=True, return_estimator=return_estimator,
    231             error_score=error_score)
--> 232         for train, test in cv.split(X, y, groups))
    233 
    234     zipped_scores = list(zip(*scores))

/usr/local/lib/python3.6/dist-packages/sklearn/base.py in clone(estimator, safe)
     63     for name, param in new_object_params.items():
     64         new_object_params[name] = clone(param, safe=False)
---> 65     new_object = klass(**new_object_params)
     66     params_set = new_object.get_params(deep=False)
     67 

/usr/local/lib/python3.6/dist-packages/hpsklearn/estimator.py in __init__(self, preprocessing, ex_preprocs, classifier, regressor, space, algo, max_evals, loss_fn, verbose, trial_timeout, fit_increment, fit_increment_dump_filename, seed, use_partial_fit)
    534             # self.space = hyperopt.pyll.as_apply(space)
    535             self.space = space
--> 536             evaled_space = space.eval()
    537             if 'ex_preprocs' in evaled_space:
    538                 self.n_ex_pps = len(evaled_space['ex_preprocs'])

/usr/local/lib/python3.6/dist-packages/hyperopt/pyll/base.py in eval(self, memo)
    290         else:
    291             args = [a.eval() for a in self.pos_args]
--> 292             kwargs = dict([(n, a.eval()) for (n, a) in self.named_args])
    293             f = scope._impls[self.name]
    294             memo[id(self)] = rval = f(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/hyperopt/pyll/base.py in <listcomp>(.0)
    290         else:
    291             args = [a.eval() for a in self.pos_args]
--> 292             kwargs = dict([(n, a.eval()) for (n, a) in self.named_args])
    293             f = scope._impls[self.name]
    294             memo[id(self)] = rval = f(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/hyperopt/pyll/base.py in eval(self, memo)
    289             return memo[id(self)]
    290         else:
--> 291             args = [a.eval() for a in self.pos_args]
    292             kwargs = dict([(n, a.eval()) for (n, a) in self.named_args])
    293             f = scope._impls[self.name]

/usr/local/lib/python3.6/dist-packages/hyperopt/pyll/base.py in <listcomp>(.0)
    289             return memo[id(self)]
    290         else:
--> 291             args = [a.eval() for a in self.pos_args]
    292             kwargs = dict([(n, a.eval()) for (n, a) in self.named_args])
    293             f = scope._impls[self.name]

/usr/local/lib/python3.6/dist-packages/hyperopt/pyll/base.py in eval(self, memo)
    289             return memo[id(self)]
    290         else:
--> 291             args = [a.eval() for a in self.pos_args]
    292             kwargs = dict([(n, a.eval()) for (n, a) in self.named_args])
    293             f = scope._impls[self.name]

/usr/local/lib/python3.6/dist-packages/hyperopt/pyll/base.py in <listcomp>(.0)
    289             return memo[id(self)]
    290         else:
--> 291             args = [a.eval() for a in self.pos_args]
    292             kwargs = dict([(n, a.eval()) for (n, a) in self.named_args])
    293             f = scope._impls[self.name]

/usr/local/lib/python3.6/dist-packages/hyperopt/pyll/base.py in eval(self, memo)
    292             kwargs = dict([(n, a.eval()) for (n, a) in self.named_args])
    293             f = scope._impls[self.name]
--> 294             memo[id(self)] = rval = f(*args, **kwargs)
    295             return rval
    296 

/usr/local/lib/python3.6/dist-packages/hyperopt/pyll/stochastic.py in randint(upper, rng, size)
    104             assert len(upper) == size[0]
    105             return np.asarray([rng.randint(uu) for uu in upper])
--> 106     return rng.randint(upper, size=size)
    107 
    108 

AttributeError: 'NoneType' object has no attribute 'randint'`

**Comment by alexdavis24** [comment]
Has there been any update on this? I am also receiving a similar error using Sklearn's DecisionTreeClassifier on attribute 'Splitter'.

**Comment by mandjevant** [comment]
@alexdavis24 Try using sklearn version 0.24.1 `pip install scikit-learn==0.24.1`
Hyperopt-sklearn is not yet compatible with the newer sklearn versions.  
  
  
@bendiste I can not replicate your error. 
Ensure you install hyperopt-sklearn by `pip install git+https://github.com/hyperopt/hyperopt-sklearn.git`

Additionally, there is an error in your code. At `cv_sc = cross_val_score(estim, X_test, y_test, cv=10, n_jobs=-1).mean()`.

This will not work since the estim you defined is a Hyperopt estimator with any_classifier as parameter not an sklearn estimator. 
Instead, implement the best estimator (derived from your hyperopt output) as you normally would with sklearn. Then use that estimator as a parameter in the `cross_val_score` function.
