### ISSUE TITLE
Flaky Spark tests

### ISSUE THREAD

**Issue by jkbradley** [hyperopt/hyperopt#598]
@marctorrellas reported some flakiness with Spark tests.  Looking at recent master tests, I see 2 main issues:

(1) The most common failure is:
```
======================================================================
FAIL: test_task_maxFailures_warning (hyperopt.tests.test_spark.FMinTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/hyperopt/hyperopt/hyperopt/tests/test_spark.py", line 657, in test_task_maxFailures_warning
    log_output=log_output
AssertionError: 'spark.task.maxFailures' not found in "trial task 0 started\ntrial task 0 succeeded, result is {'status': 'ok', 'loss': 1.0}\ntrial 0 task thread exits normally and writes results back correctly.\nfmin thread exits normally.\ndispatcher thread exits normally.\nTotal Trials: 1: 1 succeeded, 0 failed, 0 cancelled." :  "spark.task.maxFailures" warning missing from log: 
                    trial task 0 started
trial task 0 succeeded, result is {'status': 'ok', 'loss': 1.0}
trial 0 task thread exits normally and writes results back correctly.
fmin thread exits normally.
dispatcher thread exits normally.
```
E.g.: https://travis-ci.org/hyperopt/hyperopt/jobs/633229910

(2) I saw 1 instance of:
```
FAIL: test_timeout_without_job_cancellation_fmin_timeout (hyperopt.tests.test_spark.FMinTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/hyperopt/hyperopt/hyperopt/tests/test_spark.py", line 479, in test_timeout_without_job_cancellation_fmin_timeout
    self.assertTrue(spark_trials._fmin_cancelled)
AssertionError: False is not true
```
E.g.: https://travis-ci.org/hyperopt/hyperopt/jobs/630275160

This issue is for fixing these instances of flakiness.  (Please add other Spark-related ones if you see any.)

**Comment by marctorrellas** [comment]
some other spark-related things (but if you fix the tests would already be great):

- fmin shows a warning in Pycharm: Signature of method 'SparkTrials.fmin()' does not match signature of base method in class 'Trials' less... 
- some missing docstrings and probably outdated -->

    def wait_for_all_threads(self):
        """
        Wait for the dispatcher and worker threads to finish.
        :param cancel_running_trials: If true, try to cancel all running trials.
        """

when there is no parameter cancel_running_trials ?

Thanks!
