### ISSUE TITLE
TLS Support for MongoDB

### ISSUE THREAD

**Issue by tomberek** [hyperopt/hyperopt#599]
The MongoClient call does not forward kwargs:

https://github.com/hyperopt/hyperopt/blob/c903de979e50f844130dcc08107038f95e87a061/hyperopt/mongoexp.py#L277

Might be ideal to just forward the uri string directly rather than trying to parse it and pass it piece by piece.

**Comment by maxpumperla** [comment]
@tomberek very good point, thanks for reporting

**Comment by michaelmior** [comment]
Using `mongo+ssh` or `ssh+mongo` as the protocol in the URI should work.
