### ISSUE TITLE
How to get categorical hyperparameter back from optimizer output

### ISSUE THREAD

**Issue by consti-91** [hyperopt/hyperopt#604]
Hey,

I wrote an objective function for a SARIMAX model, because I want to find the model with the best hyperparameters and the best external regressors in one combined step. The objective function takes several integer variables and one categorical variable as an input and returns the loss of a given configuration.

```
# categorical variable (in reality much more regressor combinations)
regressor_combinations = [["regressor1"], ["regressor2"], ["regressor1", "regressor2"]]

```
```
# search space:
search_space_sarimax = {
                        'p': hp.randint('p', 4),
                        'd': hp.randint('d', 2),
                        'q': hp.randint('q', 4),
                        'P': hp.randint('P', 2),
                        'D': hp.randint('D', 2),
                        'Q': hp.randint('Q', 2),
                        's': hp.choice('s', [3, 12]),
                        'regressors' : hp.choice('regressors', regressor_combinations)
                        }  

```
```
# objective function
def objective(search_space_sarimax):
        
        p = search_space_sarimax['p']
        d = search_space_sarimax['d']
        q = search_space_sarimax['q']
        P = search_space_sarimax['P']
        D = search_space_sarimax['D']
        Q = search_space_sarimax['Q']
        s = search_space_sarimax['s']
       regressors = search_space_sarimax['regressors']
      
       # ...create model with hyperparameters and regressors and return loss...
```

If I run hyperopt, I don't receive the names of the regressors that have been chosen but a number:

```
Out[3]: 
{'D': 1,
 'P': 0,
 'Q': 0,
 'd': 1,
 'regressors': 2,
 'p': 2,
 'q': 1,
 's': 0}
```

Is that a bug or am I missing something crucial here? In the obective function, the SARIMAX model takes a list of regressors as a model input, so this shouldn't be the problem.

Thanks in advance!

**Comment by bjkomer** [comment]
When a parameter is defined by `hp.choice` by default the output of `fmin` will contain the indices of the best setting chosen. You can use the `space_eval` function on this output to convert it to what you are expecting. Another option is to set `return_argmin=False` in the `fmin` function and it will call `space_eval` automatically on the output before returning it.

This is a common issue people run into, I feel like the default behaviour should be flipped...

**Comment by consti-91** [comment]
Thanks a lot, now it is working perfectly!

**Comment by ihadanny** [comment]
thanks, how do I get the same from the trials object?
```python
t = my_trials.trials[0]
space_eval(ctb_para, t['misc']['vals'])
```
throws a `int() argument must be a string, a bytes-like object or a number, not 'list'` :(

**Comment by bjkomer** [comment]
@ihadanny you need to do a little more work to extract it from a trials object. See #572 for some methods of doing this.

**Comment by ihadanny** [comment]
thanks! but weird that it's not a part of the framework, don't you agree? something like:

```python
df = []
for t in my_trials.trials:
    hyp = space_eval(ctb_para, {key:val[0] for key, val in t['misc']['vals'].items()})['reg_params']
    hyp['loss'] = t['result']['loss']    
    df.append(hyp)
df = pd.DataFrame(df)    
```
