### ISSUE TITLE
Loss set to infinite if STATUS_FAIL?

### ISSUE THREAD

**Issue by MilesCranmer** [hyperopt/hyperopt#609]
Hi,

I just wanted to check: if I set loss=0, but status='STATUS_FAIL', tpe.suggest will treat the loss as infinite for that point right? Or will it only work if I also set loss=None?

https://github.com/hyperopt/hyperopt/blob/40bd617a0ca47e09368fb65919464ba0bfa85962/hyperopt/tpe.py#L884

Thanks!
Miles

**Comment by michaelmior** [comment]
The loss value is not used at all if status is `STATUS_FAIL`. So whatever the loss value is, it will be ignored.
