### ISSUE TITLE
Update networkx requirement to >=2.2

### ISSUE THREAD

**Issue by optroodt** [hyperopt/hyperopt#614]
`networkx` was pinned to version 2.2 because of Python 2.7 build issues (https://github.com/hyperopt/hyperopt/pull/506). Python 2.7 is now EOL and PyPI does not contain `networkx` versions greater than 2.2 for Python 2.7.

Version 2.2 is ~1.5 years old and people using Python 3.x (me) will probably want a newer version because of version conflicts with more modern packages (e.g. [dbt](https://github.com/fishtown-analytics/dbt)).

Thus, can the requirement for networkx become `networkx>=2.2` in order to satisfy both Python 2.7 and Python 3.x users?

**Comment by thomasburgess** [comment]
Bump.

**Comment by maxpumperla** [comment]
@optroodt sure, please send a PR

**Comment by optroodt** [comment]
There you go! :)

**Comment by kenbr7613** [comment]
When will this change be released to pypi?

**Comment by michaelmior** [comment]
Closing since this has fixed and released.
