### ISSUE TITLE
IndexError: list index out of range in rec_eval

### ISSUE THREAD

**Issue by FRUEHNI1** [hyperopt/hyperopt#615]
I am using hyperopt to (manually) generate the next set of hyperparameters to run my own parallel evaluation on them. The algorithm works fine in the beginning, but at one point (at least for more complex spaces!) breaks.

This is the "evaluation" set-up.

```python

# slightly modified code

searchspace = hp.choice(...)

domain = Domain(fn=lambda _: _, expr=searchspace)

N = 10
trials = Trials()
new_ids = trials.new_trial_ids(N)

new_trials = suggest_algo(
            new_ids,
            domain,
            trials,
            np.random.randint(2 ** 31 - 1),
)

trials.insert_trial_docs(new_trials)
trials.refresh()

def _evaluate(self, config, ctrl):
        memo =domain.memo_from_config(config)
        use_obj_for_literal_in_memo(domain.expr, ctrl, Ctrl, memo)
        pyll_rval = pyll.rec_eval(domain.expr, memo=memo)
        return pyll_rval

new_params = []
for tid in new_ids:
            current_trial = trials.trials[tid]
            current_trial["state"] = base.JOB_STATE_RUNNING
            current_trial["book_time"] = now
            current_trial["refresh_time"] = now
            # convert the suggested misc IDs back to their original value
            random_params_spec = base.spec_from_misc(current_trial["misc"])
            ctrl = base.Ctrl(trials, current_trial=current_trial)
            random_params = _evaluate(random_params_spec, ctrl)
            new_params.append(random_params)

# evaluate random_params in parallel ...
scores = ...

# enter the infos into trials objects

for tid, loss in zip(new_ids, scores):
            current_trial = trials.trials[tid]
            current_trial["state"] = base.JOB_STATE_DONE
            current_trial["result"] = {
                "loss": loss,
                "status": "ok",
                "info": 2,
            }
            current_trial["refresh_time"] = now

trials.refresh()

# save trials to file
```

However, if I want to continue using these existing trials objects (i.e. loading the pickled trials object), this is what happens:

pyll_rval = pyll.rec_eval(self.domain.expr, memo=memo)
  File "/opt/pyenv/versions/analytics-venv/lib/python3.7/site-packages/hyperopt/pyll/base.py", line 875, in rec_eval
    rval_var = node.pos_args[int(switch_i) + 1]
IndexError: list index out of range

Under the hood, these are the nodes etc involved (simplified):

Switch node:

```
0 switch
1   hyperopt_param
2     Literal{decide_ws.main[1],complex[0]}
3     randint
4       Literal{2}
5   dict
6    A = 1
7   dict
8    A = 2

node.pos_args: [<hyperopt.pyll.base.Apply object at 0x7f9de889d9e8>, <hyperopt.pyll.base.Apply object at 0x7f9e0dfc45f8>, <hyperopt.pyll.base.Apply object at 0x7f9e0dfc4940>]
```

The main cause now is that the first apply is evaluated to int(2). This shouldn't be, as randint(2) may ONLY return 0,1, never 2. Because it is 2, the code attempts to add 1, so we try to use node.pos_args[3] which of course fails. I am now stuck, as I have no idea what could possibly cause the first apply object to evaluate to 2 - maybe a non-unique naming? It also seems to be that this problem does only occur when using ATPE instead of TPE.

**Comment by FRUEHNI1** [comment]
FYI: Trying whether deepcopy_inputs solves the problem.

**Comment by magdapoppins** [comment]
I am also occasionally getting the same issue when calling randint_via_categorical_lpdf(sample, p) via rec_eval(). In my case sample will contain values like 259, although the length of p[0] is only 131. (In hyperopt/tpe.py line 72.) Would be happy to share more details if needed.

**Comment by ekerazha** [comment]
I've the same issue.

**Comment by ekerazha** [comment]
Duplicate? https://github.com/hyperopt/hyperopt/issues/565
