### ISSUE TITLE
randint(low=100, high=10000) returns a number lower than 100

### ISSUE THREAD

**Issue by gcoter** [hyperopt/hyperopt#616]
Hello,

In one project, I use `hyperopt` to optimize the number of neurons in a layer. To do so, I use `randint` to sample random integers between 100 and 10000. If I run the optimization for long enough, my program will run into a `ValueError` from this line : https://github.com/hyperopt/hyperopt/blob/410d4e4488bb0e5ae51ccc8b0825930d42741b37/hyperopt/pyll/base.py#L1060
Unfortunately, it is not easy to reproduce. The only way I found was to sample many times until the `ValueError` is raised.

After some debugging, I found out that the problem was that one sampled value was lower than 100. For instance, here is the list of the sampled values:
```
[9565, 7669, 228, 4153, 1148, 6043, 5428, 2310, 2255, 9140, 3583, 6525, 4917, 7995, 9211, 3366, 8037, 2193, 2437, 1443, 2018, 4788, 5115, 393, 6408, 4924, 850, 4366, 9767, 5216, 7641, 7858, 6794, 9658, 9292, 9165, 175, 2395, 2031, 6891, 9811, 7682, 8506, 4308, 7604, 6262, 4650, 4308, 5829, 4135, 5728, 4140, 5445, 5283, 9183, 855, 6279, 8169, 4961, 9322, 1100, 1129, 2310, 697, 8054, 1]
```

As you can see, the very last value is 1. And because `offset` is 100 in this case, `y - offset` will contain one negative value (-99) which causes a `ValueError` from `bincount`.
> ValueError: If the input is not 1-dimensional, or contains elements with negative values, or if minlength is negative.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.bincount.html#numpy.bincount

Here are some info about my environment:
- Docker version 19.03.5, build 633a0ea
- Ubuntu 16.04 as a Docker container (base image: nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04)
- Python 3.6.8
- pip 19.0.1
- hyperopt 0.2.3

**Comment by prateeksingh0001** [comment]
@gcoter were you able to resolve this issue? I am facing a similar issue while using hyperopt

**Comment by gcoter** [comment]
Hi @prateeksingh0001, no I have not solved this issue, meanwhile I have moved to other projects, sorry
