### ISSUE TITLE
Tuning variable-length arrays

### ISSUE THREAD

**Issue by Yura52** [hyperopt/hyperopt#622]
Hi! My goal is to tune the number of layers for my neural network. Additionally, for each of the layers I want to tune the number of units. In other words, I want to tune the size of some array and its content at the same time. I have several related questions.

1. I found many suggestions such as [this](https://github.com/hyperopt/hyperopt/issues/531#issuecomment-525391645) one. The problem with them is `hp.choice` which does not express the nature of the problem correctly, because "the number of layers" is not a categorical variable. Is there a way to achieve the same with `uniformint` so that the result is equivalent to the `create_model` function shown [here](https://optuna.readthedocs.io/en/latest/tutorial/configurations.html#branches-and-loops) (the second snippet)?

2. If I do the following:
```python
a = hp.uniform('first', 16, 32)
b = hp.uniform('second', 16, 32)
hp.choice('layers', [
    [a],  # option 1
    [a, b]  # option 2
])
```
Is it correct in the sense that the subspace represented by the variable `a` is "shared" by both "option 1" and "option 2" and it is tuned consistently regardless of which option is sampled?

3. Is there any difference between `randint('x', 10, 20)` and `uniformint('x', 10, 20)` ?

**Comment by WeirdKeksButtonK** [comment]
I came up with the following solution:

```python
from hyperopt import hp
from hyperopt.pyll.stochastic import sample

def f(values, prefix):
    if not isinstance(values[0], tuple):
        values = list(enumerate(values))
    x = values[0]
    label = f'{prefix}_{x[0]}'
    size = len(values)
    if len(values) == 1:
        return hp.pchoice('optional_' + label, [
            (0.5, [None]),
            (0.5, [hp.randint(label, x[1])])
        ])
    else:
        return hp.pchoice('optional_' + label, [
            (1 / (size + 1), [None]),
            (1 - 1 / (size + 1), [hp.randint(label, x[1]), f(values[1:], prefix)])
        ])
    
    
def unpack(arr):
    if len(arr) == 1:
        if arr[0] is None:
            return []
        else:
            return [arr[0].flatten()[0]]
    else:
        a = [arr[0].flatten()[0]]
        a.extend(unpack(arr[1]))
        return a


print(sample(f([10, 10, 10, 10], 'layer')))
```

Now, the code is correct from the mathematical point of view. However, I would be glad to learn about less complex solutions.

**Comment by ag-tcm** [comment]
> Is it correct in the sense that the subspace represented by the variable a is "shared" by both "option 1" and "option 2" and it is tuned consistently regardless of which option is sampled?

I think the answer is yes, but are you sure that is what you want? I'm trying to do a similar thing and based on my understanding you need to consider whether hyperopt should attribute results from your objective function to a given number of units selected for a layer regardless of the number of layers used. For example

```python
layers_1_unit_1 = hp.uniform('layers_1_unit_1', 16, 32)
layers_2_unit_2 = hp.uniform('layers_2_unit_2', 16, 32)
hp.choice('layers', [
    [layers_1_unit_1],  # option 1
    [layers_1_unit_1, layers_2_unit_2]  # option 2
])
```
is not the same as
```python
layers_1_unit_1 = hp.uniform('layers_1_unit_1', 16, 32)
layers_2_unit_1 = hp.uniform('layers_2_unit_1', 16, 32)
layers_2_unit_2 = hp.uniform('layers_2_unit_2', 16, 32)
hp.choice('layers', [
    [layers_1_unit_1],  # option 1
    [layers_2_unit_1, layers_2_unit_2]  # option 2
])
```
I think the second approach makes more sense. The partial distribution of the objective function result based on the number of units in a single layer neural network will in general differ from the partial distribution of the objective function result based on the number of units in the first layer of a two layer neural network.

**Comment by Yura52** [comment]
> I think the second approach makes more sense. 

Yes, absolutely. It was an intentional and not fully correct simplification from my side in order to reduce the optimization space :)
