### ISSUE TITLE
When is the next Release?

### ISSUE THREAD

**Issue by joonjeong** [hyperopt/hyperopt#623]
Is there any plan to release 0.2.4?

Currently, in pypi version is 0.2.3(not release tagged on github) and it's code is different with master.

Actually, I'd like to use hyperopt with SparkTrials on EMR(AWS) or DataProc(Google Cloud) but SparkTrials not working in Hadoop Cluster.

```
Traceback (most recent call last):
  File "/tmp/hyperopt-cross-validation-ir2a4vfnmp3ro/hpo.py", line 72, in <module>
    if __name__ == "__main__": main()
  File "/tmp/hyperopt-cross-validation-ir2a4vfnmp3ro/hpo.py", line 69, in main
    trials=SparkTrials(spark_session=spark))
  File "/opt/conda/default/lib/python3.6/site-packages/hyperopt/spark.py", line 95, in __init__
    max_num_concurrent_tasks, parallelism
  File "/opt/conda/default/lib/python3.6/site-packages/hyperopt/spark.py", line 121, in _decide_parallelism
    "There are no available spark executors.  "
Exception: There are no available spark executors.  Add workers to your Spark cluster to use SparkTrials.
```

I guess actual executors are allocated when job is submitted but, currently it's broken because of previous version codes.

If this code in master is applied then it works better.

```python
        if max_num_concurrent_tasks == 0:
            logger.warning(
                "The cluster has no executors currently. "
                "The trials won't start until some new executors register."
            )
```

**Comment by maxpumperla** [comment]
check in with @jaberg please, I'm taking a break for now.

**Comment by DLTarasi** [comment]
I am running into the same issue currently. @joonjeong were you able to come up with a workaround? @jaberg is there any plan to release the code currently in master on pypi?

**Comment by Data-drone** [comment]
running into the same issue here @jaberg and update?

**Comment by Data-drone** [comment]
for what it's worth @joonjeong I manually specified the parallelisation inside the SparkTrials and got it working, `trials=SparkTrials(parallelism=2)`

**Comment by maxpumperla** [comment]
I've just created 0.2.4
