### ISSUE TITLE
TPE n_random_jobs on saved trial files

### ISSUE THREAD

**Issue by partiallycomplex** [hyperopt/hyperopt#630]
it seems that loading a saved trial file (ie passing from 100 to 200 max_evals, (increase of 100)) the number of n_startup_jobs (ie 20) refers to the total of the trials performed so far and not to the new 100 trials. This implies that an incremental optimization that reaches up to 1000 trials (using blocks of 100) perform only 20 random trials in the first block of 100. Or maybe something escapes me ..?

Best
g

**Comment by bjkomer** [comment]
Yes, this is true and intended behaviour. The TPE algo looks at the length of the trials object given, and only if it is less than `n_startup_jobs` will it use random instead. The relevant line of code is [here](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/tpe.py#L906).

If you want to periodically run a block of random evaluations, you can alternate between calling `tpe` and `rand` on the same trials object.
