### ISSUE TITLE
 set tpe.suggests parameters n_startup_jobs and n_EI_candidates

### ISSUE THREAD

**Issue by Arktius** [hyperopt/hyperopt#632]
Hi folks,

I'm using the fmin method and I'd like to specify the number of startup jobs (random points) and the number of candidates which tpe suggest at each iteration. I tried to specify them like this:

`best = fmin(fn=ae,
    space=parameterspace,
    algo=tpe.suggest(n_startup_jobs=125,n_EI_candidates=50),
    trials = bayes_trials,    
    max_evals=1000)`

and get the error 

> TypeError: suggest() missing 4 required positional arguments: 'new_ids', 'domain', 'trials', and 'seed'

At the moment, I change them directly in the module tpe at line 792 and 797, but as soon as I'll let my script run on a Kubernetes cluster, I don't want to change code within modules. How can I fix this?

I want to increase both values to a) explore more regions to not get stuck in local minima and b) to get more accurate results.

**Comment by bjkomer** [comment]
The `algo` parameter of fmin is expecting a function, so if you just give those parameters to `tpe.suggest` it will try to evaluate that function before it is passed. There is a bit of a trick to be able to pass in parameters while not evaluating the function and the simplest way is to use `functools.partial`. This is built in to Python and can be thought of as 'partially evaluating a function'

Quick example:

```
from functools import partial
from hyperopt import tpe, fmin

# ...

# this line effectively creates a new function that is the same as tpe.suggest but with some parameter values already set
algo = partial(tpe.suggest, n_startup_jobs=125, n_EI_candidates=50)

# pass in the new `algo` function that you created instead
best = fmin(fn=ae, space=parameterspace, algo=algo, trials=bayes_trials, max_evals=100)
```

**Comment by Arktius** [comment]
Works smoothly 👌 .

Another short question: How can the function ae() return parameters without considering them as 'loss'? I want to log the number of epochs a model was trained (when the callback stopped training).

**Comment by bjkomer** [comment]
Your function will return a dictionary, the only required keys are loss and status, but you can add others as well. See [this](https://github.com/hyperopt/hyperopt/wiki/FMin#13-the-trials-object) part of the docs about the trials object for how to do that. You can then parse your trials object to get that information for each evaluation.

**Comment by Arktius** [comment]
Thanks, you're a great help!
