### ISSUE TITLE
Optimize pyspark mllib model with SparkTrials

### ISSUE THREAD

**Issue by zhuangyanbuaa** [hyperopt/hyperopt#633]
I tried to use hyperopt on databricks environment, and found that there will be error if I optimize a mllib model with SparkTrails.

the error message should be
`py4j.Py4JException: Method __getstate__([]) does not exist`

Right now, these patterns work well
- mllib model + hyperopt(not spark trials)
- sklearn model + hyperopt(spark trials)

Is this a databricks environment problem or hyperopt sparktrail problem?

Thanks

**Comment by ei-grad** [comment]
Faced the same issue, and it seems like it is not possible to use spark context inside the train function :(.

**Comment by allard-jeff** [comment]
Same issue here. This seems a pretty big short coming for Spark and data bricks. Any word on this?

**Comment by Data-drone** [comment]
it says in docu here: http://hyperopt.github.io/hyperopt/scaleout/spark/#sparktrials-api to use the default Trials if you have a mllib model?

**Comment by zhuangyanbuaa** [comment]
@Data-drone 
You are right, thanks!
I didn't read the documentation well.
Here is what the official documentation says: 
`Since SparkTrials fits and evaluates each model on one Spark worker, it is limited to tuning single-machine ML models and workflows, such as scikit-learn or single-machine TensorFlow. For distributed ML algorithms such as Apache Spark MLlib or Horovod, you can use Hyperopt’s default Trials class.`

**Comment by arq-divjyotsingh** [comment]
```
with mlflow.start_run():
    best_result = fmin(
        fn=objective, 
        space=search_space,
        algo=algo,
        trials=SparkTrails(),
        max_evals=150)
```
        
I am getting following error when I set `SparkTrails()` to `fmin` trails arg 
`RuntimeError: It appears that you are attempting to reference SparkContext from a broadcast variable, action, or transformation. SparkContext can only be used on the driver, not in code that it run on workers. For more information, see SPARK-5063.`


However,  setting trails to `hyperopt.Trails()`
`with mlflow.start_run():
    best_result = fmin(
        fn=objective, 
        space=search_space,
        algo=algo,
        trials= Trails(),
        max_evals=150)`
