### ISSUE TITLE
Getting  intermediate  best hyper parameters 

### ISSUE THREAD

**Issue by BattashB** [hyperopt/hyperopt#634]
At the end of the optimization, we are getting the best values
In the Readme example, it after 100 evaluations:
`best = fmin(objective, space, algo=tpe.suggest, max_evals=100)`
Is there an option to return and print intermediate values?
sometimes the optimization can take a few days, so the probability of the run to crash is higher, hence intermediate results can really help, is there any option like this?
Thanks.

**Comment by bjkomer** [comment]
This is definitely possible, the easiest way would be to run `fmin` iteratively in a loop. Something like this:

```python
from hyperopt import fmin, tpe
import pickle  # optional way of saving results

# ...

# Initialize an empty trials database
trials = Trials()

max_evals = 100
step = 1  # how many to run before printing/saving
for i in range(1, max_evals + 1, step):
    best = fmin(objective, space, algo=tpe.suggest, trials=trials, max_evals=i)
    # each step 'best' will be the best trial so far
    print(best)
    # each step 'trials' will be updated to contain every result
    # you can save it to reload later in case of a crash
    pickle.dump(trials, open("my_results.pkl", "wb"))
```

If your machine crashes but the `trials` object is saved, you can reload it and start the loop from `len(trials)+1` to continue where you left off. If it is your objective function that can sometimes cause the crash, you could also just handle the error there and return `STATUS_FAIL` for that run.

**Comment by BattashB** [comment]
Thanks!

**Comment by phyzhenli** [comment]
see #267.
