### ISSUE TITLE
SparkTrials not working for the below code in python and Trials is working

### ISSUE THREAD

**Issue by VinodKumar9576** [hyperopt/hyperopt#651]
`search_space = {'alpha':hp.choice('alpha',[10**x for x in range(-1,2)])
                ,'penalty':hp.choice('penalty',['l1']),
                'loss':hp.choice('loss',['hinge'])
                }
#from hyperopt import Trials
spark_trials = SparkTrials(parallelism=2)

best = fmin(fn=opt_alpha_sgd_para, 
            space=search_space, 
            algo=tpe.suggest, 
            max_evals=16, 
            trials = spark_trials
           #,return_argmin=False
            )`

**This is my objective function:**
`def opt_alpha_sgd_para(search_space):

  clf = SGDClassifier(alpha=search_space['alpha'], penalty=search_space['penalty'],loss=search_space['loss'], random_state=42)
  clf.fit(X_train,Y_train)
  sig_clf = CalibratedClassifierCV(clf, method='sigmoid')
  sig_clf.fit(X_train,Y_train)
  #Predicting Y with test data
  Y_predict = sig_clf.predict_proba(X_test)
  #calculating log-loss
  #no need to store the log error as hyperopt default stores it
  log_error = log_loss(Y_test,Y_predict, labels = clf.classes_, eps = 1e-15)

  #below don't change the 'loss' to anyother as its used by fmin or anyother hyperopt functions.
  return {'loss' : log_error, 'status' : STATUS_OK}`

**Comment by VinodKumar9576** [comment]
To give little details, i'm running above in google colab and giving the error when return_argmin is set to "TRUE" and all the trails are failing. Also when return_argmin made "FALSE" all the trails are failing with no error.
Can anyone help me on it please.

![image](https://user-images.githubusercontent.com/23068132/79039659-73087600-7c00-11ea-8f10-6fb8f830c851.png)

**Comment by VinodKumar9576** [comment]
@bjkomer Can you please check and comment on this as it is bit urgent for as im working for my college project.

Thanks in advance.

If there's something wrong with my code itself, please spare as i started learning ML recently.

**Comment by bjkomer** [comment]
I've never used `SparkTrials` or Spark so I'm not sure how much help I can give. If I understand correctly, you are saying the same code works with regular `Trials` but fails when running with Spark? If you run your objective function using Spark without hyperopt, does it work?

It will be useful to see what error is actually causing your trials to fail. You could try something like wrapping the inside of your objective function in a `try` block and then logging any error that shows up. I think it would work to have an `except:` clause that returns `{'status': STATUS_FAIL, 'exception':e}` and then hopefully `fmin` will return back those failed trials and you can see what went wrong with them.

Looking at the [docs](http://hyperopt.github.io/hyperopt/scaleout/spark/) for SparkTrials, there is a `spark_session` parameter that if not set will look for an existing session. Maybe there is an issue with finding the session? I would also try setting `parallelism` to 1 or None as a sanity check, in case that is related to the issue.

**Comment by VinodKumar9576** [comment]
Thank you @bjkomer . Will try once, the above suggested steps.

**Comment by VinodKumar9576** [comment]
Now the error is different when i try running my objective function with 'status': STATUS_FAIL.
Earlier i ran without any issue with spark session. But now this. Can you @bjkomer help me out.
SpartTrials not finding spark session. And in imported spark beforehand in my notebook.

![image](https://user-images.githubusercontent.com/23068132/79217745-ff1ed580-7e6c-11ea-88ef-d614ce0cd1fd.png)

**Comment by bjkomer** [comment]
Are you sure it was running without a spark issue before? It looks to me like this error was just being hidden. If you don't explicitly catch your errors, hyperopt will automatically do that and just mark the trial as failed and let the rest of your code still run without causing an exception. Does running `from pyspark.sql import SparkSession` work? This is the line that would set the `_have_spark` flag to false if it failed.

I noticed there is a [download_spark_dependencies.sh](https://github.com/hyperopt/hyperopt/blob/master/download_spark_dependencies.sh) script, maybe there is some dependency you are missing that this could help with?

**Comment by Data-drone** [comment]
is it related to https://github.com/hyperopt/hyperopt/issues/623 ?

**Comment by VinodKumar9576** [comment]
@Data-drone issue im facing is different from #623 
Please see the toy example code im trying to get SparkTrials() to work in colab.
and the error im facing.

`jgjh`

**Objective function:**

`
def opt_alpha_sgd_para(search_space):

  clf = SGDClassifier(alpha=search_space['alpha'], penalty=search_space['penalty'],loss=search_space['loss'], random_state=42)
  clf.fit(X_train,Y_train)
  sig_clf = CalibratedClassifierCV(clf, method='sigmoid')
  sig_clf.fit(X_train,Y_train)
  Y_predict = sig_clf.predict_proba(X_test)

  try:
    log_error = log_loss(Y_test,Y_predict, labels = clf.classes_, eps = 1e-15)

  except:
    return {'status': STATUS_OK, 'exception':e}

  return {'loss' : log_error, 'status' : STATUS_OK}`

**Driver code**
`search_space = {'alpha':hp.choice('alpha',[10**x for x in range(-1,2)])
                ,'penalty':hp.choice('penalty',['l2']),
                'loss':hp.choice('loss',['log'])
                }

trials = SparkTrials(parallelism=2)

best = fmin(fn=opt_alpha_sgd_para,
            space=search_space,
            algo=tpe.suggest,
            max_evals=16,
            trials = trials
            )`

**Error**
![image](https://user-images.githubusercontent.com/23068132/79416151-a8301200-7fcc-11ea-9f2f-f94c8a9ac8f7.png)

**Comment by VinodKumar9576** [comment]
Can anyone provide me the working toy example of SparkTrials() usage so that i can try in colab.

**Comment by VinodKumar9576** [comment]
@zoj613 can you check the issue i'm facing. It seems that you faced same issue on #602. And i changed java version to 8 still not working.

**Comment by VinodKumar9576** [comment]
And for your information above code provided is working successfully without any errors in Databricks.

**Comment by VinodKumar9576** [comment]
Well.. Finally found the solution. Issue is with apache spark not installed before and environment variables not got set.
Running below codes solved for me.

`!apt-get install openjdk-8-jdk-headless -qq > /dev/null
#use latest spark version
!wget -q https://www-us.apache.org/dist/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz
!tar xf spark-2.4.5-bin-hadoop2.7.tgz
!pip install -q findspark`

`import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-2.4.5-bin-hadoop2.7"`

`import findspark
findspark.init()
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()`

@bjkomer thanks for your time and suggestions.

**Comment by stb-f5c** [comment]
I had similar issue while tuning XGBoost with hyperopt, SparkTrials does not work on azure databricks, while Trails works

SparkTrials gives me the error _ctypes objects containing pointers cannot be pickled_
