### ISSUE TITLE
hyperopt.__version__ needs update

### ISSUE THREAD

**Issue by liangz1** [hyperopt/hyperopt#657]
https://github.com/hyperopt/hyperopt/blob/1d438e5e96a7cc2a839dd2ca3aeaffc64e144976/hyperopt/__init__.py#L43

**Comment by marctorsoc** [comment]
do you mind doing a quick PR for this @liangz1 ? is there a way to automate this @maxpumperla  to be updated every time we release?

**Comment by maxpumperla** [comment]
@marctorsoc I'm honestly not sure where this is needed anymore. I suspect that `setup.py` was picking up this info at some point. Personally I've never used dunder version this way.

**Comment by marctorsoc** [comment]
it's really weird because the `setup.py` has the correct version https://github.com/hyperopt/hyperopt/blob/55bc17fba8204743a7d3d25f779bd8b2e7db70cd/setup.py#L5

**Comment by maxpumperla** [comment]
yeah, I usually make sure to change both, but forgot last time. The following notes should be adapted, too: https://github.com/hyperopt/hyperopt/blob/410d4e4488bb0e5ae51ccc8b0825930d42741b37/RELEASE.txt

**Comment by marctorsoc** [comment]
Personally, I like this solution https://stackoverflow.com/a/7071358

**Comment by liangz1** [comment]
@marctorsoc Feel free to review the PR ^
