### ISSUE TITLE
Poor treatment of losses with value nan

### ISSUE THREAD

**Issue by GiliR4t1qbit** [hyperopt/hyperopt#662]
Sometimes your loss might end up being nan. It turns out that hyperopt does not handle this well currently. I discovered this since for my algorithm, the first loss is always nan, and the rest are normally not. I noticed conflicting messages, first "TPE using 1/2 trials with best loss 0.000478" but the in the progress bar "best loss: nan". The latter is wrong, the former is right. I've figured out what the issue is - it's a subtle issue related to the way `min()` and `numpy.nan` interact (spoiler alert: never use `min()` if you might encounter a `numpy.nan`). The source of the issue is that the progress bar uses `min(losses)`, which is not safe when `losses` includes `numpy.nan` (see a detailed explanation below).

**Minimal Reproducer**
Here's a minimal reproducer. It's an objective that returns `NaN` as the first loss, and 1 after that:
```
import numpy

def objective(args):
    objective.n += 1
    
    if objective.n == 1:
        return numpy.nan
    else:
        return 1

from hyperopt import hp
space = hp.lognormal('unused', 0, 1)

from hyperopt import fmin, tpe

objective.n = 0
best = fmin(objective, space, algo=tpe.suggest, max_evals=100)

print(best)
```
The output I get is:
```100%|██████████| 100/100 [00:00<00:00, 591.91it/s, best loss: nan]```

If we instead switch the `nan` to occur in the second place by replacing `if objective.n == 1:` with `if objective.n == 2:`, then we get:
```
100%|██████████| 100/100 [00:00<00:00, 388.64it/s, best loss: 1.0]
```
So, the best loss reported is correct. The fact that it matters where the nan occurs is explained below. 

**Why We Should Avoid Using min() with nan**
Let's check what happens when at least one loss has the value `numpy.nan`. Since the expression `min(losses)` occurs in two places in the code, and the expression `np.argmin(losses)` occurs in one place, let's check directly how they react to a `numpy.nan`.

The first thing to note is the very surprising fact that for `min()` it matters _where the nan is_... Let's first try putting a nan value in the first place: 
```
l = [numpy.nan, 0, 1, 2]
min(l)
```
What do you think the result will be? I would have thought it would be `0,` but instead we get `nan`. 

Now let's try moving the nan one up:
```
l = [1, numpy.nan, 0, 2]
min(l)
```
This time we get `0`, the result I would have expected. So, what's happening? **Surely the order of the elements should not matter when using `min()`?!** 

The key bit of information to understand about `min(l)` is that most/all comparisons with `nan` return False. The `min()` function presumably sets the incumbent to the first value initially, and then iterates over the rest of the list. If the current value is lower than the incumbent, then the incumbent is updated. Since that comparison always returns False if the first value is `nan`, the incumbent remains `nan`, and that is what is returned. But when we don’t have a `nan` at the beginning, we’ll get the correct minimum. I find this super non-intuitive, and **would suggest that `min()` should never be used if there's a non-zero probability of `numpy.nan` occuring**.

Running `numpy.argmin()` on the two examples above, returns 0 and 1, respectively, i.e. it identifies the `nan` as being the minimum value. That is also non-intuitive to me, but it's at least consistent, unlike `min()`. However, if the loss is `nan`, surely those configurations/values should be ignored? 

**Proposed Solution**
I'd like to suggest replacing `min(losses)` with `numpy.nanmin(losses)`, which would return the minimum of the losses that are not `nan`. For the case of all losses being `nan`, it issues a `RuntimeWarning` and returns `nan`. One would then also replace `numpy.argmin(losses)` with `numpy.nanargmin(losses)`. Since I'm fairly new to `hyperopt`, I'm wondering if this solution has implications elsewhere?

**Comment by maxpumperla** [comment]
@GiliR4t1qbit this is a very interesting finding! thanks for elaborating on the `min` issue, I frankly wasn't aware of it. I frankly don't see a problem with your proposed solution, let me check!
