### ISSUE TITLE
ATPE RuntimeError: The reset parameter is False but there is no n_features_in_ attribute

### ISSUE THREAD

**Issue by thededlier** [hyperopt/hyperopt#668]
**Version: 0.2.4**
I'm trying to optimise a KNN algorithm using Adaptive TPE. Here's a snippet of the code I'm running
```{python}
KNN_DEFAULT_SPACE = {
    'k': scope.int(hp.quniform('k', 1, 500, 1)),
    'min_k': scope.int(hp.quniform('min_k', 1, 50, 1))
}

def _knn_algo(params):
     # Run KNN with params and crossvalidate to return loss
     return loss

def _objective(params):
    loss = _knn_algo(params)

    return {
        'loss': loss,
        'status': STATUS_OK,
        'hyperparams': params
    }

trials = Trials()

best = fmin(
            objective,
            KNN_DEFAULT_SPACE,
            algo=atpe.suggest,
            max_evals=100,
            trials=trials,
        )
```
The first 10 initialization rounds run fine. However after that I run into this exception

```
 File "/home/rohan/auto-surprise-venv/lib/python3.6/site-packages/hyperopt/fmin.py", line 482, in fmin
    show_progressbar=show_progressbar,
  File "/home/rohan/auto-surprise-venv/lib/python3.6/site-packages/hyperopt/base.py", line 686, in fmin
    show_progressbar=show_progressbar,
  File "/home/rohan/auto-surprise-venv/lib/python3.6/site-packages/hyperopt/fmin.py", line 509, in fmin
    rval.exhaust()
  File "/home/rohan/auto-surprise-venv/lib/python3.6/site-packages/hyperopt/fmin.py", line 330, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/rohan/auto-surprise-venv/lib/python3.6/site-packages/hyperopt/fmin.py", line 266, in run
    new_ids, self.domain, trials, self.rstate.randint(2 ** 31 - 1)
  File "/home/rohan/auto-surprise-venv/lib/python3.6/site-packages/hyperopt/atpe.py", line 1613, in suggest
    hyperparameterConfig, results, currentTrials=[]
  File "/home/rohan/auto-surprise-venv/lib/python3.6/site-packages/hyperopt/atpe.py", line 763, in recommendNextParameters
    transformed = scalingModel.transform([[stats[feature]]])[0][0]
  File "/home/rohan/auto-surprise-venv/lib/python3.6/site-packages/sklearn/preprocessing/_data.py", line 794, in transform
    force_all_finite='allow-nan')
  File "/home/rohan/auto-surprise-venv/lib/python3.6/site-packages/sklearn/base.py", line 436, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/home/rohan/auto-surprise-venv/lib/python3.6/site-packages/sklearn/base.py", line 373, in _check_n_features
    "The reset parameter is False but there is no "
RuntimeError: The reset parameter is False but there is no n_features_in_ attribute. Is this estimator fitted?
```
It seems that the issue arises when transforming the scaling model. Any ideas on the exact reason for this?

Thanks in advance

**Comment by thededlier** [comment]
**Workaround**: I was using scikit-learn version 0.23.0. Going back to version 0.22.0 solved this for me

**Comment by rydevera3** [comment]
@thededlier - I just experienced the exact same thing. When I dove into the debug it was trying to scale a single scalar value. I wasn't able to fix it myself but that was the issue. I will try your workaround.

**Comment by Saibamen** [comment]
FYI: I had this same problem, when using latest `sklearn` version (https://pypi.org/project/sklearn/#history) on Azure App Service.

It works good on Kubernetes in Azure all the time.

BTW: It worked without any problems 2 months ago, even if I used `sklearn` package "from 2015"...

**Comment by sobia-shahid** [comment]
> **Workaround**: I was using scikit-learn version 0.23.0. Going back to version 0.22.0 solved this for me

how we go back to old version?

**Comment by Saibamen** [comment]
`scikit-learn==0.22.2.post1` in your `requirements.txt` file

**Comment by siplabiith** [comment]
Yes, going back to older version has worked for me.

`pip install scikit-learn==0.22.2.post1`

**Comment by giridhar-pamisetty** [comment]
Yes, going back to older version has worked for me.

pip install scikit-learn==0.22.2.post1

**Comment by marctorsoc** [comment]
shouldn't the PR https://github.com/hyperopt/hyperopt/pull/697 solve this issue? why would you like to go back? @sobia-shahid @giridhar-pamisetty

**Comment by diegoseguraes** [comment]
the issue seems to be scikit-learn version 23.0, going back to scikit-lear 22.2 solved the problem for me.. Used this code in Anaconda Command Prompt 
pip install scikit-learn==0.22.2.post1

**Comment by fx-practic** [comment]
Had same problem. Returning to scikit-lear 22.2 solved the problem. Thank you. 
@diegoseguraes thanks for the exact solution!!

**Comment by sumanth13131** [comment]
scikit-learn==0.22.2.post1 works for me

**Comment by madprogramer** [comment]
scikit-learn==0.22 seems to also work, even if it gives a warning. Thank you all for the head's up! 

Does anyone know what's causing this?

**Comment by badyalgaurav** [comment]
There should be a solution with the latest build of Scikit learn.... Because sometimes peoples are working with some functions that are not available in previous, so how to synch in that case?

**Comment by amazingclaude** [comment]
I had the same issue, I was using scikit-learn== 0.23.1, I simply run the code:
scikit-learn==0.22.2.post1 
and everything got solved.

**Comment by badyalgaurav** [comment]
Yeah I also had done the same thing and it works...but what we can do if some methods needs scikit-learn >0.22.2
