### ISSUE TITLE
Hyperopt using Apache Spark  & broadcasted datasets

### ISSUE THREAD

**Issue by easygold** [hyperopt/hyperopt#669]
Dear all,

We are trying to use the hyperopt library ver. 0.2.4 withApache Spark on a Big Data Cluster (Cloudera on premise)
In order to execute the hyperopt library with Apache Spark, we use as suggested the "SparkTrials" function,

example:
	 `trials = SparkTrials(parallelism=2, spark_session=spark)`

and the related "fmin" function, in order to get the best params:

```
best = fmin(fn=lambda params: objective(X_train, y_train, params),
                space=space_params,
                algo=partial(tpe.suggest, n_startup_jobs=n_start),
                max_evals=evals+n_start,
                trials=trials,
                rstate=np.random.RandomState(SEED),
                show_progressbar=False,
                verbose=False)

```

Using the above configuration, the library works fine; 
as next step, in order to improve the performances and avoid multiple calls to the Spark driver (avoid bottleneck problem), we have tried to use broadcasted datasets in the objective/"fn" function, as in the example below:

```
# broadcast dataset with Spark Broadcast
X_train_br = sparkContext.broadcast(X_train)

...

def objective(X_train_br, y_train_br, params):
        '''objective function to minimize with hyperopt'''
        # load broadcasted dataset (python list of lists)
        X_train = X_train_br.value

        ...
```

but the point is that we are not able to load the broadcasted dataset inside the objective/"fn" function. In detail, We are facing with the following issue:

```
File "/tmp/.../conda-env/lib/python3.6/site-packages/hyperopt/fmin.py", line 482, in fmin
    show_progressbar=show_progressbar,
  File "/tmp/.../conda-env/lib/python3.6/site-packages/hyperopt/spark.py", line 270, in fmin
    raise e
  File "/tmp/.../conda-env/lib/python3.6/site-packages/hyperopt/spark.py", line 266, in fmin
    show_progressbar=show_progressbar,
  File "/tmp/.../conda-env/lib/python3.6/site-packages/hyperopt/fmin.py", line 504, in fmin
    show_progressbar=show_progressbar,
  File "/tmp/.../conda-env/lib/python3.6/site-packages/hyperopt/fmin.py", line 152, in __init__
    pickler.loads(msg)
  File "/tmp/.../conda-env/lib/python3.6/site-packages/pyspark/broadcast.py", line 45, in _from_id
    raise Exception("Broadcast variable '%s' not loaded!" % bid)
Exception: Broadcast variable '17' not loaded!
```

From our analysis, the problem seems connected to "pickler" function.
So far, the only "_dirty workaround_" discovered was to download the hyperopt ver. 0.2.3 code and commented the part related to "pickler.loads(msg)" present in "fmin.py" line 152, as shown below: 

```
	        # if self.asynchronous:
	        #     if "FMinIter_Domain" in trials.attachments:
	        #         logger.warning("over-writing old domain trials attachment")
	        #     msg = pickler.dumps(domain)
	        #     # -- sanity check for unpickling
line 152	#     pickler.loads(msg)
        	#     trials.attachments["FMinIter_Domain"] = msg

```
by commenting the above lines, the previous configuration also works with broadcasted data.

My Questions are:
- is there a way to use broadcasted datasets inside the objective/"fn" function?
- is it or it will be supported in the future?

Thanks in advance,

**Comment by felipeeeantunes** [comment]
This notebook suggests how to use the broadcast feature properly and suggest an alternative to datasets with more than 1GB: 
https://docs.databricks.com/_static/notebooks/hyperopt-spark-data.html

**Comment by Isidoro91** [comment]
Hi @felipeeeantunes ,
thank you for your answer.
Yes, I know this databricks notebook and I have also followed it; in particular I'm following the approach "**_Medium datasets (~100MB)_**" described.

What I have discovered so far it seems that when it is present a "broadcast variable" inside the "objective" function, the picker is not able to "dump" the "domain" variable, which contains all info, code and variables involved inside the objective function (here you can find info about broadcasted variables as well); 
as you can see in the code below (already cited above), the dump of the variable "domain" is done just as "sanity check", as matter of fact, it is then loaded in line 152 but it is neither saved in a variable nor used.

"fmin.py" script:

```
	             msg = pickler.dumps(domain)
	             # -- sanity check for unpickling
line 152	     pickler.loads(msg)
        	     trials.attachments["FMinIter_Domain"] = msg

```

**Comment by qianyu88** [comment]
Facing exactly the same issue with a data size of 67MB. Any updates?

**Comment by Veusty13** [comment]
Hello, we are facing the same issue with pickle size = 283MB . Any updates ?

**Comment by hipoglucido** [comment]
I am also following https://docs.databricks.com/_static/notebooks/hyperopt-spark-data.html and I am getting `Exception: Broadcast variable '840' not loaded!`
Any update?

**Comment by abhilash-j2** [comment]
Still facing this issue with 24MB dataset when broadcasting,

**Comment by aastha11190** [comment]
I ma facing the same issue. Has anyone got the resolution to this issue?

**Comment by delodic** [comment]
I run into something similar when trying to run this. We have a trainer class which is initialized with some data and has some functionality to split this and broadcast it. The broadcasted data is then accessed via self.
We get the 'broadcast variable not loaded'. 

In order to debug it, I put the whole trainer class in a databricks notebook cell and got a different error message for the same error:

> It appears that you are attempting to reference SparkContext from a broadcast variable, action, or transformation. SparkContext can only be used on the driver, not in code that it run on workers. For more information, see SPARK-5063.

The spark issue it refers to is not that interesting I think, it's about clearer error messages. But perhaps the issue is that the broadcast variable is put into self.bc_var, and the issue is that self is not distributed over the workers?
A similar issue is described here: https://stackoverflow.com/questions/31508689/spark-broadcast-variables-it-appears-that-you-are-attempting-to-reference-spar

**Comment by amanm27** [comment]
Hi, I'm facing this same issue when trying to broadcast a ~100 MB dataset (Pandas DF) in a Databricks notebook. Any guidance would be appreciated!

**Comment by candalfigomoro** [comment]
Ping @hanyucui, @WeichenXu123, @lu-wang-dl, @jkbradley

**Comment by candalfigomoro** [comment]
It looks like the `trials.attachments["FMinIter_Domain"] = msg` line is trying to add an "attachment". However, the following line https://github.com/hyperopt/hyperopt/blob/master/hyperopt/spark.py#L188 suggests that SparkTrials shouldn't even support attachments.

**Comment by raviraj07** [comment]
Can anyone please help with the resolution to the above problem?

**Comment by raviraj07** [comment]
> Can anyone please help with the resolution to the above problem?

Able to resolve the issue by removing the SparkTrials as Hyperopt package doesn't support Sparktrials.

**Comment by WeichenXu123** [comment]
Hi all,
Note the `fn` closure (containing the training data) itself is broadcast to spark executor side via spark broadcast.

**Comment by Karenou** [comment]
> Hi all, Note the `fn` closure (containing the training data) itself is broadcast to spark executor side via spark broadcast.

Hi, does it mean that we cannot use another broadcasted variable within the broadcasted 'fmin' closure? If that is the case, is there any other way to pass in variables to the fmin function? Many thanks!
