### ISSUE TITLE
Objective fn with one of the outputs as constraints

### ISSUE THREAD

**Issue by zonexo** [hyperopt/hyperopt#670]
I have used deep learning to obtain an multi output objective function (or black box). So it's multi input -> multi output. Now I need to optimize one of the outputs to get max output.

So supposed my inputs are ap1 - ap6, outputs are o1,o2,o3.

My objective is to get max o1, but constraints are:

ap3 - ap6 = 0.18, o3 < o2.
I use inequality 0.17 < ap3 - ap6 < 0.19 to relax the problem a little bit 

 I have managed to use hyperopt to get my ans as follows:
```
def objective(args):
    ap1,ap2,ap3,ap4,ap5,ap6 = args
    x_in = np.asarray([ap1,ap2,ap3,ap4,ap5,ap6])
    x_in = x_in.reshape(-1, 1).T
    
    if (ap3 - ap6 < 0.17) | (ap3 - ap6 > 0.19):
        o1= 1e10
    else:
        ans = -np.array(model.predict(x_in))
        o2= np.squeeze(aoa_cl_cruise_scaler.inverse_transform(ans[2,0,0].reshape(-1, 1)))
        o3= np.squeeze(aoa_max_c_end_scaler.inverse_transform(ans[3,0,0].reshape(-1, 1)))
        if o2> o3:
            o1= ans[1,0,0]
        else:
            o1= 1e10
    return {'loss': o1, 'status': STATUS_OK }
```
Is this the best way to solve the problem? It seems that I'm wasting a lot of trials because I can't use hp.uniform to limit their values.

My obj function is a black box obtained thru deep learning. Is it better a retrain a another model with o2,o3 becoming one of the inputs? Not sure if that would help.

**Comment by marctorsoc** [comment]
AFAIK hyperopt supports only single-objective optimisation. I'm not sure I understand your problem, can you give more context? like not calling ap1...ap6 and give some more meaningful names?

**Comment by zonexo** [comment]
Hi,

Sorry for the late reply. What I meant is that for e.g, I have an airfoil optimization problem. I need to get the airfoil shape which gives max endurance coefficient (c_end) at some optimum angle of attack (aoa).

I have used deep learning to get an objective function which predicts endurance coefficient (c_end), lift (cl), drag etc based on my airfoil shape parameters and its corresponding angle of attack (aoa).

To get max endurance coefficient (max_c_end), I can use hyperopt to optimize, giving my shape parameters and aoa some ranges of values. The answer will be max c_end for some values of shape parameters and aoa@max_c_end.

However, I have another constraint - my aoa@max_c_end < aoa@cl_cruise

where cl_cruise = max_cl / 1.2^2, and its corresponding aoa@cl_cruise is the aoa whereby cl = cl_cruise

So the problem is abit complicated, not sure if you understand fully.

One way to solve this problem is to predict max_c_end and aoa@max_c_end using hyperopt. Then check for the max_cl, cl_cruise and aoa@cl_cruise.

If (aoa@max_c_end < aoa@cl_cruise), then constraints satisfied, case close.

Else I would need to reduce the range of aoa input, run hyperopt and the subsequent calculations, check. If still not satisfied, reduce aoa range and re-iterate.

So I'm wondering if there's a better or smarter way to do it.

Thank you very much.

**Comment by marctorsoc** [comment]
I don't see a better way to do this, tbh

**Comment by zonexo** [comment]
Hi,

I can only constrain my input e.g.  0 < i1 < 1 with hyperopt. But i can't do this with outputs. So supposed I have:

F1(i1, i2) = o1, o2.

However, I need 0 < o2 < 1 while getting max o1. Can I train my neural network such that my new function is:

F2(i1, i2, o2) = o1?

Now I have o2 as one of my input and so I can use hyperopt to constrain it with 0 < o2 < 1. Can this work?
