### ISSUE TITLE
Example for early_stop_fn in fmin

### ISSUE THREAD

**Issue by shaddyab** [hyperopt/hyperopt#689]
Is there an example or tutorial on how to use the early_stop_fn argument in fmin?

**Comment by maxpumperla** [comment]
@marload did you have plans to add that?

**Comment by marload** [comment]
@maxpumperla I have a plan to do it. But first, I think we need to discuss with the other Maintains in which direction to produce the Tutorial. Tutorials 1 and 2 were the most basic, so they were easy to add, but other advanced tutorials(like `early_stop_fn`) are likely to require consultation.

**Comment by shaddyab** [comment]
In the meantime, is it possible to get a simple 2-3 line codes on how to make the callback?

**Comment by adalrsjr1** [comment]
@shaddyab here is a link to the [`/tests/fmin.py`](https://github.com/hyperopt/hyperopt/blob/abf6718951eecc1c43d591f59da321f2de5a8cbf/hyperopt/tests/test_fmin.py#L336) with pretty much what you need to use `early_stop_fn`

**Comment by marload** [comment]
@shaddyab 

As @adalrsjr1  said, there is a good example.


```
from hyperopt.early_stop import no_progress_loss

fmin(
    fn = lambda x: x,
    space=hp.uniform("x", -5, 5),
    algo=rand.suggest,
    max_evals=500,
    trials=trials,
    early_stop_fn=no_progress_loss(10)
)

# or 
def stop(trial, count=0):
    return count+1 >= 100, [count+1]

fmin(
    fn = lambda x: x,
    space=hp.uniform("x", -5, 5),
    algo=rand.suggest,
    max_evals=500,
    trials=trials,
    early_stop_fn=no_progress_loss(10)
)
```
You can create your own callback function, or you can use a provided function such as `no_progress_loss`.

**Comment by shaddyab** [comment]
@marload and @adalrsjr1 Thank you. This is what I am looking for.
