### ISSUE TITLE
Electronics Shop in hackerrank

### ISSUE THREAD

**Issue by vedantaher** [hyperopt/hyperopt#696]
b,n,m=(int(i) for i in input().split())
c=(int(i) for i in input().split())
d=(int(i) for i in input().split())
e=b
for i in range(n):
    for j in range(m):
        if b-(c[i]+d[j])<e and b-(c[i]+d[j])>0:
            e=c[i]+d[j]
        
print(e)

################i know i didnt apply condition for -1 but im getting  TypeError: 'generator' object is not subscriptable
and dont know whats wronge

**Comment by maxpumperla** [comment]
@vedantaher how is that a hyperopt issue?

**Comment by vedantaher** [comment]
oops  i posted in wronge section sorry .
