### ISSUE TITLE
running fmin creates 'CANT ENCODE' error

### ISSUE THREAD

**Issue by jshusko** [hyperopt/hyperopt#699]
Calling fmin returns the following error message in the console:

> --------------------------------------------------------------------------------                 
> CANT ENCODE                                                                                      
> -------------------------------------------------------------------------------- 

I am using the tpe suggest.

**Comment by bjkomer** [comment]
Can you provide a minimum example that reproduces the error?

I've never seen this happen before, but it looks like the error comes from [this](https://github.com/hyperopt/hyperopt/blob/16cf1111c2d4c5340a94ca1e37145ffcee2acf45/hyperopt/base.py#L427) line, indicating that it has something to do with the return value of your objective function not being encode-able.

**Comment by jshusko** [comment]
Hi Brent,

It turns out it was an environment issue with BSON. I updated that, and it
is now working.

Best,
Jacob Shusko
