### ISSUE TITLE
trials.trials dictionary values differ from actual ones.

### ISSUE THREAD

**Issue by ajaychat3** [hyperopt/hyperopt#708]
I am running a simple example to train my model. the code is shown below. the best parameter value is obtained in first iteration but different from actual one. I have also included the results and the trials.trials output. the numbers don't match. 

I am using hyperopt latest version 0.2.4 and python 3.7 on win 10. Am I doing anything wrong. 

**"from hyperopt import fmin, tpe, hp, STATUS_OK, Trials
def hyperopt_train_test(params,X,y):
    clf = RandomForestClassifier(**params)
    return cross_val_score(clf, X, y).mean()

space4rf = {
    'max_depth': hp.choice('max_depth', range(1,20)),
    'max_features': hp.choice('max_features', range(1,5)),
    'n_estimators': hp.choice('n_estimators', range(1,20)),
    'criterion': hp.choice('criterion', ["gini", "entropy"]),

}

best = 0
def f(params):
    global best
    acc = hyperopt_train_test(params,train,targets)
    if acc > best:
        best = acc
        print ('new best:', best, params)
    return {'loss': -acc, 'status': STATUS_OK}

trials = Trials()
best = fmin(f, space4rf, algo=tpe.suggest, max_evals=3, trials=trials)
print( 'best:')
print (best)"

new best:                                                                                                              
0.8137907224907414                                                                                                     
{'criterion': 'entropy', 'max_depth': 5, 'max_features': 1, 'n_estimators': 15}                                        
100%|█████████████████████████████████████████████████| 3/3 [00:00<00:00,  8.62trial/s, best loss: -0.8137907224907414]
best:
{'criterion': 1, 'max_depth': 4, 'max_features': 0, 'n_estimators': 14}**

trials.trials
[{'state': 2,
  'tid': 0,
  'spec': None,
  'result': {'loss': -0.8137907224907414, 'status': 'ok'},
  'misc': {'tid': 0,
   'cmd': ('domain_attachment', 'FMinIter_Domain'),
   'workdir': None,
   'idxs': {'criterion': [0],
    'max_depth': [0],
    'max_features': [0],
    'n_estimators': [0]},
   'vals': {'criterion': [1],
    'max_depth': [4],
    'max_features': [0],
    'n_estimators': [14]}},
  'exp_key': None,
  'owner': None,
  'version': 0,
  'book_time': datetime.datetime(2020, 7, 19, 16, 17, 54, 523000),
  'refresh_time': datetime.datetime(2020, 7, 19, 16, 17, 54, 655000)},
 {'state': 2,
  'tid': 1,
  'spec': None,
  'result': {'loss': -0.806973824618668, 'status': 'ok'},
  'misc': {'tid': 1,
   'cmd': ('domain_attachment', 'FMinIter_Domain'),
   'workdir': None,
   'idxs': {'criterion': [1],
    'max_depth': [1],
    'max_features': [1],
    'n_estimators': [1]},
   'vals': {'criterion': [0],
    'max_depth': [17],
    'max_features': [0],
    'n_estimators': [11]}},
  'exp_key': None,
  'owner': None,
  'version': 0,
  'book_time': datetime.datetime(2020, 7, 19, 16, 17, 54, 655000),
  'refresh_time': datetime.datetime(2020, 7, 19, 16, 17, 54, 793000)},
 {'state': 2,
  'tid': 2,
  'spec': None,
  'result': {'loss': -0.7553386479191513, 'status': 'ok'},
  'misc': {'tid': 2,
   'cmd': ('domain_attachment', 'FMinIter_Domain'),
   'workdir': None,
   'idxs': {'criterion': [2],
    'max_depth': [2],
    'max_features': [2],
    'n_estimators': [2]},
   'vals': {'criterion': [1],
    'max_depth': [14],
    'max_features': [2],
    'n_estimators': [1]}},
  'exp_key': None,
  'owner': None,
  'version': 0,
  'book_time': datetime.datetime(2020, 7, 19, 16, 17, 54, 793000),
  'refresh_time': datetime.datetime(2020, 7, 19, 16, 17, 54, 855000)}]

**Comment by bjkomer** [comment]
When you use `hp.choice` the index of the best parameter is what gets stored and returned. It looks like they do match based on that, since your choice ranges start from 1.

You can use this helper function to convert from the indices to the actual values:

```python
from hyperopt import space_eval
# ...
space_eval(space, best)
```

**Comment by ajaychat3** [comment]
Thanks Brent.
Regards, Ajay
Sent from Yahoo Mail on Android 
 
  On Sun, 19 Jul 2020 at 10:15 PM, Brent Komer<notifications@github.com> wrote:   


When you use hp.choice the index of the best parameter is what gets stored and returned. It looks like they do match based on that, since your choice ranges start from 1.

You can use this helper function to convert from the indices to the actual values:
from hyperopt import space_eval
# ...
space_eval(space, best)
