### ISSUE TITLE
constrained optimization problem

### ISSUE THREAD

**Issue by Long9401** [hyperopt/hyperopt#709]
Is the hyperopt support constrained optimization problem of the following form?

min f(x) <=0
subject to  g1(x) <=0
                  g2(x) <=0
                  ....
                  gk(x) <=0

**Comment by Arktius** [comment]
I'm not quite sure what you really mean. Is your question about minimizing a function with negative values? Must the parameters always smaller equal than 0? ...

**Comment by Long9401** [comment]
I am minimizing a function with constraints. See the wiki page: https://en.wikipedia.org/wiki/Constrained_optimization
Best,
Long Wang

**Comment by Arktius** [comment]
> Is the hyperopt support constrained optimization problem of the following form?
> 
> min f(x) <=0
> subject to g1(x) <=0
> g2(x) <=0
> ....
> gk(x) <=0

Short answer: '**Yes**'

Please remove the unnecessary email information in later comments.

**Comment by Long9401** [comment]
So are there any tutorials on setting up constraints in the objective function?

**Comment by Arktius** [comment]
https://github.com/hyperopt/hyperopt/wiki

https://github.com/hyperopt/hyperopt/wiki/FMin

**Comment by Arktius** [comment]
Maybe work with LPSolve: https://sourceforge.net/projects/lpsolve/
I've used this software in Operations Research.

**Comment by Long9401** [comment]
> Maybe work with LPSolve: https://sourceforge.net/projects/lpsolve/
> I've used this software in Operations Research.

Thank you for your response. My interest is to treat TPE as tool for expensive evaluation constrained optimization problems in some engineering applications. TPE already proved itself as an expensive unconstrained optimization just as other methods like EGO:
Jones, Donald R., Matthias Schonlau, and William J. Welch. "Efficient global optimization of expensive black-box functions." Journal of Global optimization 13.4 (1998): 455-492.
