### ISSUE TITLE
Cannot see progress output

### ISSUE THREAD

**Issue by zonexo** [hyperopt/hyperopt#710]
Hi,

I am running hyperopt on 2 machines. On one with CPU, I get the progress output:

  2%|▏         | 35/2000 [00:03<02:53, 11.32trial/s, best loss: 0.20275822281837463]

However, on another machine with with GPU, I  got:

(more hidden) ...

(more hidden) ...

Only the final output is shown:
100%|██████████| 2000/2000 [07:01<00:00,  4.74trial/s, best loss: 0.06477009505033493

How can I correct it? Btw, the code is exactly the same.

Thanks.

**Comment by Arktius** [comment]
How does your code look like?

Is there any output on the other machine but using the CPU? Probably a issue on the machine, not your code.

Try this fmin(...,verbose=True) or fmin(...show_progressbar=True).

**Comment by zonexo** [comment]
Thanks for the recommendations.

But strange enough, I can see the progress bar now. I didn't change my code but I think I restarted my PC once. 
Anyway, I will try your recommendations if it happens again. Thanks.
