### ISSUE TITLE
[question] use parameter values to define search space for subsequent parameters

### ISSUE THREAD

**Issue by flokde** [hyperopt/hyperopt#711]
Dear hyperopt team,

I am currently using hyperopt to optimise over a rather awkward search space to find an optimal sklearn pipeline for imbalanced classification. I really enjoy the flexibility when defining the search space. Is it possible to use a chosen parameter value to define the search space for other parameters? Say my first parameter is chosen at random between zero and one. I want my second parameter to be chosen at random between zero and the value chosen for the first parameter. For example:

I have random downsampling in my pipeline as the first step, which uses the desired ratio majority/minority class after the sampling is done as a hyperparameter. I have then another resampling preprocessing step and would like to use the value chosen for this first hyperparameter (the ratio) to set a bound for the next hyperparameter.

I couldn't definitively tell from the documentation and was wondering if this is possible.
Thank you very much in advance!

**Comment by bjkomer** [comment]
There isn't a nice way to do this directly that I am aware of, but a similar result can be achieved by redefining the second parameter as a proportion of the first. In this manner, you can calculate the actual value of the second parameter in the objective function, and no explicit dependency needs to be specified.

For example, something like this:

```python
space = {
    'p1': hp.uniform('p1', 0.0, 1.0),
    'p2': hp.uniform('p2', 0.0, 1.0)
}

def objective(params):
    p1 = params['p1']
    p2 = params['p1'] * params['p2']
    # ...
```

**Comment by guillaumenibert** [comment]
Hello,

I am coming back to this post which

I find interesting. I am looking to create a search space whose parameters are dependent on the above using the `hp.choice()` function. After having read many forums and posts on StackOverflow and GitHub, I wonder if what I want to do is possible.

Here is the challenge:

I have a list of items: `L = ['A', 'B', 'C', 'D', 'E', 'F', 'G']`.

I am looking for a search space that looks like this:

```python
search_space = { 'param_1': hp.choice('param_1', L),
                 'param_2': hp.choice('param_2', L\{param_1}),
                 'param_3': hp.choice('param_3', L\{param_1, param_2}),
                 'param_4': hp.choice('param_4', L\{param_1, param_2, param_3}),
                 'param_5': hp.choice('param_5', L\{param_1, param_2, param_3, param_4}),
```

For example for `param_2`, if `param_1`'s choice is `'B'`, then `param_2` will have to make a choice from the following list: `['A', 'C', 'D', 'E', 'F', 'G']` (`L` without element `'B'`).

I am trying to find out if there is any other way to create this search space than defining an expression to directly get a subset of choices (in my case it would be 5 choices), as proposed on this StackOverflow post: https://stackoverflow.com/questions/51367504/does-hyperopt-support-subset-of-choices. Unfortunately, it seems that this is a solution to avoid according to the hyperopt documentation (https://github.com/hyperopt/hyperopt/wiki/FMin#24-adding-new-kinds-of-hyperparameter).

The second idea, which I also want to avoid, is the manual creation of a huge list containing my 4 first parameters (combination and permutation functions would more or less automate the creation of this huge list): 

```python
search_space = hp.choice('params', [('A', ('B', ('C', ('D', hp.choice('param_5', ['E', 'F', 'G']))))),
                                    ('A', ('B', ('C', ('E', hp.choice('param_5', ['D', 'F', 'G']))))),
                                    ('A', ('B', ('C', ('F', hp.choice('param_5', ['D', 'E', 'G']))))),
                                    ...
                                   ]
                        )

# where the parameters are located at those indexes of the choice lists :
hp.choice('params', [('param_1', ('param_2', ('param_3', ('param_4', hp.choice('param_5', [other_element_1, other_element_2, other_element_3])))))]...)
```
This second approach does not seem ideal in hyperopt.

If you have any leads or ideas, I am interested :)

Thank you in advance!
