### ISSUE TITLE
Initial values / generate_trials_to_calculate doesn't work for nested parameter space

### ISSUE THREAD

**Issue by Arktius** [hyperopt/hyperopt#712]
@bjkomer 

I'd like to run some initial points before evaluating my objective function at random points (and before TPE).
Because of technical reasons, I want to have 100 random points with 'Normalize' = False and then True for example. Same for the hyperparameter 'MixedPrecision'. 

```
parameterspace = { 'parameters':{
                   'ac':hp.choice('AFunction',['elu','relu','selu','sigmoid','softplus','softsign','tanh']),
                   'bn':hp.choice('BatchNorm',[
                       {'bnorm':False,'dr':hp.loguniform('Dropout', np.log(1e-8), np.log(0.5))},
                       {'bnorm':True,'dr':0.0}]),
                   'bs':hp.quniform('BatchSize', 64, 256,8),
                   'bo':hp.choice('Bottleneck', [                                  
                       {'la':hp.quniform('BOFLayers', 1,4,1),'BO':0},
                       {'la':hp.quniform('BOTLayers', 0,4,1),'BO':hp.quniform('BotNeurons', 32,80,8)}
                       ]),
                   'da':hp.choice('Dataset',[dataset]),
                   'den':hp.quniform('DecNeurons', 136, 200, 8),
                   'dec':hp.loguniform('Decay',np.log(1e-5),np.log(1e-2)),
                   'en':hp.quniform('EncNeurons', 88,128,8),
                   'lr':hp.loguniform('LR', np.log(1e-3), np.log(0.5)),
                   'mp':hp.choice('MixedPrecision', [
                       {'MP':False,'gn':hp.quniform('GaussianNoiseT',0,0.05,0.0025)},
                       {'MP':True,'gn':0.0}]),
                   'no':hp.choice('Normalize', [False,True]),
                   'op':hp.choice('Optimizer', ['adadelta','adagrad','adam','rmsprop','sgd']),
                   'sp':hp.choice('Split',[split]),
                   'we':hp.choice('WeightInit', [0])
                   }}

bayes_trials = Trials()
algo = partial(tpe.suggest, n_startup_jobs=2, n_EI_candidates=50) #random points and take best candidate out of choice

maxevals = 4
init_vals = [hyperopt.pyll.stochastic.sample(parameterspace,rstate) for x in range(2)]
bayes_trials_init = generate_trials_to_calculate(init_vals)

best = fmin(fn=ae,
                    space=parameterspace,
                    algo=tpe.suggest,
                    trials = bayes_trials_init, 
                    max_evals=maxevals,
                    rstate = rstate)
```
The code above throws the following error message:

```
  File "C:\Users\Admin\Anaconda3\envs\tf2\lib\site-packages\hyperopt\pyll\base.py", line 869, in rec_eval
    int(switch_i)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'type'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-62-4cc3757ab005>", line 4, in <module>
    trials = bayes_trials_init)#,

  File "C:\Users\Admin\Anaconda3\envs\tf2\lib\site-packages\hyperopt\fmin.py", line 482, in fmin
    show_progressbar=show_progressbar,

  File "C:\Users\Admin\Anaconda3\envs\tf2\lib\site-packages\hyperopt\base.py", line 686, in fmin
    show_progressbar=show_progressbar,

  File "C:\Users\Admin\Anaconda3\envs\tf2\lib\site-packages\hyperopt\fmin.py", line 509, in fmin
    rval.exhaust()

  File "C:\Users\Admin\Anaconda3\envs\tf2\lib\site-packages\hyperopt\fmin.py", line 330, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)

  File "C:\Users\Admin\Anaconda3\envs\tf2\lib\site-packages\hyperopt\fmin.py", line 286, in run
    self.serial_evaluate()

  File "C:\Users\Admin\Anaconda3\envs\tf2\lib\site-packages\hyperopt\fmin.py", line 165, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)

  File "C:\Users\Admin\Anaconda3\envs\tf2\lib\site-packages\hyperopt\base.py", line 892, in evaluate
    print_node_on_error=self.rec_eval_print_node_on_error,

  File "C:\Users\Admin\Anaconda3\envs\tf2\lib\site-packages\hyperopt\pyll\base.py", line 871, in rec_eval
    raise TypeError("switch argument was", switch_i)

TypeError: ('switch argument was', <class 'hyperopt.pyll.base.GarbageCollected'>)
```

The code snippet below runs without evaluating the initial points:
```
best = fmin(fn=ae,space=parameterspace,algo=tpe.suggest,trials = bayes_trials, 
                    max_evals=maxevals,rstate = rstate,
                    points_to_evaluate=init_vals)
```
                    
Is there a way to sample random points, evaluate them and store them in this Trials-object?

**Comment by bjkomer** [comment]
> Is there a way to sample random points, evaluate them and store them in this Trials-object?

This is definitely possible, but I don't think there is a nice way to do this currently. If someone has the time, that would be a great feature to add!

One workaround that basically accomplishes the same thing would be to evaluate with different spaces at first, to fill up the trials object with the kinds of initial points you want, save that, and then do your runs from that starting point.

Something like this:

```python
from hyperopt import Trials, tpe, hp, fmin
from hyperopt.fmin import generate_trials_to_calculate
import pickle
import os

# some dummy function just to see what parameters get chosen
def objective(params):
    print(params)
    return 1

# the full space you care about
full_space = {
    'p1': hp.pchoice('p1', [(0.5, 'a'), (0.5, 'b')]),
    'p2': hp.pchoice('p2', [(0.5, 'c'), (0.5, 'd')]),
}

# some restriction, such as 'a' should always be chosen for p1
p1_fixed_a_space = {
    'p1': hp.pchoice('p1', [(1.0, 'a'), (0.0, 'b')]),
    'p2': hp.pchoice('p2', [(0.5, 'c'), (0.5, 'd')]),
}

# some other restriction, in this case 'b' is always chosen for p1
p1_fixed_b_space = {
    'p1': hp.pchoice('p1', [(0.0, 'a'), (1.0, 'b')]),
    'p2': hp.pchoice('p2', [(0.5, 'c'), (0.5, 'd')]),
}

if os.path.exists('warm_start.pkl'):
    # load saved initial parameters if they exist
    trials  = pickle.load(open("warm_start.pkl", "rb")
else:
    trials = Trials()

    # fill the trials object with 5 evals of the first restriction
    best = fmin(
        objective, space=p1_fixed_a_space, algo=tpe.suggest, trials=trials, max_evals=5
    )
    # fill the trials object with 5 evals of the second restriction
    best = fmin(
        objective, space=p1_fixed_b_space, algo=tpe.suggest, trials=trials, max_evals=5+5
    )
    # save for later
    pickle.dump(trials, open('warm_start.pkl', 'wb'))

# run 10 evals after the 'warm start'
best = fmin(
    objective, space=full_space, algo=tpe.suggest, trials=trials, max_evals=5+5+10
)
```

This is kinda hacky, but I think it will work as long as the different spaces have the same signature. I used `pchoice` here instead of `choice` because internally choice saves the index chosen. `pchoice` allows you to effectively change the number of elements with the indices still lining up. For numerical parameters there shouldn't be an issue.

**Comment by Arktius** [comment]
Thanks for the quick reply! Is there a way to redefine single parameters? 

I think an easy approach would be to have a function like space_eval() but in the other direction. Then, one could use 
`sample = hyperopt.pyll.stochastic.sample(parameterspace,rstate)` to sample new points,
`sample = point_eval(sample,parameterspace)` to convert the values to numbers and finally
```

trials = generate_trials_to_calculate(sample)

best = fmin(
            fn=run_the_strategy,
            space=params,
            algo=tpe.suggest,
            max_evals=10,
            trials=trials
            )
```

**Comment by Arktius** [comment]
@bjkomer I've used the approach that you proposed, but there seems to be a bug somewhere. 

```

from hyperopt import Trials, tpe, hp, fmin
from hyperopt.fmin import generate_trials_to_calculate
import pickle
import os

# some dummy function just to see what parameters get chosen
def objective(params):
    print(params)
    return 1

# the full space you care about
full_space = {
    'p1': hp.pchoice('p1', [(0.5, 'a'), (0.5, 'b')]),
    'p2': hp.pchoice('p2', [(0.5, 'c'), (0.5, 'd')]),
}

# some restriction, such as 'a' should always be chosen for p1
p1_fixed_a_space = {
    'p1': hp.pchoice('p1', [(1.0, 'a'), (0.0, 'b')]),
    'p2': hp.pchoice('p2', [(0.5, 'c'), (0.5, 'd')]),
}

# some other restriction, in this case 'b' is always chosen for p1
p1_fixed_b_space = {
    'p1': hp.pchoice('p1', [(0.0, 'a'), (1.0, 'b')]),
    'p2': hp.pchoice('p2', [(0.5, 'c'), (0.5, 'd')]),
}

if os.path.exists('warm_start.pkl'):
    # load saved initial parameters if they exist
    trials  = pickle.load(open("warm_start.pkl", "rb")
                          
else:
    trials = Trials()
    # fill the trials object with 5 evals of the first restriction
    best = fmin(
        objective, space=p1_fixed_a_space, algo=tpe.suggest, trials=trials, max_evals=25
    )
    # fill the trials object with 5 evals of the second restriction
    best = fmin(
        objective, space=p1_fixed_b_space, algo=tpe.suggest, trials=trials, max_evals=25+25
    )
    # save for later
    pickle.dump(trials, open('warm_start.pkl', 'wb'))

# run 10 evals after the 'warm start'
best = fmin(objective, space=full_space, algo=tpe.suggest, trials=trials, max_evals=75)
```
I get the following values for p1:
![image](https://user-images.githubusercontent.com/31614164/90642189-5d503080-e232-11ea-8047-7c2278ff294d.png)

**Comment by bjkomer** [comment]
I think I've figured out what is going on here. The hacky workaround I gave is not quite correct, but it looks like it will work if you replace `tpe.suggest` with `rand.suggest` in the warmup phases. The probabilities in pchoice are just initial probabilities to use when choosing randomly. TPE starts from this distribution, but then builds its own distribution based on the result of past iterations (from the trials object). The second part of the warmup phase the trials object has some entries for the initially 0 probability choice, so TPE can use those to change the probability it uses to something nonzero.

The `rand` algorithm ignores past trials, so will use the initial probabilities (or given bounds in the case of numerical parameters) every time.

> Is there an option to get the parameter boundaries of the search space?

I'm not sure what you mean by this. Boundaries are defined when you create the search space, e.g. `hp.uniform('param', 0.01, 1.0)` only allows values to be chosen between 0.01 and 1.0. All search algorithms should respect these boundaries. Some distributions can be unbounded, such as `hp.normal(label, mu, sigma)`.

**Comment by Arktius** [comment]
Yeah, it works now. Thank you, man!

> > Is there an option to get the parameter boundaries of the search space?
> 
> I'm not sure what you mean by this. Boundaries are defined when you create the search space, e.g. `hp.uniform('param', 0.01, 1.0)` only allows values to be chosen between 0.01 and 1.0. All search algorithms should respect these boundaries. Some distributions can be unbounded, such as `hp.normal(label, mu, sigma)`.

It wasn't correctly formulated. Instead of using different spaces, I wanted to access single parameters and **set** their boundaries. So one does not to create multiple spaces:

`p1_fixed_a_space['p2'] =  hp.pchoice('p2', [(0.5, 'c'), (0.5, 'd')])`

**Comment by bjkomer** [comment]
Happy to hear it's working!

> I wanted to access single parameters and set their boundaries. So one does not to create multiple spaces

There isn't a nice built in way to do that as far as I know. Swapping out single dictionary elements like it your example will work, though when the space is nested in multiple `choice` blocks you'll either have to swap out the whole block or traverse the tree to the part you want to change (e.g. the 'high' and 'low' boundaries of `hp.uniform` can be changed with [`set_kwarg`](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/pyll/base.py#L397)).
Making this kind of swapping easier to do may be a nice feature to add if someone has the time, though just having a function to generate the different spaces you need might be easiest in your case.
