### ISSUE TITLE
Can't use trials=SparkTrials() with mmlspark LightGBMClassifier

### ISSUE THREAD

**Issue by informatica92** [hyperopt/hyperopt#720]
Hi all, I am trying to test a very simple code to perform a distributed hyperparameter search. 
If I run the basic version of the code (see below)
```
train, test = model_df.randomSplit([0.8, 0.2], seed=7)
space = {
    'numLeaves': hp.choice('numLeaves', range(10,200,1)),
    'maxDepth': hp.choice('maxDepth', range(1,15,1)),
    'baggingFraction': hp.uniform('baggingFraction', 0, 1),
    'featureFraction':  hp.uniform('featureFraction', 0, 1),
    'lambdaL1': hp.uniform('lambdaL1', 0, 2),
    'lambdaL2': hp.uniform('lambdaL2', 0, 2),
    'learningRate': hp.uniform('learningRate', 0.05, 0.50),
    'numIterations': hp.choice('numIterations', range(100, 500, 50)),
    'numLeaves': hp.choice('numLeaves', range(10, 100, 1)),
}
def objective_v2(params):
    lgb = LightGBMClassifier(
        featuresCol='features',
        labelCol='to_hit',
        isUnbalance=True
    )
    
    model = lgb.fit(train, params)
    pred = model.transform(test)
    
    metrics = ComputeModelStatistics(
      evaluationMetric='classification',
      labelCol='to_hit',
      scoredLabelsCol='prediction'
    ).transform(pred)
    
    return -1.0 * metrics.select("accuracy").collect()[0][0]
best = fmin(objective_v2, space, algo=tpe.suggest, max_evals=2)
```
it works well. As soon as I change the last line into: 
```
best = fmin(objective_v2, space, algo=tpe.suggest, max_evals=2, trials=SparkTrials(parallelism=8))
```
I get this error instead:
```
TypeError: can't pickle _thread.RLock objects
```

Do you know how to solve this?

**Comment by vanducng** [comment]
Hi @informatica92, this is currently a limitation of **hyperopt**. You can only use **distributed Hyperopt** or **single-machine Hyperopt** on Spark Cluster.

* Use distributed Hyperopt with single-machine training algorithms. Specifically, you use the SparkTrials class when calling hyperopt.fmin() and run single-machine training algorithms in the objective function.
* Use single-machine Hyperopt with distributed training algorithms. Specifically, you use the default base.Trials class when calling hyperopt.fmin() and run distributed training algorithms in the objective function.

Refer details from here: https://docs.databricks.com/applications/machine-learning/automl-hyperparam-tuning/index.html

**Comment by stb-f5c** [comment]
@vanducng does the limitation of hyperopt continue now?
