### ISSUE TITLE
Early Stopping module not found

### ISSUE THREAD

**Issue by malorimeyer** [hyperopt/hyperopt#721]
Hello,

I install hyperopt via pip command in databricks. everything works as expected until I try to add the early stopping parameter to fmin. I have followed the example showing in the commit comments here: https://github.com/hyperopt/hyperopt/pull/661#issuecomment-652535028

This import command supplies this error: (no module named 'hyperopt.early_stop'
![image](https://user-images.githubusercontent.com/42249496/90300103-98331c80-de5e-11ea-9f1f-dd88672aa734.png)

Here is the version information:
![image](https://user-images.githubusercontent.com/42249496/90300151-daf4f480-de5e-11ea-966e-3623821698cb.png)

Is this a databricks issue? I know databricks promotes this package a lot, so I thought there would be no hitches.

I have also tried to manually install the correct version, and still get the same error:
![image](https://user-images.githubusercontent.com/42249496/90303267-409eac00-de72-11ea-9fad-3e1a7d7c59d5.png)

**Comment by thededlier** [comment]
The early stop feature is not yet in the latest release.

**Comment by malorimeyer** [comment]
@thededlier Thank you very much. Do you have an idea of how we could "jerry rig" something similar until the release? Have you seen any examples of how people are doing it?

**Comment by thededlier** [comment]
You can clone the current master branch and install it manually with `pip` in your virtual environment.

**Comment by marctorsoc** [comment]
sorry for the late reply. Will check with the team

**Comment by michaelmior** [comment]
@malorimeyer This should work in the latest release of Hyperopt (0.2.7). I'm going to close this for now, but if you're still having issues, feel free to reopen.
