### ISSUE TITLE
how can i use brier score? 

### ISSUE THREAD

**Issue by zahs123** [hyperopt/hyperopt#723]
all i am new to hyperopt. i plan to use it as below: 

```
space={'max_depth': hp.quniform("max_depth", 3, 18, 1),
        'gamma': hp.uniform ('gamma', 1,9),
        'reg_alpha' : hp.quniform('reg_alpha', 40,180,1),
        'reg_lambda' : hp.uniform('reg_lambda', 0,1),
        'colsample_bytree' : hp.uniform('colsample_bytree', 0.5,1),
        'min_child_weight' : hp.quniform('min_child_weight', 0, 10, 1),
        'n_estimators': 180
    }

def objective(params):
    clf= xgb.XGBClassifier(n_estimators =space['n_estimators'], max_depth = space['max_depth'], 
                           gamma = space['gamma'],
                         reg_alpha = space['reg_alpha'],min_child_weight=space['min_child_weight'],
                         colsample_bytree=space['colsample_bytree'],objective='binary:logistic')
    
    score = cross_val_score(clf, x_train_fin, y_train_fin, cv=kfolds.split(x_train_fin,y_train_fin), 
                            scoring='neg_brier_score')
     # Extract the best score
    best_score = max(score)


    # Dictionary with information for evaluation
    return {'loss': best_score, 'params': params, 'status': STATUS_OK}



tpe_algorithm = tpe.suggest

# Trials object to track progress
bayes_trials = Trials()

# Optimize
best = fmin(fn = objective, space = space, algo = tpe.suggest, max_evals = 50, trials = bayes_trials)
```

updating this because i can use cross_val_score to pass 'neg_brier_score' since it is negated. when i run the above however i get the error: 

```
: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
xgboost.core.XGBoostError: Some trailing characters could not be parsed: ' float
1   hyperopt_param
2     Literal{colsample_bytree}
3     uniform
4       Literal{0.5}
5       Literal{1}'
```

what am i doing wrong?

**Comment by bjkomer** [comment]
You can use any evaluation metric you like, as long as you end up with a scalar value to minimize. sklearn has many of these built in that are easy to use.

For brier score, simply use it like normal:

```python
from sklearn.metrics import brier_score_loss
def objective(params):
    # ...
    loss = brier_score_loss(y_test, pred)
    return {'loss': loss, 'status': STATUS_OK}
```

If you're meaning the `eval_metric` parameter of your XGB model, you'll have to look at the XGB docs for what options are available, that is not a hyperopt thing.

**Comment by zahs123** [comment]
how can i also use stratfied k folds? you can usually do this in grdisearch by using cv parameter but cannot find documentation anywhere in relation to this method

**Comment by bjkomer** [comment]
The documentation for stratified k fold is [here](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html).

This is the default cross validation used in the [`hyperopt-sklearn`](https://github.com/hyperopt/hyperopt-sklearn) project. Depending on your use case that project might be simpler for you to use. For vanilla hyperopt there is more flexibility but you'll have to define the k folds and averaging yourself in the optimization function.

**Comment by zahs123** [comment]
just to clarify, the default kfold used in the above is stratified k fold cross validation? i am unsure on how to implement it in my above code.

**Comment by bjkomer** [comment]
Yes, the default cross validation for `hyperopt-sklearn` is stratified k fold (for classification problems). The code where it is used is [here](https://github.com/hyperopt/hyperopt-sklearn/blob/64c693164fff9753165bb71f64648cc659d83025/hpsklearn/estimator.py#L245).

For the code in your updated question, you need to replace `space` with `params` in your objective function. `space` is a hyperopt specific description of the space itself, while in the function params are the actual parameters chosen on a given evaluation.

**Comment by zahs123** [comment]
thanks. So there is no need for me to use cross_val_score then i suppose. In the code you have linked how does hyperopt infer it is a classifier - from 'is_classif'? also how does it determine the number of folds for straified. 

since no need for k-folds i guess i can just use the below: 


```
def hyperparameter_tuning(space):
    clf= xgb.XGBClassifier(n_estimators =space['n_estimators'], max_depth = int(space['max_depth']), 
                          
                         reg_alpha = space['reg_alpha'],min_child_weight=space['min_child_weight']
                       ,objective='binary:logistic')
    evaluation = [( x_train_fin, y_train_fin), ( x_test, y_test)]
    
    clf.fit(x_train_fin, y_train_fin,
            eval_set=evaluation,
            early_stopping_rounds=10,verbose=False)

    pred = clf.predict(x_test)
    loss = brier_score_loss(y_test, pred)
    print ("SCORE:", loss)
    #change the metric if you like
    return {'loss': loss, 'status': STATUS_OK }
```

**Comment by bjkomer** [comment]
The code I linked is from a different project built on top of hyperopt. If you are just using hyperopt you have to do the cross validation yourself. The usual thing to do is to score each fold and return the average.

**Comment by zahs123** [comment]
I see I will also try the other implementation

**Comment by bjkomer** [comment]
It is built in already, the function to use is [here](https://github.com/hyperopt/hyperopt-sklearn/blob/master/hpsklearn/components.py#L1335). It might not be in the latest version on pip, so you'll have to install from the master branch on github.

**Comment by zahs123** [comment]
`AllTrialsFailed                           Traceback (most recent call last)
<ipython-input-88-4adad31c0a93> in <module>
      1 # Search the space of classifiers and preprocessing steps and their
      2 # respective hyperparameters in sklearn to fit a model to the data
----> 3 estim.fit(x_train_fin.values ,y_train_fin.values)
      4 

~/anaconda3/lib/python3.7/site-packages/hpsklearn/estimator.py in fit(self, X, y, EX_list, valid_size, n_folds, cv_shuffle, warm_start, random_state, weights)
    744             increment = min(self.fit_increment,
    745                             adjusted_max_evals - len(self.trials.trials))
--> 746             fit_iter.send(increment)
    747             if filename is not None:
    748                 with open(filename, 'wb') as dump_file:

~/anaconda3/lib/python3.7/site-packages/hpsklearn/estimator.py in fit_iter(self, X, y, EX_list, valid_size, n_folds, cv_shuffle, warm_start, random_state, weights, increment)
    655                               #    so we notice them.
    656                               catch_eval_exceptions=False,
--> 657                               return_argmin=False, # -- in case no success so far
    658                              )
    659             else:

~/anaconda3/lib/python3.7/site-packages/hyperopt/fmin.py in fmin(fn, space, algo, max_evals, timeout, loss_threshold, trials, rstate, allow_trials_fmin, pass_expr_memo_ctrl, catch_eval_exceptions, verbose, return_argmin, points_to_evaluate, max_queue_len, show_progressbar)
    480             catch_eval_exceptions=catch_eval_exceptions,
    481             return_argmin=return_argmin,
--> 482             show_progressbar=show_progressbar,
    483         )
    484 `

**Comment by zahs123** [comment]
ok many thanks
