### ISSUE TITLE
How can I access/save the Trials() instance from within the function to be minimized?

### ISSUE THREAD

**Issue by fantauzzi** [hyperopt/hyperopt#725]
After each iteration of hyperopt running the function (`fn`) to be minimized, I would like to save the current value of the `Trials()` instance; this way, if the computation is interrupted (by a CTRL+C, a power outage, etc.), I can still re-run my program and have hyperopt resume the computation from the last iteration of hyperopt. 

Currently I must wait for `fmin()` to return, before I can save the `Trials()` instance, but this may require many iterations. If the computation is interrupted before `fmin()` completes, and the `Trials()` instance has not be saved, I won't be able to resume the computation from where it was interrupted.

How could I do that? E.g. any way I can access the `Trials()` instance from within the implementation of the function to be minimized, and save it from there?

**Comment by bjkomer** [comment]
You can run `fmin` in a loop and save every X iterations.

```python
trials = Trials()  # can load a partial run instead of initializing here if it crashed
batch_size = 20  # number of evaluations per fmin call
max_evals = 100  # total number of evaluations
for current_evals in range(0, max_evals, batch_size):
    # run the next batch of evaluations
    best = fmin(objective, space, algo, max_evals=current_evals, trials=trials)
    # save trials here
    # ...
```

**Comment by fantauzzi** [comment]
> You can run `fmin` in a loop and save every X iterations. [...]

I think I will do that, possibly running `fmin()` for one iteration only at a time, and then also checking for the early termination condition within my loop and outside of `fmin()`.
