### ISSUE TITLE
Parallel search using MongoDB Atlas

### ISSUE THREAD

**Issue by gianghoang912** [hyperopt/hyperopt#727]
Hello,

I'm trying to use MongoTrials with MongoDB Atlas. However, it seems like the mongoexp doesn't support the "srv" protocol (which is required when connecting to MongoDB Atlas). I want to ask if it is possible to add the "srv" protocol, or do you have any recommended workaround for connecting to the Atlas?

Best regards

**Comment by german1608** [comment]
What's the resolution of this ticket?

**Comment by g-hoang** [comment]
@german1608 since we found out that hyperopt is only designed for local MongoDB (or at least at the time I asked), we tried to set it up on several local computers and sync the results as much as we can on the "central" MongoDB Atlas. It is for sure not a perfect solution but sufficient for our case

**Comment by german1608** [comment]
Could you share your solution @g-hoang please? Im having problems setting up the connection string.

**Comment by g-hoang** [comment]
@german1608 sorry, maybe my previous answer wasn't clear. I think until now, it is **impossible** to use hyperopt with MongoDB Atlas directly (According to [their documentation](https://github.com/hyperopt/hyperopt/wiki/Parallelizing-Evaluations-During-Search-via-MongoDB), hyperopt connects to MongoDB via the mongod process, and thus it requires `network-visible` connections (e.g., localhost, or ssh connection).

In case you are having troubles setting up, could you please give me some more context of your situation? maybe I can give you some recommendations
