### ISSUE TITLE
Parameters' rounding

### ISSUE THREAD

**Issue by shaddyab** [hyperopt/hyperopt#728]
is it possible to round the float parameter?
For example, the values sampled from hp.uniform('subsample',0.55, 0.95) would be incremented by 0.01 ( 0.55, 0.56, 0.57 .... 0.95, 0.95)

**Comment by bjkomer** [comment]
This is exactly what `hp.quniform` is for. You give it a range and a step size.
For your example it would be `hp.quniform('subsample', 0.55, 0.95, 0.01)`

**Comment by shaddyab** [comment]
@bjkomer Thank you! I will try it.
