### ISSUE TITLE
AttributeError: module 'hyperopt' has no attribute 'choice'

### ISSUE THREAD

**Issue by CamilleBV** [hyperopt/hyperopt#729]
Hello, 

I can't understand why I can't access to hyperopt features ...
Do you have any idea ? 

Thank you 

![image](https://user-images.githubusercontent.com/70316872/91445409-5ea6dc00-e876-11ea-96df-be4ab072408d.png)

**Comment by maxpumperla** [comment]
you need lowercase `choice`, not `Choice`

**Comment by CamilleBV** [comment]
Sorry, thank you!
