### ISSUE TITLE
Hyperopt incorrect version in __version__

### ISSUE THREAD

**Issue by Leonolovich** [hyperopt/hyperopt#730]
Both the conda and the pip packages for hyperopt 0.2.4 state that they are 0.2.3 inside __init__.py.

At least one of the fixes for an issue that I am having is not working for me, and the comments state that there have been a lot of changes since 0.2.3, which leads me to think that I may have 0.2.3 installed and not that the __version__ variable was not updated. Is this the case? If so, can these be updated on the conda and pypi repos?

**Comment by maxpumperla** [comment]
@Leonolovich you're right, my mistake. I think we should have a version 0.2.5 soon.

**Comment by liuzhe-lz** [comment]
@maxpumperla And 0.2.5 states it's 0.2.4
https://github.com/hyperopt/hyperopt/blob/0.2.5/hyperopt/__init__.py#L43

**Comment by marctorsoc** [comment]
any volunteer for a PR to fix this? doesn't seem too complicated :)

**Comment by maxpumperla** [comment]
https://github.com/hyperopt/hyperopt/blob/0.2.5/hyperopt/__init__.py

simply not true, look again
