### ISSUE TITLE
Time series examples

### ISSUE THREAD

**Issue by microprediction** [hyperopt/hyperopt#731]
Hi. Reaching out as developer of [microprediction](https://pypi.org/project/microprediction/) package. 

Quite a few of the time series algorithms use hyperopt now and I'd expect to see more. 

An example is  [Yex Cheetah](https://github.com/microprediction/microprediction/blob/master/crawler_examples/yex_cheetah.py)

I'm wondering if there is any other logical place to put specific usage examples of hyperopt for time series.

**Comment by maxpumperla** [comment]
@microprediction you want to put microprediction examples in this repo? just want to make sure I understand your idea. we could think about an examples folder here, but most likely is that we might end up creating an examples repo in the hyperopt org.

**Comment by microprediction** [comment]
If you do create a separate repo for examples (seems cleaner) I’ll add one.

 
 
 






This message, including its attachments, contains information from Intech Investment Management LLC or one of its affiliates, which may be confidential and/or privileged. If
 it has been sent to you in error, please reply to advise the sender of the error and immediately delete this message. Thank you.
l
