### ISSUE TITLE
0.2.5 Release Cut

### ISSUE THREAD

**Issue by jameswinegar** [hyperopt/hyperopt#734]
Are there any particular issues the team is waiting to resolve to make a 0.2.5 release cut? I'm very interested in facilitating this as we'd like to include the changes from #661 which were not part of the 0.2.4 release. 

It's easier if it's in PyPI instead of the wheel I'm shipping around currently :)

**Comment by nechciGitHub** [comment]
Please, https://github.com/hyperopt/hyperopt/issues/653
it's easy.
