### ISSUE TITLE
ATPE failed to continue optimize due to unfitted scalingModel

### ISSUE THREAD

**Issue by aEgoist** [hyperopt/hyperopt#738]
Optimization would fail after 10 trails and raise RuntimeError(

>  50%|█████     | 10/20 [27:24<27:24, 164.48s/trial, best loss: 0.8421969852136753]
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 131, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\hyperopt\progress.py", line 27, in tqdm_progress_callback
>     yield pbar
>   File "C:\ProgramData\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 265, in run
>     new_trials = algo(
>   File "C:\ProgramData\Anaconda3\lib\site-packages\hyperopt\atpe.py", line 1612, in suggest
>     parameters = optimizer.recommendNextParameters(
>   File "C:\ProgramData\Anaconda3\lib\site-packages\hyperopt\atpe.py", line 763, in recommendNextParameters
>     transformed = scalingModel.transform([[stats[feature]]])[0][0]
>   File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_data.py", line 791, in transform
>     X = self._validate_data(X, reset=False,
>   File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py", line 436, in _validate_data
>     self._check_n_features(X, reset=reset)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py", line 372, in _check_n_features
>     raise RuntimeError(
> RuntimeError: The reset parameter is False but there is no n_features_in_ attribute. Is this estimator fitted?

This is caused by 

> hyperopt/atpe:761:766
> ```
>             for feature in self.atpeModelFeatureKeys:
>                 scalingModel = self.featureScalingModels[feature]
>                 transformed = scalingModel.transform([[stats[feature]]])[0][0]
>                 baseVector.append(transformed)
> 
>             baseVector = numpy.array([baseVector])
> ```
where atpe uses a featureScalingModels to transform the params with previous stats, but a fit call cannot be found anywhere in this class ATPEOptimizer code. I'm thinking either there is a bug there or I'm missing some part of user guide of atpe algo, any help?

**Comment by ilya-ustinov** [comment]
Same story

**Comment by ilya-ustinov** [comment]
Looks like fit_transform is needed instead of transform
