### ISSUE TITLE
[question] Automate mongodb usage (run mongo workers from python script)

### ISSUE THREAD

**Issue by flokde** [hyperopt/hyperopt#740]
Dear hyperopt team,

I got my project up and running with hyperopt and am happy with my choice. Now I would really like to include parallelisation in my optimisation task. I tried this via mongodb as recommended in your tutorial and with the help of some other issues this worked quite nicely.

I would however love to get rid of the "manual" part of this parallelisation, where I launch another shell and get the hyperopt-mongo-workers going. My project is a simple AutoML framework and the optimisation through hyperopt is basically the search for the optimal model. To make this search user friendly, I would prefer for the user not to have to start the mongodb process and then launch the workers from the console, but rather have my script take care of it internally.

I couldn't find any issue on this topic. Is there a way to do this? I know I can access the console from a python script, but I am having trouble with the running of the workers, as this should happen when the script blocks at the fmin call and therefore I can't really include it in my script "at the same time".

Thanks so much in advance!

P.S. Would you recommend starting one worker per available cpu?

**Comment by amtamasi** [comment]
I'd like to echo this. I think it would be great to automate that "manual" piece of having to launch hyperopt-mongo-workers, maybe by using python's [multiprocessing module](https://docs.python.org/3/library/multiprocessing.html)

**Comment by skylogic004** [comment]
I've been launching workers from Python too. My solution goes like this:
```
import sys
from hyperopt import mongoexp
...
sys.argv = [
	'hyperopt-mongo-worker',
	f'--mongo={DB_host}:{DB_port}/{name}',
	'--poll-interval=5',
	'--no-subprocesses',
]
mongoexp.main()
```
which sets the command line args to be passed to the worker program. Though if you wanted, you could call `hyperopt.mongoexp.main_worker_helper` directly.

As for the blocking call to `fmin`, you could actually startup the workers *first* (using multiprocessing module in a non-blocking fasion) then end with calling `fmin`.
