### ISSUE TITLE
Push 0.2.5 to PyPI?

### ISSUE THREAD

**Issue by akx** [hyperopt/hyperopt#744]
Based on https://github.com/hyperopt/hyperopt/releases/tag/0.2.5 it seems there's something of a 0.2.5 release, but it's not on PyPI.

Could it be pushed?

cc @marctorsoc as the author of said release

**Comment by marctorsoc** [comment]
This is supposed to be the last version supporting python2, and also release last changes. Waiting for @maxpumperla to do so. Don't have permissions

**Comment by jameswinegar** [comment]
Would love this plus conda-forge being updated.

**Comment by marctorsoc** [comment]
maybe @jaberg can do it otherwise?

**Comment by adalrsjr1** [comment]
any update on this issue?

**Comment by maxpumperla** [comment]
sorry, had a bit of a health emergency going on. should be live now, including the latest Spark 3 additions

**Comment by akx** [comment]
> sorry, had a bit of a health emergency going on.

Sorry to hear! Hope that's cleared up!

> should be live now, including the latest Spark 3 additions

Thank you :)
