### ISSUE TITLE
Changing hyperopt-mongo-worker wait time

### ISSUE THREAD

**Issue by samarthbhargav** [hyperopt/hyperopt#766]
Currently, `hyperopt-mongo-worker` dies after it finds no jobs to execute for a while. Is it possible to have this run for a specified amount of time or alternatively, to keep it running? `--help` doesn't seem to ... help.

**Comment by skylogic004** [comment]
I believe you need to use the `--reserve_timeout` option. It's default is 120 but you can set it to None to disable it.
