### ISSUE TITLE
Choosing parameter space directly on objective function

### ISSUE THREAD

**Issue by brunodoamaral** [hyperopt/hyperopt#769]
Hi all!

This is just a suggestion about a different way to use the minimization API. Here we annotate the search space directly on parameters.

I'm sure this may not be the best approach for all situations, but at least for me seems to be easier to link parameters and search space:

```python
# define an objective function
def objective(
            x: hp.uniform('x', -10, 10),
            y: hp.uniform('y', -10, 10)
        ):
    return (x * y) ** 2
```

We'll need to use the inspect module to get the annotations from function parameters:

```python
import inspect

# define a search space
space = inspect.getfullargspec(objective).annotations
```

And finally wrap the objective function on a dict -> kargs helper function:

```python
def objective_fmin_wrapper(func):
    def _objective(params):
        return func(**params)
    
    return _objective

# minimize the objective over the space
best = fmin(objective_fmin_wrapper(objective), space, algo=tpe.suggest, max_evals=1000)

print(best)
```

I'm sorry if this is a duplicate of future features. Anyway, I hope this can enrich the discussion about hyperopt.

Best regards,
Bruno

**Comment by maxpumperla** [comment]
@brunodoamaral thank you, great suggestion. @marload I think you wanted to look into API going forward?

**Comment by marload** [comment]
@maxpumperla 
To me this design looks very attractive. It cannot be replaced in all cases, but it seems that it can be used as an intuitive design in many cases. I will make related PR sooner or later.

@brunodoamaral 
Or do you have any plans to create your own PR?

**Comment by brunodoamaral** [comment]
@marload and @maxpumperla thanks for your positive reception. I can create a PR, but first we should decide the design of this API.

One that come to my mind is:

```python

# define the objective function as before

# minimize the objective over the space
best = fmin(objective, space='auto', algo=tpe.suggest, max_evals=1000)
```
Within `fmin`, I will call `inspect.getfullargspec(objective).annotations` if `space == 'auto'` to get the search space. It should raise an Exception if the objective function has no annotations.

What do you think?

**Comment by marload** [comment]
@brunodoamaral 

This design looks good to me. In addition, if the parameter obtained `inspecto.getfullargspec` is not Hyperopt Search Space, an error must be raised.

**Comment by brunodoamaral** [comment]
@marload I just forked the master branch, but I'm having errors on tests. Do you know if they are ok?

Here is one of the errors:

```
======================================================================
ERROR: test_plot_vars (tests.test_plotting.TestPlotting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bruno/git/hyperopt/hyperopt/tests/test_plotting.py", line 57, in test_plot_vars
    do_show=get_do_show())
TypeError: main_plot_vars() got multiple values for argument 'do_show'

----------------------------------------------------------------------
Ran 3 tests in 29.597s
```

I can fix then as a sub-product of my proposed change. But let me know if someone else is having the same problems.

**Comment by marload** [comment]
I'm sorry I'm so late. I will check this issue.

**Comment by marload** [comment]
@brunodoamaral 
Would you check if the repository you forked is the master? `test_plotting.py` does not have the 57th line.

**Comment by brunodoamaral** [comment]
My bad. I have an old fork that I used for https://github.com/hyperopt/hyperopt/pull/521. I'll clean it before continuing the  proposal of this issue.
