### ISSUE TITLE
hyperopt chooses which parameter to tune

### ISSUE THREAD

**Issue by DivJ** [hyperopt/hyperopt#773]
Hi,
For my experiment, I want the ability to tune one parameter at a time and let the other one take the default value.
For eg:

```
space = 
{
  'a': hp.uniform('a',0,1),
  'b': hp.uniform('b',0,1)
}
```

I want that the hyperopt only picks either a or b in each run using the default value of the other parameter. In-short, I want to tune only one parameter at a time leaving the other default.

How can I do that?

Thanks

**Comment by blaney83** [comment]
Isn't this counter to the fundamental strength of HPO? If the parameters are dependent, then any tuning of one would necessarily affect the optimization range of the others and the order in which they were tuned would vastly impact the final loss optimization. Regardless, have you considered a multi-step approach- tuning all parameters to get a baseline optimization then holding others constant while optimizing only those which you identify as most interesting?

**Comment by michaelmior** [comment]
What is the "default" here? Hyperopt doesn't really have a notion of a default value for a parameter. In this case, it sounds like what you just want a grid search and Hyperopt might be overkill. I'm going to close this for now, but feel free to reopen if you have further questions.
