### ISSUE TITLE
How to run Hyperopt on GAN?

### ISSUE THREAD

**Issue by majesticcoder14** [hyperopt/hyperopt#779]
I am creating a Generative Adversarial Network, and I want to run Hyperopt on the GAN. However, I am confused on how to do this because the GAN is essentially 2 models, with the output of one model, going into the next model. Any help would be appreciated.

**Comment by rifaadev** [comment]
Hi @majesticcoder14 I have the same issue, do you have the answer ?

**Comment by majesticcoder14** [comment]
> Hi @majesticcoder14 I have the same issue, do you have the answer ?

Hi. What I did was to instead use the [Optuna](https://github.com/optuna/optuna) library in the [Pytorch](https://github.com/pytorch/pytorch) framework. It allowed me to create a custom training process that I could use for a GAN.  You would need to know how to use Pytorch first however. If you need any help, please contact me.

**Comment by michaelmior** [comment]
The challenge here is really just want value you want to use to evaluate the GAN. One possibility for is the [inception score](https://medium.com/octavian-ai/a-simple-explanation-of-the-inception-score-372dff6a8c7a). The blog post describes inception score for images, but you could certainly apply it to other domains as well. Once you have a metric defined, using Hyperopt with a GAN is not really very different from any other model.
