### ISSUE TITLE
fmin - specify starting points in search space

### ISSUE THREAD

**Issue by snaraya7** [hyperopt/hyperopt#787]
Thank You for hyperopt, great package!

Is there a way to force `fmin `function to start exploration from a **specific set of points** in `space` ?

**Comment by rydeveraumn** [comment]
@snaraya7 did you ever get an answer to this question? I see this was way back in 2021 now.

**Comment by michaelmior** [comment]
@snaraya7 You can specify this using the `points_to_evaluate` parameter to `fmin`. This parameter accepts a list of dictionaries where each contains a set of parameter values you want to use before the optimization process begins. Note that in this case, the actual number of trials run will be `len(points_to_evaluate) + max_evals`.
