### ISSUE TITLE
Quantized sampling does not return integers

### ISSUE THREAD

**Issue by Petkomat** [hyperopt/hyperopt#788]
For example,

a sample from `hp.qloguniform('a', 0, 10, 1)`  is `21669.0` and a sample from `hp.qlognormal('b', 1, 10, 1)` is `425.0` instead of `21669` and `425`.

Since sklearn.ensemble.RandomForestRegressor accept some arguments which can be
- floats between 0.0 and 1.0, or
- integers greater than 1,

this results in raised errors (since float `425.0` is greater than one).

**Comment by OlaRonning** [comment]
Have a similar problem when using `hyperopt` with NumPyro. Here is a minimal example:

``` python
from hyperopt import fmin, tpe, hp

def fn(x):
    print(type(x))  # <class 'float'>
    return x ** 2

if __name__ == "__main__":
    best = fmin(
        fn=fn,
        space=hp.quniform("x", -10, 10, 2),
        algo=tpe.suggest,
        max_evals=1,
    )
    print(best)

```
I'll gladly look at a fix.

**Comment by michaelmior** [comment]
This appears to be a duplicate of #253. Do any of the solutions in there work for you?

**Comment by OlaRonning** [comment]
@michaelmior Sorry missed the other thread. It's relatively easy to work around the problem with a typecast. 

However, the current behavior is a bit counterintuitive (and seems leaky). I'll gladly have a look at a fix.
