### ISSUE TITLE
Method maxNumConcurrentTasks([]) does not exist

### ISSUE THREAD

**Issue by sayinbu** [hyperopt/hyperopt#798]
Hello,

I have been using and loving this library for a while and first wanted to thank you for maintaining it.

I started receiving this error message after I upgraded my databricks runtime from `7.3 (Spark 3.0.1)` to `8.1 (Spark 3.1.1)` :
```Python
spark_trials = SparkTrials()
```
```
py4j.Py4JException: Method maxNumConcurrentTasks([]) does not exist
```

After a bit of research, I've found that this seems to be fixed in https://github.com/hyperopt/hyperopt/pull/765

My question is when do you plan to release this fix?

**Comment by omkarmore83** [comment]
Facing similar issue with [latest hyperopt from pypi](https://pypi.org/project/hyperopt/0.2.5/) and Spark 3.1

Any idea when this fix would be released?

**Comment by omkarmore83** [comment]
In our case, I am trying to use it outside of Databricks.

**Comment by summerela** [comment]
I'm using Databricks on Azure and hyperopt was not pre-installed. I installed it on the cluster and am getting the same error.

**Comment by sklingel** [comment]
So with the pyspark downgrade it also works in a single node cluster. I don't think this is particular related @summerela, you simply probably don't use spark for the parallelism anymore and this is why it started working.
