### ISSUE TITLE
Pickling Hyperopt stores hp.choice INDEX (not value)

### ISSUE THREAD

**Issue by loewenm** [hyperopt/hyperopt#800]
**This is more of a request that would greatly improve functionality of Hyperopt.**

When using pickle to store trials and the tested hyperparameters, pickle stores the index number of any _hp.choice_ search.

The problem with this is that if you attempt to query your dictionary of searchable parameters ("space"), then you'll get a python _switch_ statement when using the _hp.choice_ function only, not the actual value used in a specific trial. This requires the user to declare a _hp.choice_ searchable hyperparameter outside of the searchable _space_ dictionary, insert that parameter into the dictionary before feeding it to the fmin(). Then, in order, to get the value used, you'd index the results stored in the pickle file against each individual hyperparameter declared outside of the dictionary... That's a huge time sink and not very practical and not consistent with the other search functions.

**Solution:** Why not just have Hyperopt store the values used in each trial for _hp.choice_ as this would be consistent with all of the other search functions (e.g. hp.lognormal, hp.uniform, etc.)???

**Comment by sorinmuchi** [comment]
I think you might find this helpful: https://github.com/hyperopt/hyperopt/issues/761#issuecomment-718004328

**Comment by loewenm** [comment]
Masssively helpful! Thank you @sorinmuchi
