### ISSUE TITLE
Seeds in the fmin function

### ISSUE THREAD

**Issue by Leonardbcm** [hyperopt/hyperopt#809]
Hi everyone, I encountered a seed problem while trying to replicate a result.

The problem occured when I tried to recall the 'fmin' function with a higher number of iterations ('max_eval') but keeping the 'trials' object. As written in 'fmin' documentation:
> Each call to `algo` requires a seed value, which should be different
        on each call. This object is used to draw these seeds via `randint`.
        The default rstate is
        `numpy.random.RandomState(int(env['HYPEROPT_FMIN_SEED']))`

Thus, for replicability, I worked with the env['HYPEROPT_FMIN_SEED'] pre-set.
Each iteration's seed are sampled from this initial  set seed. The problem is, when we recall 'fmin', the iteration's seed sequence is reset and the seeds of the second call to 'fmin' are the same as the first one's.
This causes issues of replicability. The result of a call to 'fmin' with 10 iterations will not be the same than a first call with 5 iteration and a second one with 10 for instance.

Here is a straight-forward example to illustrate and reproduce the problem:

```python
import os
from hyperopt import fmin, tpe, hp, Trials

# set the seed for replicability
os.environ['HYPEROPT_FMIN_SEED'] = "1"

# Dumb function to optimize
def fn(hp_):    
    return hp_["x"] ** 2

# Build a space with a dummy hyper-parameter to track
space = {"x" : hp.uniform('x', -10, 10),
         "DUMMY" : hp.quniform("DUMMY", 1, 100, 1)}

# Initialize the trial object
trials = Trials()

# Run 5 evaluations
fmin(fn, space=space, algo=tpe.suggest, max_evals=5, trials=trials)

# Track the sampled dummies
dummies = [trials.trials[i]["misc"]["vals"]["DUMMY"][0] for i in range(len(trials.trials))]

# Re-run for 5 new iterations
fmin(fn, space=space, algo=tpe.suggest, max_evals=10, trials=trials)

# Track the sampled dummies
dummies2 = [trials.trials[i]["misc"]["vals"]["DUMMY"][0] for i in range(len(trials.trials))]

"""
The new sampled dummies are the same than the first ones. This is because the r_state
is refreshed to the state specified in os.environ['HYPEROPT_FMIN_SEED'] when we call fmin 
for the second time. Let's try to run 10 iterations in the first call
"""

# Refresh the trials
trials = Trials()
fmin(fn, space=space, algo=tpe.suggest, max_evals=10, trials=trials)
dummies3 = [trials.trials[i]["misc"]["vals"]["DUMMY"][0] for i in range(len(trials.trials))]

dummies 
> [68.0, 7.0, 34.0, 2.0, 42.0]
dummies2
> [68.0, 7.0, 34.0, 2.0, 42.0, 68.0, 7.0, 34.0, 2.0, 42.0]
dummies3
> [68.0, 7.0, 34.0, 2.0, 42.0, 37.0, 44.0, 11.0, 74.0, 52.0]
```

I hope this issue description is clear enough, feel free to ask questions if it's not the case.

The current solution I can think of is going back to the 'rstate' state's by generating 'n' seeds for nothing, 'n' being the number of previously ran trials stored in the 'trials' object. In my example, this would mean re-generating the first 5 seeds before starting any new iterations. 

Thanks by advance for your help.

**Comment by sank3t** [comment]
I hope the following will resolve your issue:

`fmin(f_lgbm, lgbm_param, algo=tpe.suggest, max_evals=MAX_EVAL, trials=trials, rstate=np.random.default_rng(SEED))`

**Source:** https://github.com/hyperopt/hyperopt/issues/838#issuecomment-992182546
