### ISSUE TITLE
RandomForestClassifier in search space yields "object has no attribute 'estimators_' " error

### ISSUE THREAD

**Issue by egregorimar** [hyperopt/hyperopt#823]
Hello,

I have defined a search space as follows:

```
space = hp.choice('classifiers', [
    {
        'model': KNeighborsClassifier(),
        'params':{
            'model__n_neighbors': hp.randint('n_neighbors', 2, 10),
            'model__algorithm': hp.choice('algorithm', ['auto', 'ball_tree', 'kd_tree']),
            'model__weights': hp.choice('weights', ['uniform', 'distance'])
            }
    },
    {
        'model' : RandomForestClassifier(),
        'params': {
            'model__n_estimators': hp.randint('n_estimators', 80, 120)
            }
    }
])
```

but I am getting the following error:
`AttributeError: 'RandomForestClassifier' object has no attribute 'estimators_'`

This only happens with `RandomForestClassifier`, if I change it for any other classifier (for example `DecisionTreeClassifier`) it works perfectly.

My current package versions are:
 
- `hyperopt==0.2.5`
- `scikit-learn==1.0`
- `numpy==1.21.2`

**Comment by mandjevant** [comment]
To fix this you should downgrade your scikit-learn to version 0.21.0. `pip install scikit-learn==0.21.0`
