### ISSUE TITLE
MongoDB error: Unknown option j

### ISSUE THREAD

**Issue by Young-chow** [hyperopt/hyperopt#836]
When I tried to optimize the hyper-parameters using hyperopt and Mongodb, hower, while the following codes were runned in spyder, the program ran wrong.
       from hyperopt.mongoexp import MongoTrials
       trials =  MongoTrials(arg='mongo://localhost:27017/foo_db/jobs', exp_key=('exp1'))
The tips were as follows:
      File "E:\Program\Anaconda3\lib\site-packages\pymongo\common.py", line 144, in raise_config_error
             raise ConfigurationError("Unknown option %s" % (key,))
I tried to exam whether the MongoDB had installed successfully. The following codes were used:
      from pymongo import MongoClient
     client=MongoClient()
     client
     MongoClient('localhost', 27017)
The results are:
     MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

**Comment by BaruchG** [comment]
I'm not sure what is causing this issue but it started occuring when pymongo was upgraded to 4.0.  Downgrading to 3.12.0 got rid of that error for me and things started working again.

**Comment by 87royalts87** [comment]
Hey... I had a short look into the Error. The parameter 'j' is never used. No Idea why `pymongo.MongoClient` in `hyperopt/mongoexp.py` is using it. However as it is passed as **kwargs I simply removed it. Looks usable so far.

Regards Stefan

**Comment by maxwnewcomer** [comment]
@BaruchG's fix worked for me, thanks sm.
