### ISSUE TITLE
'numpy.random.mtrand.RandomState' object has no attribute 'integers'

### ISSUE THREAD

**Issue by acmilannesta** [hyperopt/hyperopt#838]
When I try to run `fmin` and define `rstate` as `np.random.RandomState(SEED)`, I got the error

`'numpy.random.mtrand.RandomState' object has no attribute 'integers'`

My `fmin` call looks like this:
`fmin(f_lgbm, lgbm_param, algo=tpe.suggest, max_evals=MAX_EVAL, trials=trials, rstate=np.random.RandomState(SEED))`

I am running the latest hyperopt on conda python 3.8.6 on win11.

**Comment by rharish101** [comment]
`np.random.RandomState` was deprecated, so Hyperopt now uses `np.random.Generator`. Replace the fmin call with:

```python
fmin(f_lgbm, lgbm_param, algo=tpe.suggest, max_evals=MAX_EVAL, trials=trials, rstate=np.random.default_rng(SEED))
```

**Comment by ChesterXS** [comment]
> `np.random.RandomState` was deprecated, so Hyperopt now uses `np.random.Generator`. Replace the fmin call with:
> 
> ```python
> fmin(f_lgbm, lgbm_param, algo=tpe.suggest, max_evals=MAX_EVAL, trials=trials, rstate=np.random.default_rng(SEED))
> ```

This issue is back again on python 3.9, hyperopt 0.2.7.

I use the following code:

    def objective_(space):
        sm = SMOTE(random_state=seed)
        clf = XGBClassifier(learning_rate=space['learning_rate'],
                            max_depth=int(space['max_depth']),
                            n_estimators=int(space['n_estimators']),
                            reg_alpha=int(space['reg_alpha']),
                            gamma=space['gamma'],
                            reg_lambda=space['reg_lambda'],
                            subsample=space['subsample'],
                            colsample_bytree=space['colsample_bytree'],
                            min_child_weight=int(space['min_child_weight']),
                            max_delta_step=space['max_delta_step'],
                            n_jobs=-1,
                            random_state=seed
                            )
        pipe = make_pipeline(sm, clf)
        score = cross_val_score(pipe, x, y, scoring=scoring, cv=cv, n_jobs=-1)
        return {'loss': -score.mean(), 'status': STATUS_OK}

    trials = Trials()
    best_hyperparams = fmin(fn=objective_, space=space, algo=tpe.suggest, max_evals=20, trials=trials,
                            rstate=np.random.default_rng(seed))

Results are not repeatable each time I run the code. Please investigate.

**Comment by yustiks** [comment]
> `np.random.RandomState` was deprecated, so Hyperopt now uses `np.random.Generator`. Replace the fmin call with:
> 
> ```python
> fmin(f_lgbm, lgbm_param, algo=tpe.suggest, max_evals=MAX_EVAL, trials=trials, rstate=np.random.default_rng(SEED))
> ```

I replaced according to your advice, and now I have another problem:
```
================================================================================
ERROR in rec_eval                                                               
EXCEPTION                                                                       
<class 'AttributeError'>                                                        
'numpy.random.mtrand.RandomState' object has no attribute 'integers'            
NODE                                                                            
0 randint                                                                       
1   Literal{3}
2  size =
3   len
4     array_union
5       array_union
6         array_union
7           Literal{new_ids}
8  rng =
9   Literal{rng-placeholder}
================================================================================
  0%|                                    | 0/90 [00:00<?, ?trial/s, best loss=?]
Traceback (most recent call last):
  File "run_hyper.py", line 124, in <module>
    hyperopt_tune(args)
  File "run_hyper.py", line 38, in hyperopt_tune
    hp.run()
  File "/opt/conda/lib/python3.7/site-packages/recbole/trainer/hyper_tuning.py", line 416, in run
    early_stop_fn=self.early_stop_fn,
  File "/opt/conda/lib/python3.7/site-packages/hyperopt/fmin.py", line 554, in fmin
    rval.exhaust()
  File "/opt/conda/lib/python3.7/site-packages/hyperopt/fmin.py", line 357, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/opt/conda/lib/python3.7/site-packages/hyperopt/fmin.py", line 272, in run
    new_ids, self.domain, trials, np.random.randint(2 ** 31 - 1)
  File "/opt/conda/lib/python3.7/site-packages/recbole/trainer/hyper_tuning.py", line 127, in exhaustive_search
    domain.s_rng: rng,
  File "/opt/conda/lib/python3.7/site-packages/hyperopt/pyll/base.py", line 902, in rec_eval
    rval = scope._impls[node.name](*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/hyperopt/pyll/stochastic.py", line 100, in randint
    return rng.integers(low, high, size)
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'
```

any thoughts?

**Comment by yustiks** [comment]
> > `np.random.RandomState` was deprecated, so Hyperopt now uses `np.random.Generator`. Replace the fmin call with:
> > ```python
> > fmin(f_lgbm, lgbm_param, algo=tpe.suggest, max_evals=MAX_EVAL, trials=trials, rstate=np.random.default_rng(SEED))
> > ```
> 
> I replaced according to your advice, and now I have another problem:
> 
> ```
> ================================================================================
> ERROR in rec_eval                                                               
> EXCEPTION                                                                       
> <class 'AttributeError'>                                                        
> 'numpy.random.mtrand.RandomState' object has no attribute 'integers'            
> NODE                                                                            
> 0 randint                                                                       
> 1   Literal{3}
> 2  size =
> 3   len
> 4     array_union
> 5       array_union
> 6         array_union
> 7           Literal{new_ids}
> 8  rng =
> 9   Literal{rng-placeholder}
> ================================================================================
>   0%|                                    | 0/90 [00:00<?, ?trial/s, best loss=?]
> Traceback (most recent call last):
>   File "run_hyper.py", line 124, in <module>
>     hyperopt_tune(args)
>   File "run_hyper.py", line 38, in hyperopt_tune
>     hp.run()
>   File "/opt/conda/lib/python3.7/site-packages/recbole/trainer/hyper_tuning.py", line 416, in run
>     early_stop_fn=self.early_stop_fn,
>   File "/opt/conda/lib/python3.7/site-packages/hyperopt/fmin.py", line 554, in fmin
>     rval.exhaust()
>   File "/opt/conda/lib/python3.7/site-packages/hyperopt/fmin.py", line 357, in exhaust
>     self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
>   File "/opt/conda/lib/python3.7/site-packages/hyperopt/fmin.py", line 272, in run
>     new_ids, self.domain, trials, np.random.randint(2 ** 31 - 1)
>   File "/opt/conda/lib/python3.7/site-packages/recbole/trainer/hyper_tuning.py", line 127, in exhaustive_search
>     domain.s_rng: rng,
>   File "/opt/conda/lib/python3.7/site-packages/hyperopt/pyll/base.py", line 902, in rec_eval
>     rval = scope._impls[node.name](*args, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/hyperopt/pyll/stochastic.py", line 100, in randint
>     return rng.integers(low, high, size)
> AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'
> ```
> 
> any thoughts?

this was solved with the command:
```
pip install hyperopt==0.2.5
```

**Comment by rharish101** [comment]
> > `np.random.RandomState` was deprecated, so Hyperopt now uses `np.random.Generator`. Replace the fmin call with:
> > ```python
> > fmin(f_lgbm, lgbm_param, algo=tpe.suggest, max_evals=MAX_EVAL, trials=trials, rstate=np.random.default_rng(SEED))
> > ```
> 
> I replaced according to your advice, and now I have another problem:
> 
> ```
> ================================================================================
> ERROR in rec_eval                                                               
> EXCEPTION                                                                       
> <class 'AttributeError'>                                                        
> 'numpy.random.mtrand.RandomState' object has no attribute 'integers'            
> NODE                                                                            
> 0 randint                                                                       
> 1   Literal{3}
> 2  size =
> 3   len
> 4     array_union
> 5       array_union
> 6         array_union
> 7           Literal{new_ids}
> 8  rng =
> 9   Literal{rng-placeholder}
> ================================================================================
>   0%|                                    | 0/90 [00:00<?, ?trial/s, best loss=?]
> Traceback (most recent call last):
>   File "run_hyper.py", line 124, in <module>
>     hyperopt_tune(args)
>   File "run_hyper.py", line 38, in hyperopt_tune
>     hp.run()
>   File "/opt/conda/lib/python3.7/site-packages/recbole/trainer/hyper_tuning.py", line 416, in run
>     early_stop_fn=self.early_stop_fn,
>   File "/opt/conda/lib/python3.7/site-packages/hyperopt/fmin.py", line 554, in fmin
>     rval.exhaust()
>   File "/opt/conda/lib/python3.7/site-packages/hyperopt/fmin.py", line 357, in exhaust
>     self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
>   File "/opt/conda/lib/python3.7/site-packages/hyperopt/fmin.py", line 272, in run
>     new_ids, self.domain, trials, np.random.randint(2 ** 31 - 1)
>   File "/opt/conda/lib/python3.7/site-packages/recbole/trainer/hyper_tuning.py", line 127, in exhaustive_search
>     domain.s_rng: rng,
>   File "/opt/conda/lib/python3.7/site-packages/hyperopt/pyll/base.py", line 902, in rec_eval
>     rval = scope._impls[node.name](*args, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/hyperopt/pyll/stochastic.py", line 100, in randint
>     return rng.integers(low, high, size)
> AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'
> ```
> 
> any thoughts?

Seems to me that the recbole package hasn't been updated to use the latest hyperopt, since a `np.random.RandomState` object is being created somewhere. Please open an issue there, if you want to use the latest version.
