### ISSUE TITLE
Security issue in required library networkx

### ISSUE THREAD

**Issue by NorDar** [hyperopt/hyperopt#843]
Hi, 

The installation of hyperopt is blocked for me since it relies on the dependency networkx>=2.2. 
All networkx versions prior to 2.6 have a deserialization vulnerability: https://security.snyk.io/vuln/SNYK-PYTHON-NETWORKX-1062709

Is it possible to bump the networkx version to at least networkx>=2.6 ?

Thanks :)

**Comment by akx** [comment]
The specification `networkx>=2.2` should not prevent you from installing networkx 2.6 or newer.

**Comment by NorDar** [comment]
@akx This is actually true and I feel stupid right now. 
I think I have to go over the actual issue with the pip proxy used and try to figure out why a newer version was not installed.

Thanks and sorry.
