### ISSUE TITLE
Feature Request: an integer seed input for fmin

### ISSUE THREAD

**Issue by cjmcgill** [hyperopt/hyperopt#847]
Could fmin be changed so that there is the option to provide a seed as an integer rather than a numpy object?

With the change in numpy random integer support that was mentioned in #838, I'm having some version control trouble with my code that uses hyperopt's fmin function internally. If I pass it the old random state from numpy, it breaks on users with new dependency installations. If I pass it the new random state from numpy, it breaks on the users with old installations.

I'm going to try to sidestep the whole thing by setting it with the environment variable option ("HYPEROPT_FMIN_SEED"). But this seems like a more complicated way of just passing an integer seed to fmin as an argument, which is what I wish I could do.

It doesn't affect my dependency issue right now, because I need to support older versions of hyperopt for a while yet. But just thinking in the future, an integer seed input would be cleaner for some users.

**Comment by michaelmior** [comment]
Internally `HYPEROPT_FMIN_SEED` is just used in the default `rstate` value of `fmin`m `numpy.random.default_rng(int(env['HYPEROPT_FMIN_SEED']))`. If you want to pass an integer seed, you should be able to do `numpy.random.default_rng(int(YOUR_SEED_HERE))` without using the environment variable.
