### ISSUE TITLE
Hyperopt 0.2.7/0.2.6 version error: AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'

### ISSUE THREAD

**Issue by naomichx** [hyperopt/hyperopt#849]
I have the following error when I use fmin function with the latest versions:

   File ".../opt/anaconda3/lib/python3.9/site-packages/hyperopt/fmin.py",  in run
    new_ids, self.domain, trials, self.rstate.integers(2 ** 31 - 1)
AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'integers'

To avoid this error I tried to install older versions of hyperopt (0.2.5), but it this case I got another error: 
  File ".../hyper/_hypersearch.py", line 139, in objective_wrapper
    returned_dict = objective(dataset, config, **kwargs)
TypeError: objective() got an unexpected keyword argument 'leak'

Any ideas ?

Thank you in advance!

**Comment by nielei0128** [comment]
Could you tell me how you solve this problem? I have similar error.
Thank you in advance!!
