### ISSUE TITLE
Hyperopt search space issue in taking range values 

### ISSUE THREAD

**Issue by Harshitha-HM1999** [hyperopt/hyperopt#854]
I am getting the following error while executing the code -

```python 
s = {"epochs": hp.quniform("epochs",100,500,100),"batch_size": hp.quniform("batch_size",100,300,100),"generator_dim": hp.quniform("generator_dim",100,300,100),"discriminator_dim": hp.quniform("discriminator_dim",100,300,100)}

def objective(s):
    model_1 = CTGAN(epochs = s['epochs'], batch_size = s['batch_size'], generator_dim = [100,100,100], discriminator_dim =[100,100,100])
    model_1.fit(Input)
    dat_1 = model_1.sample(len(Input))
    ev = evaluate(dat_1,Input)
    return {'loss': ev, 'status': STATUS_OK}

trials = Trials()
best = fmin(fn = objective,
            space = s,
            max_evals = 80,
            algo = tpe.suggest,
            trials = trials)
best
```
    
##TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 
How can I fix this. how to assign range values to the parameters?

**Comment by michaelmior** [comment]
Can you show the complete stack trace?
