### ISSUE TITLE
Hyperopt doesn't throw any error for SparkTrials parallelism parameter value

### ISSUE THREAD

**Issue by sank3t** [hyperopt/hyperopt#858]
Hi There,

I was tuning a LightGBM model using hyperopt, I am new to this stuff. So, I set `max_evals=12` and `parallelism=32`.

These values led to not utilizing the parallelism of Spark. Then I go through the documentation available on [Databricks](https://docs.databricks.com/applications/machine-learning/automl-hyperparam-tuning/hyperopt-concepts.html#the-sparktrials-class) there is nothing mentioned regarding the trade-off between `max_evals` and `parallelism`.

Somehow after googling I found this [doc](http://hyperopt.github.io/hyperopt/scaleout/spark/) which explained the trade-off between these two parameters.

Can you guys add this feature that if the parallelism reaches more than `max_evals` it should throw an exception?

**Thanks,**
**Sanket Sharma**

**Comment by sank3t** [comment]
Hey Guys,

Any update on this.

**Comment by candalfigomoro** [comment]
@sank3t 
The dev team seems to have disappeared, I think hyperopt is basically abandonware. I suggest you try Optuna https://optuna.org for hyperparameter optimization on a single machine, or a random search if you want to use Spark.

**Comment by sank3t** [comment]
Hi @candalfigomoro,

Have you tried Optuna before?

Does it support all libraries? Any upper bound on the dataset size?

**Comment by sank3t** [comment]
I think it seems to be abandonware. Is there any official announcement?
