### ISSUE TITLE
Formally drop support for Python 2

### ISSUE THREAD

**Issue by rparini** [hyperopt/hyperopt#864]
As of https://github.com/hyperopt/hyperopt/pull/831 hyperopt requires `numpy>=1.17` but numpy 1.16 [was the last to support Python 2 ](https://docs.scipy.org/doc/numpy-1.16.1/release.html) so effectively hyperopt does not support Python 2 anymore. The setup.py and documentation should be changed to reflect this and it looks like the `future` library should not be needed anymore.

I'd be happy to submit a PR if a maintainer is happy with this suggestion.

**Comment by akx** [comment]
Not to mention caa3c2425de055d885b59acf5bd921e5dae33eb0, which added pyupgrade for 3.7+ syntax only. :)
