### ISSUE TITLE
Recommended way to log python debug statements when using SparkTrials

### ISSUE THREAD

**Issue by JasperHG90** [hyperopt/hyperopt#867]
Hi,

I'm using hyperopt and sparktrials on databricks to optimize the hyperparameters for my ML model.

In my objective function, I'm creating debug statements using a standard python logging setup, and I'd be able to capture those logs for later analysis.

These logs are not showing up, which makes sense. Do you have any pointers / best practices for logging using such a setup?

Thanks in advance!

Jasper.

**Comment by lu-wang-dl** [comment]
Depends on what you want to do with these logs. If you just want to check these logs. You can go to the worker stderr logs from spark UI (https://mallikarjuna_g.gitbooks.io/spark/content/spark-webui-executors.html). You should see the loggings.

If you want to capture and save the logs, you may return it in the objective functions and collect the messages from SparkTrial. If you are using mlflow in your objective function, log them into mlflow is another option too.

**Comment by JasperHG90** [comment]
Thanks for your reply. We're storing the logs in Azure Application Insights. Given that the executors run on their own python process, I'm currently setting up logging using python and adding the handler in the objective function, which works fine.
