### ISSUE TITLE
[Feature] Support SparkTrials for SparkML models

### ISSUE THREAD

**Issue by serena-ruan** [hyperopt/hyperopt#869]
Hi team,

Now SparkTrials only supports running single-machine training algorithms, so we can only train SparkML models in series instead of in parallel. I think if we could support training distributed training algorithms in parallel that would satisfy a lot of users' needs. 
I investigated a bit on hyperopt's source code of SparkTrials, and have tested my changes for supporting this locally. 
I'm wondering what's the contributing process for this and what do you think about this feature request? If you have any concerns, please let me know and we could also have a discussion. If you think this is a reasonable request, then could I go ahead and raise a PR for review?

Thanks!

**Comment by serena-ruan** [comment]
@maxpumperla @WeichenXu123 for awareness 😃

**Comment by WeichenXu123** [comment]
My concern is,
because spark trials run model training inside spark task, if we want to support spark Model, then we need to initiate spark session (local mode) in spark task side, and run nested spark jobs in spark task side.
This might be tricky and it cannot adapt to spark resource allocation well.

**Comment by cloud-fan** [comment]
It will be a big feature to support launching Spark jobs on the task side.

**Comment by serena-ruan** [comment]
The idea is that we run spark jobs in parallel, instead of triggering spark jobs in the task. If the spark schedular mode is FAIR then we can run spark jobs in parallel, and each job can be a distributed training job that maps to tasks on executors. Does this make sense?

**Comment by serena-ruan** [comment]
> > The idea is that we run spark jobs in parallel, instead of triggering spark jobs in the task. If the spark schedular mode is FAIR then we can run spark jobs in parallel, and each job can be a distributed training job that maps to tasks on executors. Does this make sense?
> 
> Yes. This make sense. This case we can use default hyperopt Trial, It will run all hyperopt subtask from spark driver side (i.e. launch all spark jobs from spark driver side.

But Trials is running spark jobs in series, there's a for loop right that only launches the next job after the first one finishes (Or do I misunderstand here?). My thought is to add one simple parameter in SparkTrials that controls if we're training spark models, then instead of making a 1 partition rdd and map the task onto it, we directly run the distributed job.

**Comment by serena-ruan** [comment]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/82044803/200714106-6d87617f-37e0-4f08-a484-97b950f5dbcd.png">
Something like this

**Comment by WeichenXu123** [comment]
> Trials is running spark jobs in series

Oh I get your point.

https://github.com/hyperopt/hyperopt/issues/192 
this mongo backend already supports run in parallel.

We can implement another Trial class which supports parallelly running without mongodb,
but I think we should not reuse `SparkTrial` name, we can name it `ParallelTrial`

**Comment by serena-ruan** [comment]
> We can implement another Trial class which supports parallelly running without mongodb, but I think we should not reuse `SparkTrial` name, we can name it `ParallelTrial`

This also makes sense! So, in this new ParallelTrial it just runs jobs in parallel and no matter what kind of jobs. How should we kick off this task :D

**Comment by WeichenXu123** [comment]
> So, in this new ParallelTrial it just runs jobs in parallel and no matter what kind of jobs.

Yes you get it !

**Comment by serena-ruan** [comment]
@WeichenXu123 Can I go ahead and build this then let you review?

**Comment by WeichenXu123** [comment]
> @WeichenXu123 Can I go ahead and build this then let you review?

Yes you can. Note that I am not maintainer of hyperopt repo, you need maintainer's review and approval as well.

**Comment by serena-ruan** [comment]
Thanks!  @jaberg @yamins81 @maxpumperla I'm not sure who is the maintainer as there's no OWNERS file so tagging top contributors here 😅 What do you think about this plan?
