### ISSUE TITLE
ModuleNotFoundError: No module named 'hyperopt'

### ISSUE THREAD

**Issue by MuhammadIrfanAli** [hyperopt/hyperopt#879]
I am trying to perform hyperparameter sweep with Catboost using Databricks notebook but running into following error:
```
Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/worker.py", line 752, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/databricks/spark/python/pyspark/worker.py", line 75, in read_command
    command = serializer.loads(command.value)
  File "/databricks/spark/python/pyspark/serializers.py", line 466, in loads
    return pickle.loads(obj, encoding=encoding)
ModuleNotFoundError: No module named 'hyperopt'
```

I don't understand why I am getting this error when I have `hyperopt` installed via pip. I am able to import it: 
```
import hyperopt
hyperopt.__version__ #0.2.7
```
Similary no issues with the following imports either:
```
from hyperopt import fmin, hp, tpe, SparkTrials, STATUS_OK
```

**Comment by lu-wang-dl** [comment]
This should be a Databricks specific issue. Could you help provide some example code so that we can look into it?

**Comment by michaelmior** [comment]
Closing as this does appear to be a Databricks-specific issue. But please reopen if you have more details.
