### ISSUE TITLE
Grid search

### ISSUE THREAD

**Issue by mathiasottenbreit** [hyperopt/hyperopt#892]
It would be useful if hyperopt also offered the possibility of doing grid search. Sometimes grid search may be the most feasible choice, for example when testing a hyperparameter that has a few discrete integers as possible values.

**Comment by michaelmior** [comment]
Have you tried random search? This should also be able to solve this use case.

**Comment by Dv04** [comment]
I have made GridSearch blocks for Machine Learning before. Can I get more details of this particular issue? I would like to solve it if possible.

**Comment by michaelmior** [comment]
@Dv04 Currently I believe hyperopt only implements random search, although that implementation appears to be incomplete. You can see that implementation in [`rand.py`](https://github.com/hyperopt/hyperopt/blob/master/hyperopt/rand.py).

**Comment by Dv04** [comment]
@michaelmior Ah yes. Sorry for not going through the other algorithms before. I assumed this Issue to be about adding Grid Search functionality to the project.

**Comment by michaelmior** [comment]
That is indeed what this issue is about :) Random search and grid search are somewhat distinct although arguably grid search is not necessary if random search is implemented.
