### ISSUE TITLE
Numpy 1.25.1  AttributeError: module 'numpy' has no attribute 'warnings'

### ISSUE THREAD

**Issue by MMCMA** [hyperopt/hyperopt#894]
I get the following error when running a hyperopt instance with numpy 1.25.1

```
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/hyperopt/fmin.py", line 540, in fmin
    return trials.fmin(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/hyperopt/base.py", line 671, in fmin
    return fmin(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/hyperopt/fmin.py", line 586, in fmin
    rval.exhaust()
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/hyperopt/fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/hyperopt/fmin.py", line 278, in run
    new_trials = algo(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/hyperopt/atpe.py", line 1603, in suggest
    parameters = optimizer.recommendNextParameters(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/hyperopt/atpe.py", line 744, in recommendNextParameters
    stats = self.computeAllResultStatistics(hyperparameterSpace, results)
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/hyperopt/atpe.py", line 1459, in computeAllResultStatistics
    allResultStatistics = self.computePartialResultStatistics(
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/hyperopt/atpe.py", line 1274, in computePartialResultStatistics
    numpy.warnings.filterwarnings("ignore")
  File "/opt/conda/envs/py310/lib/python3.10/site-packages/numpy/__init__.py", line 322, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'warnings'
```

Here are some more infos on my system:
INSTALLED VERSIONS
------------------
python           : 3.10.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.19.0-46-generic
Version          : #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : C.UTF-8
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.25.1
pytz             : 2023.3
dateutil         : 2.8.2
setuptools       : 68.0.0
pip              : 23.1.2
Cython           : 0.29.36
pytest           : 7.4.0
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.1.2
IPython          : 8.14.0
pandas_datareader: 0.10.0
bs4              : 4.12.2
bottleneck       : None
brotli           :
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.7.2
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.1.2
pandas_gbq       : None
pyarrow          : 11.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.10.1
snappy           : None
sqlalchemy       : 1.4.49
tables           : None
tabulate         : 0.9.0
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
tzdata           : 2023.3

**Comment by HahaLan97** [comment]
I've run into the same problem, is there any solution now? I see that there is one line in tpe.py file:
```
numpy.warnings.filterwarnings("ignore")
```
Maybe this caused the error?

**Comment by pangjac** [comment]
numpy.bool is deprecated. Downgrade numpy to version 1.23.1 would work. By the way, I did not see a `requirements.txt` or `*.toml` to enforce package version, am I missing something ?

**Comment by stevetracvc** [comment]
Another option is:


```
import warnings
np.warnings = warnings
```

and then you don't have to downgrade (clearly not the best approach, but if you can't downgrade then this will fix it)

**Comment by stevetracvc** [comment]
> I have the same issue, somebody could fix it?

What have you tried already? Did you try downgrading your numpy package like @pangjac suggested? Or did you try the code snippet I provided?

**Comment by stevetracvc** [comment]
They did. You have an old version of hyperopt.

https://github.com/hyperopt/hyperopt/pull/874
