### ISSUE TITLE
TypeError: ap_uniform_sampler() got multiple values for argument 'size'

### ISSUE THREAD

**Issue by Kamran21st** [hyperopt/hyperopt#900]
TypeError                                 Traceback (most recent call last)
Cell In[388], line 13
     10     return {'loss': -accuracy,"status":STATUS_OK}
     12 trials=Trials()
---> 13 best5=fmin(fn=objective,
     14            space=space,
     15            algo=tpe.suggest,
     16            max_evals=25,
     17            trials=trials)
     18 best5

**Comment by michaelmior** [comment]
@Kamran21st Can you provide some example code? It's not really possible to do any debugging with the information here.
