### ISSUE TITLE
Updating loss values in Mongo

### ISSUE THREAD

**Issue by btyukodi** [hyperopt/hyperopt#902]
Is it possible to update the loss values in the job collection?

I realized that I worked with the wrong objective function but I don't want to loose the already completed function evaluations. With all the data I saved, I am able to map the existing loss values to the new, correct values. I was wondering whether I can simply update them in Mongo and keep running the optimization? 

I see that there are other collections in the database as well (drivers, fs.chunks, fs.files, job_ids) and wanted to make sure that simply updating loss values in the job collection does not lead to inconsistencies in further evaluations.

Thank you.

**Comment by michaelmior** [comment]
There's no way to have hyperopt do this, but modifying the values manually in Mongo and continuing should do the right thing. Unsurprisingly, this hasn't been tested. I would suggest backing up your MongoDB database and giving it a try.

**Comment by btyukodi** [comment]
@michaelmior , thank you. It appears to work well.
