### ISSUE TITLE
Sample space multiple times

### ISSUE THREAD

**Issue by khayamgondal** [hyperopt/hyperopt#908]
I have  5 cameras and 3 possible FOVs for each camera. I would like to construct a space where each camera is assigned a random FOV from the list of FOVs. I can do this for a single camera like below but wondering how can I achieve the same for 5 cameras?
Note: cameras could be more or less than 5

```
fovs = [72, 1 , 75]
n_cams = 5

space = {
   "fov" : hp.choice("cam_fovs", fovs)
}

```
Output
```
print (hyperopt.pyll.stochastic.sample(space))
{'fov': 72}
```

**Comment by khayamgondal** [comment]
I am doing it like following, not sure if its the best approach 

```
space = {
   "fov" : [hp.choice("cam_fovs", fovs) for _ in range(n_cams)]
}
```

**Comment by ayushtankha** [comment]
> I am doing it like following, not sure if its the best approach
> 
> ```
> space = {
>    "fov" : [hp.choice("cam_fovs", fovs) for _ in range(n_cams)]
> }
> ```
Instead try following -

space = {
    f"fov_{i}": hp.choice(f"cam_fovs_{i}", fovs) for i in range(n_cams)
}
