### ISSUE TITLE
Include Swarm Optimization Techniques

### ISSUE THREAD

**Issue by dtommandru** [hyperopt/hyperopt#917]
I am currently doing my thesis and I am using swarm intelligence techniques for tuning hyperparameters of classification models. One of the classic techniques is PSO, and there are galore of techniques being used. Is there a way to include the PSO in Hyperopt? I can contribute if I can get some help.

**Comment by leoknuth** [comment]
Just use `pyswarms`

**Comment by michaelmior** [comment]
@dtommandru hyperopt supports whatever algorithm you like for suggesting new runs. The built-in algorithms include TPE, random, annealing, as well as a mixture of any of the above. I would suggest you look at the existing implementations as a base for any new algorithm you might want to implement.
