### ISSUE TITLE
MongoDB error with pymongo>4: Unknown option j

### ISSUE THREAD

**Issue by Cmurilochem** [hyperopt/hyperopt#920]
This bug was discussed before in #836 and #845 but it seems that it still persists whenever instantiating `pymongo.MongoClient` in `hyperopt/mongoexp.py` with `pymongo>4`. In #836, it looks like a provisory solution was provided:

> .... The parameter 'j' is never used. No Idea why `pymongo.MongoClient` in `hyperopt/mongoexp.py` is using it. However as it is passed as **kwargs I simply removed it. Looks usable so far pymongo/mongo_client.py:

But I suspect that this has never been implemented into `main` ? If not, please, could this be done ?
Noticed that there is some discussions about the deprecation of the `j` option that should be replaced by `journal` when launching `mongod`. The problem here is that this error appears even without using the `journal` option in `mongod`.

Any clues?

Thanks
Carlos

**Comment by jaberg** [comment]
Looks fixed in #859
