### ISSUE TITLE
"IndexError: list index out of range" in rec_eval when using ATPE

### ISSUE THREAD

**Issue by ascripter** [hyperopt/hyperopt#925]
Using hyperopt 0.2.7 on Windows 10 and python 3.9.15
```
  File "c:\users\pfa2ba\documents\untitled0.py", line 46, in <module>
    best = fmin(train_func, space, **fmin_params)

  File "C:\Users\pfa2ba\.conda\envs\ML39\lib\site-packages\hyperopt\fmin.py", line 540, in fmin
    return trials.fmin(

  File "C:\Users\pfa2ba\.conda\envs\ML39\lib\site-packages\hyperopt\base.py", line 671, in fmin
    return fmin(

  File "C:\Users\pfa2ba\.conda\envs\ML39\lib\site-packages\hyperopt\fmin.py", line 586, in fmin
    rval.exhaust()

  File "C:\Users\pfa2ba\.conda\envs\ML39\lib\site-packages\hyperopt\fmin.py", line 364, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)

  File "C:\Users\pfa2ba\.conda\envs\ML39\lib\site-packages\hyperopt\fmin.py", line 300, in run
    self.serial_evaluate()

  File "C:\Users\pfa2ba\.conda\envs\ML39\lib\site-packages\hyperopt\fmin.py", line 178, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)

  File "C:\Users\pfa2ba\.conda\envs\ML39\lib\site-packages\hyperopt\base.py", line 887, in evaluate
    pyll_rval = pyll.rec_eval(

  File "C:\Users\pfa2ba\.conda\envs\ML39\lib\site-packages\hyperopt\pyll\base.py", line 856, in rec_eval
    rval_var = node.pos_args[int(switch_i) + 1]
```

The following script tries to narrow down the problem, but since the exception occurs stochastically (usually after executing 2 or 3 times, I tested up to 20), I can't be fully sure what triggers it and what not:

```
from hyperopt import hp, fmin, STATUS_OK, Trials, atpe, tpe
import numpy as np

space = {
    "kernel": hp.choice("kernel", ["poly", "rbf", "sigmoid"]),
    "C": hp.qloguniform("C", np.log(0.001), np.log(1), 0.001),
}


def train_func(params: dict):
    return {
        "loss": -np.random.random(),
        "status": STATUS_OK,
    }


for i in range(20):
    fmin_params = dict(max_evals=30, trials=Trials(), algo=atpe.suggest)
    best = fmin(train_func, space, **fmin_params)
```

The cause seems to be that the variable `switch_i` in the function `rec_eval` in line 846 of `pyll/base.py` is 3 while it should be between 0 and 2. 

The exception **does not happen** when either of this is changed:
- Use `tpe` instead of `atpe`
- Use only a single `hp.choice` in the space w/o any other variables

The exception **still is triggered** when changing:
- second variable as `hp.choice` instead of `hp.qloguniform`
- decreasing or increasing the number of choices between 1 and 6 (though larger values make occurrence less probable)

Also, adding `rstate=np.random.default_rng(42)` as parameter to the `fmin`-call didn't introduce reproducibility (that surprised me most). So it may happen somewhere where randomness is unaffected by that `rstate` generator.

**Comment by ascripter** [comment]
The root cause is most probably in `atpe.py` line 1258.
```
def chooseRandomValueForParameter(self, parameter):
    ...
    value = random.randint(min, max)
```

The definition of `parameter.config["max"]` is 3 and not 2 in my case. Since [python's random module](https://docs.python.org/3.9/library/random.html#random.randint) is used, the `max` is *inclusive* (while [`numpy.random.randint()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html) would be *exclusive* of the max value). This also explains why initializing `rstate` with a numpy random generator has no effect here.

I realized this function is rarely ever called, only after 10 initialization rounds and certain conditions for the ATPE-parameters. That's why it rarely occurs.

**Comment by fedorkanin** [comment]
This is a known issue, you may fix it manually for now:
https://github.com/hyperopt/hyperopt/issues/768#issuecomment-751690497

This does not close the issue, as the solution is not merged
