### ISSUE TITLE
hyperopt's usage of NetworkX: API usage and slowdowns

### ISSUE THREAD

**Issue by nv-rliu** [hyperopt/hyperopt#934]
Hi. I would like to understand what parts of `hyperopt` depend on algorithms from Networkx. What nx API calls it uses the most, for what purposes, and if you've ever experienced any slowdowns when scaling up graph sizes?

I did a quick search for previous issues related to NetworkX Usage, but I was wondering if you had any more insight into this topic. Thank you

**Comment by michaelmior** [comment]
NetworkX is only used for topological sort. I'm not aware of any issues people have experienced with this since the graphs are typically not very large.
